# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_hmss_0_0/bd_0/ip/ip_5/bd_85ad_vip_S00_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_85ad_vip_S00_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_hmss_0_0/bd_0/ip/ip_5/bd_85ad_vip_S00_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_85ad_vip_S00_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
