// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module krnl_proj_split_merge_matches (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        short_matches_dout,
        short_matches_num_data_valid,
        short_matches_fifo_cap,
        short_matches_empty_n,
        short_matches_read,
        long_matches_dout,
        long_matches_num_data_valid,
        long_matches_fifo_cap,
        long_matches_empty_n,
        long_matches_read,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        p_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [32:0] short_matches_dout;
input  [6:0] short_matches_num_data_valid;
input  [6:0] short_matches_fifo_cap;
input   short_matches_empty_n;
output   short_matches_read;
input  [32:0] long_matches_dout;
input  [6:0] long_matches_num_data_valid;
input  [6:0] long_matches_fifo_cap;
input   long_matches_empty_n;
output   long_matches_read;
output  [511:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [63:0] output_stream_TKEEP;
output  [63:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [15:0] output_stream_TDEST;
input  [15:0] p_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg short_matches_read;
reg long_matches_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_stream_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln184_fu_146_p2;
wire    ap_CS_fsm_state5;
reg   [0:0] icmp_ln184_reg_182;
reg    ap_block_state1;
reg    ap_block_state4;
reg    ap_block_state4_io;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_idle;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_ready;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read;
wire   [511:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TREADY;
wire   [63:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP;
wire   [63:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB;
wire   [0:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER;
wire   [0:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST;
wire   [0:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID;
wire   [15:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST;
wire   [511:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out_ap_vld;
wire   [63:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out_ap_vld;
wire   [31:0] grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out;
wire    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out_ap_vld;
reg    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [511:0] out_data_6_loc_fu_68;
reg   [63:0] out_keep_6_loc_fu_64;
reg   [31:0] out_count_loc_fu_60;
wire    regslice_both_output_stream_V_data_V_U_apdone_blk;
reg    ap_block_state5;
reg    ap_block_state5_io;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg   [511:0] output_stream_TDATA_int_regslice;
reg    output_stream_TVALID_int_regslice;
wire    output_stream_TREADY_int_regslice;
wire    regslice_both_output_stream_V_data_V_U_vld_out;
wire    regslice_both_output_stream_V_keep_V_U_apdone_blk;
reg   [63:0] output_stream_TKEEP_int_regslice;
wire    regslice_both_output_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_keep_V_U_vld_out;
wire    regslice_both_output_stream_V_strb_V_U_apdone_blk;
reg   [63:0] output_stream_TSTRB_int_regslice;
wire    regslice_both_output_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_strb_V_U_vld_out;
wire    regslice_both_output_stream_V_user_V_U_apdone_blk;
reg   [0:0] output_stream_TUSER_int_regslice;
wire    regslice_both_output_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_user_V_U_vld_out;
wire    regslice_both_output_stream_V_last_V_U_apdone_blk;
reg   [0:0] output_stream_TLAST_int_regslice;
wire    regslice_both_output_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_last_V_U_vld_out;
wire    regslice_both_output_stream_V_id_V_U_apdone_blk;
reg   [0:0] output_stream_TID_int_regslice;
wire    regslice_both_output_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_id_V_U_vld_out;
wire    regslice_both_output_stream_V_dest_V_U_apdone_blk;
reg   [15:0] output_stream_TDEST_int_regslice;
wire    regslice_both_output_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_output_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg = 1'b0;
end

krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1 grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start),
    .ap_done(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done),
    .ap_idle(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_idle),
    .ap_ready(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_ready),
    .short_matches_dout(short_matches_dout),
    .short_matches_num_data_valid(7'd0),
    .short_matches_fifo_cap(7'd0),
    .short_matches_empty_n(short_matches_empty_n),
    .short_matches_read(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read),
    .long_matches_dout(long_matches_dout),
    .long_matches_num_data_valid(7'd0),
    .long_matches_fifo_cap(7'd0),
    .long_matches_empty_n(long_matches_empty_n),
    .long_matches_read(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read),
    .p_read(p_read),
    .output_stream_TDATA(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA),
    .output_stream_TVALID(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID),
    .output_stream_TREADY(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TREADY),
    .output_stream_TKEEP(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP),
    .output_stream_TSTRB(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB),
    .output_stream_TUSER(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER),
    .output_stream_TLAST(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST),
    .output_stream_TID(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID),
    .output_stream_TDEST(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST),
    .out_data_6_out(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out),
    .out_data_6_out_ap_vld(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out_ap_vld),
    .out_keep_6_out(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out),
    .out_keep_6_out_ap_vld(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out_ap_vld),
    .out_count_out(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out),
    .out_count_out_ap_vld(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out_ap_vld)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 512 ))
regslice_both_output_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TDATA_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(output_stream_TREADY_int_regslice),
    .data_out(output_stream_TDATA),
    .vld_out(regslice_both_output_stream_V_data_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_data_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TKEEP_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_keep_V_U_ack_in_dummy),
    .data_out(output_stream_TKEEP),
    .vld_out(regslice_both_output_stream_V_keep_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_keep_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 64 ))
regslice_both_output_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TSTRB_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_strb_V_U_ack_in_dummy),
    .data_out(output_stream_TSTRB),
    .vld_out(regslice_both_output_stream_V_strb_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_strb_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TUSER_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_user_V_U_ack_in_dummy),
    .data_out(output_stream_TUSER),
    .vld_out(regslice_both_output_stream_V_user_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_user_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TLAST_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_last_V_U_ack_in_dummy),
    .data_out(output_stream_TLAST),
    .vld_out(regslice_both_output_stream_V_last_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_last_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TID_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_id_V_U_ack_in_dummy),
    .data_out(output_stream_TID),
    .vld_out(regslice_both_output_stream_V_id_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_id_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(output_stream_TDEST_int_regslice),
    .vld_in(output_stream_TVALID_int_regslice),
    .ack_in(regslice_both_output_stream_V_dest_V_U_ack_in_dummy),
    .data_out(output_stream_TDEST),
    .vld_out(regslice_both_output_stream_V_dest_V_U_vld_out),
    .ack_out(output_stream_TREADY),
    .apdone_blk(regslice_both_output_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg <= 1'b1;
        end else if ((grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_ready == 1'b1)) begin
            grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
        icmp_ln184_reg_182 <= icmp_ln184_fu_146_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out_ap_vld == 1'b1))) begin
        out_count_loc_fu_60 <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out_ap_vld == 1'b1))) begin
        out_data_6_loc_fu_68 <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out_ap_vld == 1'b1))) begin
        out_keep_6_loc_fu_64 <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5))) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        long_matches_read = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read;
    end else begin
        long_matches_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln184_reg_182 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((icmp_ln184_reg_182 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY_int_regslice;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_stream_TDATA_int_regslice = out_data_6_loc_fu_68;
    end else if (((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        output_stream_TDATA_int_regslice = 512'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TDATA_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA;
    end else begin
        output_stream_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TDEST_int_regslice = p_read;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TDEST_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST;
    end else begin
        output_stream_TDEST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TID_int_regslice = 'bx;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TID_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID;
    end else begin
        output_stream_TID_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        output_stream_TKEEP_int_regslice = out_keep_6_loc_fu_64;
    end else if (((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        output_stream_TKEEP_int_regslice = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TKEEP_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP;
    end else begin
        output_stream_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TLAST_int_regslice = 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TLAST_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST;
    end else begin
        output_stream_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TSTRB_int_regslice = 'bx;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TSTRB_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB;
    end else begin
        output_stream_TSTRB_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b0 == ap_block_state4) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TUSER_int_regslice = 'bx;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID == 1'b1))) begin
        output_stream_TUSER_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER;
    end else begin
        output_stream_TUSER_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (icmp_ln184_fu_146_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (icmp_ln184_fu_146_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        output_stream_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        output_stream_TVALID_int_regslice = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID;
    end else begin
        output_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        short_matches_read = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read;
    end else begin
        short_matches_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5)) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state4 = (((icmp_ln184_fu_146_p2 == 1'd0) & (output_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln184_fu_146_p2 == 1'd1) & (output_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = (((icmp_ln184_fu_146_p2 == 1'd0) & (output_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln184_fu_146_p2 == 1'd1) & (output_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state5 = ((regslice_both_output_stream_V_data_V_U_apdone_blk == 1'b1) | ((icmp_ln184_reg_182 == 1'd0) & (output_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln184_reg_182 == 1'd1) & (output_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state5_io = (((icmp_ln184_reg_182 == 1'd0) & (output_stream_TREADY_int_regslice == 1'b0)) | ((icmp_ln184_reg_182 == 1'd1) & (output_stream_TREADY_int_regslice == 1'b0)));
end

assign grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start = grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg;

assign grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TREADY = (output_stream_TREADY_int_regslice & ap_CS_fsm_state3);

assign icmp_ln184_fu_146_p2 = (($signed(out_count_loc_fu_60) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign output_stream_TVALID = regslice_both_output_stream_V_data_V_U_vld_out;

endmodule //krnl_proj_split_merge_matches
