# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/bd_7cf0.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0 || ORIG_REF_NAME==bd_7cf0} -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/ip/ip_0/bd_7cf0_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0_axi_jtag_0 || ORIG_REF_NAME==bd_7cf0_axi_jtag_0} -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/ip/ip_1/bd_7cf0_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0_bsip_0 || ORIG_REF_NAME==bd_7cf0_bsip_0} -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/ip/ip_2/bd_7cf0_bs_switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0_bs_switch_1_0 || ORIG_REF_NAME==bd_7cf0_bs_switch_1_0} -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/bd_7cf0_ooc.xdc

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_0/ip/ip_2/bd_097b_user_debug_bridge_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_097b_user_debug_bridge_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# Block Designs: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/bd_7cf0.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0 || ORIG_REF_NAME==bd_7cf0} -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/ip/ip_0/bd_7cf0_axi_jtag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0_axi_jtag_0 || ORIG_REF_NAME==bd_7cf0_axi_jtag_0} -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/ip/ip_1/bd_7cf0_bsip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0_bsip_0 || ORIG_REF_NAME==bd_7cf0_bsip_0} -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/ip/ip_2/bd_7cf0_bs_switch_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7cf0_bs_switch_1_0 || ORIG_REF_NAME==bd_7cf0_bs_switch_1_0} -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_1/bd_7cf0_ooc.xdc

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ulp_cmp_0/bd_0/ip/ip_2/bd_097b_user_debug_bridge_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_097b_user_debug_bridge_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
