-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_proj_split_merge_matches is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    short_matches_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    short_matches_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    short_matches_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    short_matches_empty_n : IN STD_LOGIC;
    short_matches_read : OUT STD_LOGIC;
    long_matches_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    long_matches_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    long_matches_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    long_matches_empty_n : IN STD_LOGIC;
    long_matches_read : OUT STD_LOGIC;
    output_stream_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    output_stream_TVALID : OUT STD_LOGIC;
    output_stream_TREADY : IN STD_LOGIC;
    output_stream_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_stream_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDEST : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_read : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of krnl_proj_split_merge_matches is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln184_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln184_reg_182 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_idle : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_ready : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TREADY : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out_ap_vld : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out_ap_vld : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out_ap_vld : STD_LOGIC;
    signal grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal out_data_6_loc_fu_68 : STD_LOGIC_VECTOR (511 downto 0);
    signal out_keep_6_loc_fu_64 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_count_loc_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal regslice_both_output_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal output_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal output_stream_TVALID_int_regslice : STD_LOGIC;
    signal output_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal output_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_output_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal output_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_output_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal output_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_output_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal output_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_output_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal output_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_output_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal output_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_output_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        short_matches_dout : IN STD_LOGIC_VECTOR (32 downto 0);
        short_matches_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        short_matches_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        short_matches_empty_n : IN STD_LOGIC;
        short_matches_read : OUT STD_LOGIC;
        long_matches_dout : IN STD_LOGIC_VECTOR (32 downto 0);
        long_matches_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        long_matches_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        long_matches_empty_n : IN STD_LOGIC;
        long_matches_read : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        output_stream_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        output_stream_TVALID : OUT STD_LOGIC;
        output_stream_TREADY : IN STD_LOGIC;
        output_stream_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
        output_stream_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        output_stream_TDEST : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_data_6_out : OUT STD_LOGIC_VECTOR (511 downto 0);
        out_data_6_out_ap_vld : OUT STD_LOGIC;
        out_keep_6_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_keep_6_out_ap_vld : OUT STD_LOGIC;
        out_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_count_out_ap_vld : OUT STD_LOGIC );
    end component;


    component krnl_proj_split_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109 : component krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start,
        ap_done => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done,
        ap_idle => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_idle,
        ap_ready => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_ready,
        short_matches_dout => short_matches_dout,
        short_matches_num_data_valid => ap_const_lv7_0,
        short_matches_fifo_cap => ap_const_lv7_0,
        short_matches_empty_n => short_matches_empty_n,
        short_matches_read => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read,
        long_matches_dout => long_matches_dout,
        long_matches_num_data_valid => ap_const_lv7_0,
        long_matches_fifo_cap => ap_const_lv7_0,
        long_matches_empty_n => long_matches_empty_n,
        long_matches_read => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read,
        p_read => p_read,
        output_stream_TDATA => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA,
        output_stream_TVALID => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID,
        output_stream_TREADY => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TREADY,
        output_stream_TKEEP => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP,
        output_stream_TSTRB => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB,
        output_stream_TUSER => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER,
        output_stream_TLAST => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST,
        output_stream_TID => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID,
        output_stream_TDEST => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST,
        out_data_6_out => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out,
        out_data_6_out_ap_vld => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out_ap_vld,
        out_keep_6_out => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out,
        out_keep_6_out_ap_vld => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out_ap_vld,
        out_count_out => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out,
        out_count_out_ap_vld => grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out_ap_vld);

    regslice_both_output_stream_V_data_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TDATA_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => output_stream_TREADY_int_regslice,
        data_out => output_stream_TDATA,
        vld_out => regslice_both_output_stream_V_data_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_data_V_U_apdone_blk);

    regslice_both_output_stream_V_keep_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TKEEP_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => regslice_both_output_stream_V_keep_V_U_ack_in_dummy,
        data_out => output_stream_TKEEP,
        vld_out => regslice_both_output_stream_V_keep_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_keep_V_U_apdone_blk);

    regslice_both_output_stream_V_strb_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TSTRB_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => regslice_both_output_stream_V_strb_V_U_ack_in_dummy,
        data_out => output_stream_TSTRB,
        vld_out => regslice_both_output_stream_V_strb_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_strb_V_U_apdone_blk);

    regslice_both_output_stream_V_user_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TUSER_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => regslice_both_output_stream_V_user_V_U_ack_in_dummy,
        data_out => output_stream_TUSER,
        vld_out => regslice_both_output_stream_V_user_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_user_V_U_apdone_blk);

    regslice_both_output_stream_V_last_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TLAST_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => regslice_both_output_stream_V_last_V_U_ack_in_dummy,
        data_out => output_stream_TLAST,
        vld_out => regslice_both_output_stream_V_last_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_last_V_U_apdone_blk);

    regslice_both_output_stream_V_id_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TID_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => regslice_both_output_stream_V_id_V_U_ack_in_dummy,
        data_out => output_stream_TID,
        vld_out => regslice_both_output_stream_V_id_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_id_V_U_apdone_blk);

    regslice_both_output_stream_V_dest_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => output_stream_TDEST_int_regslice,
        vld_in => output_stream_TVALID_int_regslice,
        ack_in => regslice_both_output_stream_V_dest_V_U_ack_in_dummy,
        data_out => output_stream_TDEST,
        vld_out => regslice_both_output_stream_V_dest_V_U_vld_out,
        ack_out => output_stream_TREADY,
        apdone_blk => regslice_both_output_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_ready = ap_const_logic_1)) then 
                    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                icmp_ln184_reg_182 <= icmp_ln184_fu_146_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out_ap_vld = ap_const_logic_1))) then
                out_count_loc_fu_60 <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_count_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out_ap_vld = ap_const_logic_1))) then
                out_data_6_loc_fu_68 <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_data_6_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out_ap_vld = ap_const_logic_1))) then
                out_keep_6_loc_fu_64 <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_out_keep_6_out;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_block_state1, ap_block_state4, ap_block_state4_io, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done, ap_CS_fsm_state3, ap_block_state5, ap_block_state5_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done)
    begin
        if ((grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4, ap_block_state4_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5, ap_block_state5_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(icmp_ln184_fu_146_p2, output_stream_TREADY_int_regslice)
    begin
                ap_block_state4 <= (((icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (output_stream_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (output_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state4_io_assign_proc : process(icmp_ln184_fu_146_p2, output_stream_TREADY_int_regslice)
    begin
                ap_block_state4_io <= (((icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (output_stream_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (output_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(icmp_ln184_reg_182, regslice_both_output_stream_V_data_V_U_apdone_blk, output_stream_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((regslice_both_output_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln184_reg_182 = ap_const_lv1_0) and (output_stream_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln184_reg_182 = ap_const_lv1_1) and (output_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state5_io_assign_proc : process(icmp_ln184_reg_182, output_stream_TREADY_int_regslice)
    begin
                ap_block_state5_io <= (((icmp_ln184_reg_182 = ap_const_lv1_0) and (output_stream_TREADY_int_regslice = ap_const_logic_0)) or ((icmp_ln184_reg_182 = ap_const_lv1_1) and (output_stream_TREADY_int_regslice = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, ap_block_state5, ap_block_state5_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, ap_block_state5, ap_block_state5_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_ap_start_reg;
    grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TREADY <= (output_stream_TREADY_int_regslice and ap_CS_fsm_state3);
    icmp_ln184_fu_146_p2 <= "1" when (signed(out_count_loc_fu_60) > signed(ap_const_lv32_0)) else "0";

    long_matches_read_assign_proc : process(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            long_matches_read <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_long_matches_read;
        else 
            long_matches_read <= ap_const_logic_0;
        end if; 
    end process;


    output_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_CS_fsm_state5, icmp_ln184_reg_182, output_stream_TREADY_int_regslice)
    begin
        if ((((icmp_ln184_reg_182 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln184_reg_182 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TDATA_blk_n <= output_stream_TREADY_int_regslice;
        else 
            output_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_stream_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, ap_CS_fsm_state3, out_data_6_loc_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_stream_TDATA_int_regslice <= out_data_6_loc_fu_68;
        elsif (((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_stream_TDATA_int_regslice <= ap_const_lv512_lc_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TDATA_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDATA;
        else 
            output_stream_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_stream_TDEST_int_regslice_assign_proc : process(p_read, ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST, ap_CS_fsm_state3)
    begin
        if ((((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TDEST_int_regslice <= p_read;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TDEST_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TDEST;
        else 
            output_stream_TDEST_int_regslice <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_stream_TID_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID, ap_CS_fsm_state3)
    begin
        if ((((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TID_int_regslice <= "X";
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TID_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TID;
        else 
            output_stream_TID_int_regslice <= "X";
        end if; 
    end process;


    output_stream_TKEEP_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP, ap_CS_fsm_state3, out_keep_6_loc_fu_64)
    begin
        if (((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_stream_TKEEP_int_regslice <= out_keep_6_loc_fu_64;
        elsif (((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_stream_TKEEP_int_regslice <= ap_const_lv64_0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TKEEP_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TKEEP;
        else 
            output_stream_TKEEP_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_stream_TLAST_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST, ap_CS_fsm_state3)
    begin
        if ((((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TLAST_int_regslice <= ap_const_lv1_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TLAST_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TLAST;
        else 
            output_stream_TLAST_int_regslice <= "X";
        end if; 
    end process;


    output_stream_TSTRB_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB, ap_CS_fsm_state3)
    begin
        if ((((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TSTRB_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TSTRB;
        else 
            output_stream_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_stream_TUSER_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER, ap_CS_fsm_state3)
    begin
        if ((((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_boolean_0 = ap_block_state4) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TUSER_int_regslice <= "X";
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID = ap_const_logic_1))) then 
            output_stream_TUSER_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TUSER;
        else 
            output_stream_TUSER_int_regslice <= "X";
        end if; 
    end process;

    output_stream_TVALID <= regslice_both_output_stream_V_data_V_U_vld_out;

    output_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state4, icmp_ln184_fu_146_p2, ap_block_state4, ap_block_state4_io, grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID, ap_CS_fsm_state3)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4))) and (icmp_ln184_fu_146_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or (not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4))) and (icmp_ln184_fu_146_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_stream_TVALID_int_regslice <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            output_stream_TVALID_int_regslice <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_output_stream_TVALID;
        else 
            output_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    short_matches_read_assign_proc : process(grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            short_matches_read <= grp_merge_matches_Pipeline_VITIS_LOOP_146_1_fu_109_short_matches_read;
        else 
            short_matches_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
