// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        short_matches_dout,
        short_matches_num_data_valid,
        short_matches_fifo_cap,
        short_matches_empty_n,
        short_matches_read,
        long_matches_dout,
        long_matches_num_data_valid,
        long_matches_fifo_cap,
        long_matches_empty_n,
        long_matches_read,
        p_read,
        output_stream_TDATA,
        output_stream_TVALID,
        output_stream_TREADY,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        out_data_6_out,
        out_data_6_out_ap_vld,
        out_keep_6_out,
        out_keep_6_out_ap_vld,
        out_count_out,
        out_count_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_pp0_stage0 = 7'd2;
parameter    ap_ST_fsm_pp0_stage1 = 7'd4;
parameter    ap_ST_fsm_state7 = 7'd8;
parameter    ap_ST_fsm_state8 = 7'd16;
parameter    ap_ST_fsm_state9 = 7'd32;
parameter    ap_ST_fsm_state10 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [32:0] short_matches_dout;
input  [6:0] short_matches_num_data_valid;
input  [6:0] short_matches_fifo_cap;
input   short_matches_empty_n;
output   short_matches_read;
input  [32:0] long_matches_dout;
input  [6:0] long_matches_num_data_valid;
input  [6:0] long_matches_fifo_cap;
input   long_matches_empty_n;
output   long_matches_read;
input  [15:0] p_read;
output  [511:0] output_stream_TDATA;
output   output_stream_TVALID;
input   output_stream_TREADY;
output  [63:0] output_stream_TKEEP;
output  [63:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [15:0] output_stream_TDEST;
output  [511:0] out_data_6_out;
output   out_data_6_out_ap_vld;
output  [63:0] out_keep_6_out;
output   out_keep_6_out_ap_vld;
output  [31:0] out_count_out;
output   out_count_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg short_matches_read;
reg long_matches_read;
reg output_stream_TVALID;
reg out_data_6_out_ap_vld;
reg out_keep_6_out_ap_vld;
reg out_count_out_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    short_matches_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] and_ln146_fu_400_p2;
reg   [0:0] ap_phi_mux_done_short_phi_fu_200_p4;
wire   [0:0] tmp_i_nbreadreq_fu_118_p3;
reg    long_matches_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] and_ln146_reg_668;
reg   [0:0] done_long_reg_208;
reg   [0:0] tmp_4_i_reg_685;
reg    output_stream_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] and_ln146_reg_668_pp0_iter1_reg;
reg   [0:0] icmp_ln172_reg_752;
reg   [0:0] done_short_reg_196;
reg    ap_predicate_op28_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op98_write_state6;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] done_short_1_reg_220;
reg   [511:0] out_data_7_reg_300;
reg   [63:0] out_keep_7_reg_318;
reg   [0:0] tmp_i_reg_672;
wire   [31:0] hit_id_fu_406_p1;
reg   [31:0] hit_id_reg_676;
reg   [0:0] hit_last_reg_681;
wire   [0:0] tmp_4_i_nbreadreq_fu_132_p3;
reg   [31:0] out_count_6_reg_689;
reg    ap_predicate_op58_read_state3;
reg    ap_block_state3_pp0_stage1_iter0;
reg    ap_block_pp0_stage1_11001;
reg   [63:0] out_keep_2_reg_697;
reg   [511:0] out_data_2_reg_705;
wire   [511:0] out_data_3_fu_470_p2;
wire   [63:0] out_keep_3_fu_506_p2;
wire   [31:0] out_count_7_fu_512_p2;
wire   [31:0] hit_id_1_fu_518_p1;
reg   [31:0] hit_id_1_reg_728;
reg   [0:0] hit_last_1_reg_733;
wire   [511:0] out_data_5_fu_573_p2;
wire   [63:0] out_keep_5_fu_609_p2;
wire   [31:0] out_count_8_fu_615_p2;
wire   [0:0] icmp_ln172_fu_621_p2;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_done_long_phi_fu_212_p4;
reg   [0:0] ap_phi_mux_done_long_1_phi_fu_285_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_done_short_1_reg_220;
wire   [511:0] ap_phi_reg_pp0_iter0_out_data_1_reg_239;
reg   [511:0] ap_phi_reg_pp0_iter1_out_data_1_reg_239;
wire   [63:0] ap_phi_reg_pp0_iter0_out_keep_1_reg_253;
reg   [63:0] ap_phi_reg_pp0_iter1_out_keep_1_reg_253;
wire   [31:0] ap_phi_reg_pp0_iter0_out_count_2_reg_267;
reg   [31:0] ap_phi_reg_pp0_iter1_out_count_2_reg_267;
wire   [0:0] ap_phi_reg_pp0_iter1_done_long_1_reg_281;
wire   [511:0] ap_phi_reg_pp0_iter0_out_data_7_reg_300;
reg   [511:0] ap_phi_reg_pp0_iter1_out_data_7_reg_300;
wire   [63:0] ap_phi_reg_pp0_iter0_out_keep_7_reg_318;
reg   [63:0] ap_phi_reg_pp0_iter1_out_keep_7_reg_318;
wire   [31:0] ap_phi_reg_pp0_iter0_out_count_4_reg_336;
reg   [31:0] ap_phi_reg_pp0_iter1_out_count_4_reg_336;
reg   [511:0] ap_phi_mux_out_data_4_phi_fu_355_p4;
wire   [511:0] ap_phi_reg_pp0_iter1_out_data_4_reg_352;
reg   [63:0] ap_phi_mux_out_keep_4_phi_fu_366_p4;
wire   [63:0] ap_phi_reg_pp0_iter1_out_keep_4_reg_363;
reg   [31:0] ap_phi_mux_out_count_5_phi_fu_377_p4;
wire   [31:0] ap_phi_reg_pp0_iter1_out_count_5_reg_374;
reg   [31:0] out_count_fu_100;
reg   [31:0] ap_sig_allocacmp_out_count_6;
reg   [63:0] out_keep_fu_104;
reg   [63:0] ap_sig_allocacmp_out_keep_2;
reg   [511:0] out_data_fu_108;
reg   [511:0] ap_sig_allocacmp_out_data_2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state7;
wire   [3:0] trunc_ln154_fu_427_p1;
wire   [8:0] tmp_fu_431_p3;
wire   [511:0] zext_ln154_fu_439_p1;
wire   [511:0] shl_ln154_fu_443_p2;
wire   [511:0] xor_ln154_fu_449_p2;
wire   [511:0] zext_ln154_1_fu_461_p1;
wire   [511:0] and_ln154_fu_455_p2;
wire   [511:0] shl_ln154_1_fu_464_p2;
wire   [5:0] tmp_1_fu_476_p3;
wire   [63:0] zext_ln155_fu_484_p1;
wire   [63:0] shl_ln155_fu_488_p2;
wire   [63:0] xor_ln155_fu_494_p2;
wire   [63:0] and_ln155_fu_500_p2;
wire   [3:0] trunc_ln166_fu_530_p1;
wire   [8:0] tmp_3_fu_534_p3;
wire   [511:0] zext_ln166_fu_542_p1;
wire   [511:0] shl_ln166_fu_546_p2;
wire   [511:0] xor_ln166_fu_552_p2;
wire   [511:0] zext_ln166_1_fu_564_p1;
wire   [511:0] and_ln166_fu_558_p2;
wire   [511:0] shl_ln166_1_fu_567_p2;
wire   [5:0] tmp_4_fu_579_p3;
wire   [63:0] zext_ln167_fu_587_p1;
wire   [63:0] shl_ln167_fu_591_p2;
wire   [63:0] xor_ln167_fu_597_p2;
wire   [63:0] and_ln167_fu_603_p2;
wire    ap_CS_fsm_state10;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 out_count_fu_100 = 32'd0;
#0 out_keep_fu_104 = 64'd0;
#0 out_data_fu_108 = 512'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd1) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_i_reg_672 == 1'd0) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (done_short_reg_196 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_out_count_2_reg_267 <= ap_sig_allocacmp_out_count_6;
    end else if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd0) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_out_count_2_reg_267 <= out_count_7_fu_512_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_out_count_2_reg_267 <= ap_phi_reg_pp0_iter0_out_count_2_reg_267;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (hit_last_1_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_4_i_reg_685 == 1'd0) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((done_long_reg_208 == 1'd1) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter1_out_count_4_reg_336 <= ap_phi_reg_pp0_iter1_out_count_2_reg_267;
    end else if (((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (hit_last_1_reg_733 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_out_count_4_reg_336 <= out_count_8_fu_615_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_out_count_4_reg_336 <= ap_phi_reg_pp0_iter0_out_count_4_reg_336;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd1) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_i_reg_672 == 1'd0) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (done_short_reg_196 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_out_data_1_reg_239 <= ap_sig_allocacmp_out_data_2;
    end else if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd0) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_out_data_1_reg_239 <= out_data_3_fu_470_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_out_data_1_reg_239 <= ap_phi_reg_pp0_iter0_out_data_1_reg_239;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (hit_last_1_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_4_i_reg_685 == 1'd0) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((done_long_reg_208 == 1'd1) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter1_out_data_7_reg_300 <= ap_phi_reg_pp0_iter1_out_data_1_reg_239;
    end else if (((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (hit_last_1_reg_733 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_out_data_7_reg_300 <= out_data_5_fu_573_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_out_data_7_reg_300 <= ap_phi_reg_pp0_iter0_out_data_7_reg_300;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd1) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_i_reg_672 == 1'd0) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (done_short_reg_196 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_out_keep_1_reg_253 <= ap_sig_allocacmp_out_keep_2;
    end else if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd0) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_out_keep_1_reg_253 <= out_keep_3_fu_506_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_out_keep_1_reg_253 <= ap_phi_reg_pp0_iter0_out_keep_1_reg_253;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (hit_last_1_reg_733 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_4_i_reg_685 == 1'd0) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((done_long_reg_208 == 1'd1) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_phi_reg_pp0_iter1_out_keep_7_reg_318 <= ap_phi_reg_pp0_iter1_out_keep_1_reg_253;
    end else if (((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (hit_last_1_reg_733 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_out_keep_7_reg_318 <= out_keep_5_fu_609_p2;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_out_keep_7_reg_318 <= ap_phi_reg_pp0_iter0_out_keep_7_reg_318;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        done_long_reg_208 <= ap_phi_mux_done_long_1_phi_fu_285_p8;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        done_long_reg_208 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd1) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (done_short_reg_196 == 1'd1)))) begin
        done_short_1_reg_220 <= 1'd1;
    end else if ((((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_i_reg_672 == 1'd0) & (done_short_reg_196 == 1'd0)) | ((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (hit_last_reg_681 == 1'd0) & (tmp_i_reg_672 == 1'd1) & (done_short_reg_196 == 1'd0)))) begin
        done_short_1_reg_220 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        done_short_1_reg_220 <= ap_phi_reg_pp0_iter0_done_short_1_reg_220;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        done_short_reg_196 <= done_short_1_reg_220;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        done_short_reg_196 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_count_fu_100 <= 32'd0;
    end else if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_count_fu_100 <= ap_phi_mux_out_count_5_phi_fu_377_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_data_fu_108 <= 512'd0;
    end else if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_data_fu_108 <= ap_phi_mux_out_data_4_phi_fu_355_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_keep_fu_104 <= 64'd0;
    end else if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_keep_fu_104 <= ap_phi_mux_out_keep_4_phi_fu_366_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln146_reg_668 <= and_ln146_fu_400_p2;
        and_ln146_reg_668_pp0_iter1_reg <= and_ln146_reg_668;
        hit_id_reg_676 <= hit_id_fu_406_p1;
        hit_last_reg_681 <= short_matches_dout[32'd32];
        tmp_4_i_reg_685 <= tmp_4_i_nbreadreq_fu_132_p3;
        tmp_i_reg_672 <= tmp_i_nbreadreq_fu_118_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        hit_id_1_reg_728 <= hit_id_1_fu_518_p1;
        hit_last_1_reg_733 <= long_matches_dout[32'd32];
        icmp_ln172_reg_752 <= icmp_ln172_fu_621_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_count_6_reg_689 <= ap_sig_allocacmp_out_count_6;
        out_data_2_reg_705 <= ap_sig_allocacmp_out_data_2;
        out_keep_2_reg_697 <= ap_sig_allocacmp_out_keep_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_data_7_reg_300 <= ap_phi_reg_pp0_iter1_out_data_7_reg_300;
        out_keep_7_reg_318 <= ap_phi_reg_pp0_iter1_out_keep_7_reg_318;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'd1 == and_ln146_reg_668)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (hit_last_1_reg_733 == 1'd1)) | ((done_long_reg_208 == 1'd1) & (1'd0 == and_ln146_reg_668)))) begin
        ap_phi_mux_done_long_1_phi_fu_285_p8 = 1'd1;
    end else if ((((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (hit_last_1_reg_733 == 1'd0)) | ((tmp_4_i_reg_685 == 1'd0) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668)))) begin
        ap_phi_mux_done_long_1_phi_fu_285_p8 = 1'd0;
    end else begin
        ap_phi_mux_done_long_1_phi_fu_285_p8 = ap_phi_reg_pp0_iter1_done_long_1_reg_281;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_done_long_phi_fu_212_p4 = ap_phi_mux_done_long_1_phi_fu_285_p8;
    end else begin
        ap_phi_mux_done_long_phi_fu_212_p4 = done_long_reg_208;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_done_short_phi_fu_200_p4 = done_short_1_reg_220;
    end else begin
        ap_phi_mux_done_short_phi_fu_200_p4 = done_short_reg_196;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln146_reg_668_pp0_iter1_reg)) begin
        if ((icmp_ln172_fu_621_p2 == 1'd0)) begin
            ap_phi_mux_out_count_5_phi_fu_377_p4 = ap_phi_reg_pp0_iter1_out_count_4_reg_336;
        end else if ((icmp_ln172_fu_621_p2 == 1'd1)) begin
            ap_phi_mux_out_count_5_phi_fu_377_p4 = 32'd0;
        end else begin
            ap_phi_mux_out_count_5_phi_fu_377_p4 = ap_phi_reg_pp0_iter1_out_count_5_reg_374;
        end
    end else begin
        ap_phi_mux_out_count_5_phi_fu_377_p4 = ap_phi_reg_pp0_iter1_out_count_5_reg_374;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln146_reg_668_pp0_iter1_reg)) begin
        if ((icmp_ln172_fu_621_p2 == 1'd0)) begin
            ap_phi_mux_out_data_4_phi_fu_355_p4 = ap_phi_reg_pp0_iter1_out_data_7_reg_300;
        end else if ((icmp_ln172_fu_621_p2 == 1'd1)) begin
            ap_phi_mux_out_data_4_phi_fu_355_p4 = 512'd0;
        end else begin
            ap_phi_mux_out_data_4_phi_fu_355_p4 = ap_phi_reg_pp0_iter1_out_data_4_reg_352;
        end
    end else begin
        ap_phi_mux_out_data_4_phi_fu_355_p4 = ap_phi_reg_pp0_iter1_out_data_4_reg_352;
    end
end

always @ (*) begin
    if ((1'd0 == and_ln146_reg_668_pp0_iter1_reg)) begin
        if ((icmp_ln172_fu_621_p2 == 1'd0)) begin
            ap_phi_mux_out_keep_4_phi_fu_366_p4 = ap_phi_reg_pp0_iter1_out_keep_7_reg_318;
        end else if ((icmp_ln172_fu_621_p2 == 1'd1)) begin
            ap_phi_mux_out_keep_4_phi_fu_366_p4 = 64'd0;
        end else begin
            ap_phi_mux_out_keep_4_phi_fu_366_p4 = ap_phi_reg_pp0_iter1_out_keep_4_reg_363;
        end
    end else begin
        ap_phi_mux_out_keep_4_phi_fu_366_p4 = ap_phi_reg_pp0_iter1_out_keep_4_reg_363;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_out_count_6 = ap_phi_mux_out_count_5_phi_fu_377_p4;
    end else begin
        ap_sig_allocacmp_out_count_6 = out_count_fu_100;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_out_data_2 = ap_phi_mux_out_data_4_phi_fu_355_p4;
    end else begin
        ap_sig_allocacmp_out_data_2 = out_data_fu_108;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_sig_allocacmp_out_keep_2 = ap_phi_mux_out_keep_4_phi_fu_366_p4;
    end else begin
        ap_sig_allocacmp_out_keep_2 = out_keep_fu_104;
    end
end

always @ (*) begin
    if (((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        long_matches_blk_n = long_matches_empty_n;
    end else begin
        long_matches_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_predicate_op58_read_state3 == 1'b1))) begin
        long_matches_read = 1'b1;
    end else begin
        long_matches_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_count_out_ap_vld = 1'b1;
    end else begin
        out_count_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_data_6_out_ap_vld = 1'b1;
    end else begin
        out_data_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_keep_6_out_ap_vld = 1'b1;
    end else begin
        out_keep_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln172_reg_752 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_stream_TDATA_blk_n = output_stream_TREADY;
    end else begin
        output_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op98_write_state6 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output_stream_TVALID = 1'b1;
    end else begin
        output_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_nbreadreq_fu_118_p3 == 1'd1) & (ap_phi_mux_done_short_phi_fu_200_p4 == 1'd0) & (1'd0 == and_ln146_fu_400_p2) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        short_matches_blk_n = short_matches_empty_n;
    end else begin
        short_matches_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op28_read_state2 == 1'b1))) begin
        short_matches_read = 1'b1;
    end else begin
        short_matches_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'd1 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'd1 == and_ln146_reg_668) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln146_fu_400_p2 = (ap_phi_mux_done_short_phi_fu_200_p4 & ap_phi_mux_done_long_phi_fu_212_p4);

assign and_ln154_fu_455_p2 = (xor_ln154_fu_449_p2 & ap_sig_allocacmp_out_data_2);

assign and_ln155_fu_500_p2 = (xor_ln155_fu_494_p2 & ap_sig_allocacmp_out_keep_2);

assign and_ln166_fu_558_p2 = (xor_ln166_fu_552_p2 & ap_phi_reg_pp0_iter1_out_data_1_reg_239);

assign and_ln167_fu_603_p2 = (xor_ln167_fu_597_p2 & ap_phi_reg_pp0_iter1_out_keep_1_reg_253);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)) | ((1'b1 == ap_block_state6_pp0_stage0_iter2) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter2))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter2))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage1_iter0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((short_matches_empty_n == 1'b0) & (ap_predicate_op28_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage1_iter0 = ((long_matches_empty_n == 1'b0) & (ap_predicate_op58_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state6_io = ((output_stream_TREADY == 1'b0) & (ap_predicate_op98_write_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = ((output_stream_TREADY == 1'b0) & (ap_predicate_op98_write_state6 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_done_short_1_reg_220 = 'bx;

assign ap_phi_reg_pp0_iter0_out_count_2_reg_267 = 'bx;

assign ap_phi_reg_pp0_iter0_out_count_4_reg_336 = 'bx;

assign ap_phi_reg_pp0_iter0_out_data_1_reg_239 = 'bx;

assign ap_phi_reg_pp0_iter0_out_data_7_reg_300 = 'bx;

assign ap_phi_reg_pp0_iter0_out_keep_1_reg_253 = 'bx;

assign ap_phi_reg_pp0_iter0_out_keep_7_reg_318 = 'bx;

assign ap_phi_reg_pp0_iter1_done_long_1_reg_281 = 'bx;

assign ap_phi_reg_pp0_iter1_out_count_5_reg_374 = 'bx;

assign ap_phi_reg_pp0_iter1_out_data_4_reg_352 = 'bx;

assign ap_phi_reg_pp0_iter1_out_keep_4_reg_363 = 'bx;

always @ (*) begin
    ap_predicate_op28_read_state2 = ((tmp_i_nbreadreq_fu_118_p3 == 1'd1) & (ap_phi_mux_done_short_phi_fu_200_p4 == 1'd0) & (1'd0 == and_ln146_fu_400_p2));
end

always @ (*) begin
    ap_predicate_op58_read_state3 = ((tmp_4_i_reg_685 == 1'd1) & (done_long_reg_208 == 1'd0) & (1'd0 == and_ln146_reg_668));
end

always @ (*) begin
    ap_predicate_op98_write_state6 = ((1'd0 == and_ln146_reg_668_pp0_iter1_reg) & (icmp_ln172_reg_752 == 1'd1));
end

assign hit_id_1_fu_518_p1 = long_matches_dout[31:0];

assign hit_id_fu_406_p1 = short_matches_dout[31:0];

assign icmp_ln172_fu_621_p2 = ((ap_phi_reg_pp0_iter1_out_count_4_reg_336 == 32'd16) ? 1'b1 : 1'b0);

assign out_count_7_fu_512_p2 = (ap_sig_allocacmp_out_count_6 + 32'd1);

assign out_count_8_fu_615_p2 = (ap_phi_reg_pp0_iter1_out_count_2_reg_267 + 32'd1);

assign out_count_out = out_count_6_reg_689;

assign out_data_3_fu_470_p2 = (shl_ln154_1_fu_464_p2 | and_ln154_fu_455_p2);

assign out_data_5_fu_573_p2 = (shl_ln166_1_fu_567_p2 | and_ln166_fu_558_p2);

assign out_data_6_out = out_data_2_reg_705;

assign out_keep_3_fu_506_p2 = (shl_ln155_fu_488_p2 | and_ln155_fu_500_p2);

assign out_keep_5_fu_609_p2 = (shl_ln167_fu_591_p2 | and_ln167_fu_603_p2);

assign out_keep_6_out = out_keep_2_reg_697;

assign output_stream_TDATA = out_data_7_reg_300;

assign output_stream_TDEST = p_read;

assign output_stream_TID = 'bx;

assign output_stream_TKEEP = out_keep_7_reg_318;

assign output_stream_TLAST = 1'd0;

assign output_stream_TSTRB = 'bx;

assign output_stream_TUSER = 'bx;

assign shl_ln154_1_fu_464_p2 = zext_ln154_1_fu_461_p1 << zext_ln154_fu_439_p1;

assign shl_ln154_fu_443_p2 = 512'd4294967295 << zext_ln154_fu_439_p1;

assign shl_ln155_fu_488_p2 = 64'd15 << zext_ln155_fu_484_p1;

assign shl_ln166_1_fu_567_p2 = zext_ln166_1_fu_564_p1 << zext_ln166_fu_542_p1;

assign shl_ln166_fu_546_p2 = 512'd4294967295 << zext_ln166_fu_542_p1;

assign shl_ln167_fu_591_p2 = 64'd15 << zext_ln167_fu_587_p1;

assign tmp_1_fu_476_p3 = {{trunc_ln154_fu_427_p1}, {2'd0}};

assign tmp_3_fu_534_p3 = {{trunc_ln166_fu_530_p1}, {5'd0}};

assign tmp_4_fu_579_p3 = {{trunc_ln166_fu_530_p1}, {2'd0}};

assign tmp_4_i_nbreadreq_fu_132_p3 = long_matches_empty_n;

assign tmp_fu_431_p3 = {{trunc_ln154_fu_427_p1}, {5'd0}};

assign tmp_i_nbreadreq_fu_118_p3 = short_matches_empty_n;

assign trunc_ln154_fu_427_p1 = ap_sig_allocacmp_out_count_6[3:0];

assign trunc_ln166_fu_530_p1 = ap_phi_reg_pp0_iter1_out_count_2_reg_267[3:0];

assign xor_ln154_fu_449_p2 = (shl_ln154_fu_443_p2 ^ 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095);

assign xor_ln155_fu_494_p2 = (shl_ln155_fu_488_p2 ^ 64'd18446744073709551615);

assign xor_ln166_fu_552_p2 = (shl_ln166_fu_546_p2 ^ 512'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084095);

assign xor_ln167_fu_597_p2 = (shl_ln167_fu_591_p2 ^ 64'd18446744073709551615);

assign zext_ln154_1_fu_461_p1 = hit_id_reg_676;

assign zext_ln154_fu_439_p1 = tmp_fu_431_p3;

assign zext_ln155_fu_484_p1 = tmp_1_fu_476_p3;

assign zext_ln166_1_fu_564_p1 = hit_id_1_reg_728;

assign zext_ln166_fu_542_p1 = tmp_3_fu_534_p3;

assign zext_ln167_fu_587_p1 = tmp_4_fu_579_p3;

endmodule //krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1
