-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_proj_split_input_split_Pipeline_VITIS_LOOP_39_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    short_bytes_din : OUT STD_LOGIC_VECTOR (8 downto 0);
    short_bytes_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    short_bytes_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    short_bytes_full_n : IN STD_LOGIC;
    short_bytes_write : OUT STD_LOGIC;
    long_bytes_din : OUT STD_LOGIC_VECTOR (8 downto 0);
    long_bytes_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    long_bytes_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    long_bytes_full_n : IN STD_LOGIC;
    long_bytes_write : OUT STD_LOGIC;
    add_i_i5 : IN STD_LOGIC_VECTOR (63 downto 0);
    empty : IN STD_LOGIC_VECTOR (63 downto 0);
    in_word_keep : IN STD_LOGIC_VECTOR (63 downto 0);
    in_word_data : IN STD_LOGIC_VECTOR (511 downto 0);
    byte_count_write_assign_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    byte_count_write_assign_out_ap_vld : OUT STD_LOGIC;
    p_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    p_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of krnl_proj_split_input_split_Pipeline_VITIS_LOOP_39_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln41_reg_280 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln39_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal short_bytes_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal long_bytes_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln41_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bt_data_fu_203_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal bt_data_reg_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_fu_64 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln39_fu_152_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal empty_31_fu_68 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal add_ln47_fu_207_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal byte_count_write_assign_fu_72 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal p_0_fu_228_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln39_fu_158_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln41_fu_162_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln41_fu_168_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln43_fu_182_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_186_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln43_fu_194_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal lshr_ln43_fu_198_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_227 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_proj_split_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component krnl_proj_split_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    b_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    b_fu_64 <= ap_const_lv7_0;
                elsif (((icmp_ln39_fu_146_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    b_fu_64 <= add_ln39_fu_152_p2;
                end if;
            end if; 
        end if;
    end process;

    byte_count_write_assign_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    byte_count_write_assign_fu_72 <= add_i_i5;
                elsif ((ap_const_boolean_1 = ap_condition_227)) then 
                    byte_count_write_assign_fu_72 <= add_ln47_fu_207_p2;
                end if;
            end if; 
        end if;
    end process;

    empty_31_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_31_fu_68 <= empty;
                elsif ((ap_const_boolean_1 = ap_condition_227)) then 
                    empty_31_fu_68 <= add_ln47_fu_207_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bt_data_reg_284 <= bt_data_fu_203_p1;
                icmp_ln41_reg_280 <= icmp_ln41_fu_173_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln39_fu_152_p2 <= std_logic_vector(unsigned(b_fu_64) + unsigned(ap_const_lv7_1));
    add_ln47_fu_207_p2 <= std_logic_vector(unsigned(empty_31_fu_68) + unsigned(ap_const_lv64_1));
    and_ln41_fu_168_p2 <= (shl_ln41_fu_162_p2 and in_word_keep);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(short_bytes_full_n, icmp_ln41_reg_280, long_bytes_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (((long_bytes_full_n = ap_const_logic_0) and (icmp_ln41_reg_280 = ap_const_lv1_0)) or ((icmp_ln41_reg_280 = ap_const_lv1_0) and (short_bytes_full_n = ap_const_logic_0)));
    end process;


    ap_condition_227_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln39_fu_146_p2, icmp_ln41_fu_173_p2)
    begin
                ap_condition_227 <= ((icmp_ln41_fu_173_p2 = ap_const_lv1_0) and (icmp_ln39_fu_146_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln39_fu_146_p2)
    begin
        if (((icmp_ln39_fu_146_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    bt_data_fu_203_p1 <= lshr_ln43_fu_198_p2(8 - 1 downto 0);
    byte_count_write_assign_out <= byte_count_write_assign_fu_72;

    byte_count_write_assign_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln39_fu_146_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln39_fu_146_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            byte_count_write_assign_out_ap_vld <= ap_const_logic_1;
        else 
            byte_count_write_assign_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln39_fu_146_p2 <= "1" when (b_fu_64 = ap_const_lv7_40) else "0";
    icmp_ln41_fu_173_p2 <= "1" when (and_ln41_fu_168_p2 = ap_const_lv64_0) else "0";

    long_bytes_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln41_reg_280, long_bytes_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln41_reg_280 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            long_bytes_blk_n <= long_bytes_full_n;
        else 
            long_bytes_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    long_bytes_din <= p_0_fu_228_p3;

    long_bytes_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln41_reg_280, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln41_reg_280 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            long_bytes_write <= ap_const_logic_1;
        else 
            long_bytes_write <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln43_fu_198_p2 <= std_logic_vector(shift_right(unsigned(in_word_data),to_integer(unsigned('0' & zext_ln43_fu_194_p1(31-1 downto 0)))));
    p_0_fu_228_p3 <= (ap_const_lv1_0 & bt_data_reg_284);
    p_out <= empty_31_fu_68;

    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln39_fu_146_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln39_fu_146_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln41_fu_162_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_1),to_integer(unsigned('0' & zext_ln39_fu_158_p1(31-1 downto 0)))));
    shl_ln_fu_186_p3 <= (trunc_ln43_fu_182_p1 & ap_const_lv3_0);

    short_bytes_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, short_bytes_full_n, icmp_ln41_reg_280, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln41_reg_280 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            short_bytes_blk_n <= short_bytes_full_n;
        else 
            short_bytes_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    short_bytes_din <= p_0_fu_228_p3;

    short_bytes_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln41_reg_280, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln41_reg_280 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            short_bytes_write <= ap_const_logic_1;
        else 
            short_bytes_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln43_fu_182_p1 <= b_fu_64(6 - 1 downto 0);
    zext_ln39_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_fu_64),64));
    zext_ln43_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_186_p3),512));
end behav;
