-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    short_matches_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    short_matches_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    short_matches_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    short_matches_empty_n : IN STD_LOGIC;
    short_matches_read : OUT STD_LOGIC;
    long_matches_dout : IN STD_LOGIC_VECTOR (32 downto 0);
    long_matches_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    long_matches_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    long_matches_empty_n : IN STD_LOGIC;
    long_matches_read : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    output_stream_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    output_stream_TVALID : OUT STD_LOGIC;
    output_stream_TREADY : IN STD_LOGIC;
    output_stream_TKEEP : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_stream_TSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    output_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_stream_TDEST : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_data_6_out : OUT STD_LOGIC_VECTOR (511 downto 0);
    out_data_6_out_ap_vld : OUT STD_LOGIC;
    out_keep_6_out : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_keep_6_out_ap_vld : OUT STD_LOGIC;
    out_count_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_count_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of krnl_proj_split_merge_matches_Pipeline_VITIS_LOOP_146_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv512_lc_3 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111111111111111111111111111111";
    constant ap_const_lv512_lc_4 : STD_LOGIC_VECTOR (511 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal short_matches_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal and_ln146_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_done_short_phi_fu_200_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_nbreadreq_fu_118_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal long_matches_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal and_ln146_reg_668 : STD_LOGIC_VECTOR (0 downto 0);
    signal done_long_reg_208 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_reg_685 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal and_ln146_reg_668_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln172_reg_752 : STD_LOGIC_VECTOR (0 downto 0);
    signal done_short_reg_196 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op28_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op98_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal done_short_1_reg_220 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_7_reg_300 : STD_LOGIC_VECTOR (511 downto 0);
    signal out_keep_7_reg_318 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i_reg_672 : STD_LOGIC_VECTOR (0 downto 0);
    signal hit_id_fu_406_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal hit_id_reg_676 : STD_LOGIC_VECTOR (31 downto 0);
    signal hit_last_reg_681 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_nbreadreq_fu_132_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_count_6_reg_689 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op58_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal out_keep_2_reg_697 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_data_2_reg_705 : STD_LOGIC_VECTOR (511 downto 0);
    signal out_data_3_fu_470_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal out_keep_3_fu_506_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_count_7_fu_512_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal hit_id_1_fu_518_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal hit_id_1_reg_728 : STD_LOGIC_VECTOR (31 downto 0);
    signal hit_last_1_reg_733 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_data_5_fu_573_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal out_keep_5_fu_609_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_count_8_fu_615_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln172_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_done_long_phi_fu_212_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_done_long_1_phi_fu_285_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_done_short_1_reg_220 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_out_data_1_reg_239 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter1_out_data_1_reg_239 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter0_out_keep_1_reg_253 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_out_keep_1_reg_253 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_out_count_2_reg_267 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_out_count_2_reg_267 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_done_long_1_reg_281 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_out_data_7_reg_300 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter1_out_data_7_reg_300 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter0_out_keep_7_reg_318 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_out_keep_7_reg_318 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter0_out_count_4_reg_336 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_out_count_4_reg_336 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_out_data_4_phi_fu_355_p4 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_reg_pp0_iter1_out_data_4_reg_352 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_phi_mux_out_keep_4_phi_fu_366_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_reg_pp0_iter1_out_keep_4_reg_363 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_out_count_5_phi_fu_377_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_out_count_5_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_count_fu_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_out_count_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_keep_fu_104 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_sig_allocacmp_out_keep_2 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_data_fu_108 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_sig_allocacmp_out_data_2 : STD_LOGIC_VECTOR (511 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal trunc_ln154_fu_427_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_431_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln154_fu_439_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln154_fu_443_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal xor_ln154_fu_449_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln154_1_fu_461_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal and_ln154_fu_455_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln154_1_fu_464_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_1_fu_476_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln155_fu_484_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln155_fu_488_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln155_fu_494_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln155_fu_500_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln166_fu_530_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_534_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln166_fu_542_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln166_fu_546_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal xor_ln166_fu_552_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln166_1_fu_564_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal and_ln166_fu_558_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln166_1_fu_567_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal tmp_4_fu_579_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln167_fu_587_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln167_fu_591_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln167_fu_597_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln167_fu_603_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_out_count_2_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_1) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (tmp_i_reg_672 = ap_const_lv1_0) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (done_short_reg_196 = ap_const_lv1_1)))) then 
                ap_phi_reg_pp0_iter1_out_count_2_reg_267 <= ap_sig_allocacmp_out_count_6;
            elsif (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_0) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_out_count_2_reg_267 <= out_count_7_fu_512_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_out_count_2_reg_267 <= ap_phi_reg_pp0_iter0_out_count_2_reg_267;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_out_count_4_reg_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (hit_last_1_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_4_i_reg_685 = ap_const_lv1_0) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((done_long_reg_208 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ap_phi_reg_pp0_iter1_out_count_4_reg_336 <= ap_phi_reg_pp0_iter1_out_count_2_reg_267;
            elsif (((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (hit_last_1_reg_733 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_out_count_4_reg_336 <= out_count_8_fu_615_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_out_count_4_reg_336 <= ap_phi_reg_pp0_iter0_out_count_4_reg_336;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_out_data_1_reg_239_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_1) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (tmp_i_reg_672 = ap_const_lv1_0) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (done_short_reg_196 = ap_const_lv1_1)))) then 
                ap_phi_reg_pp0_iter1_out_data_1_reg_239 <= ap_sig_allocacmp_out_data_2;
            elsif (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_0) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_out_data_1_reg_239 <= out_data_3_fu_470_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_out_data_1_reg_239 <= ap_phi_reg_pp0_iter0_out_data_1_reg_239;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_out_data_7_reg_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (hit_last_1_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_4_i_reg_685 = ap_const_lv1_0) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((done_long_reg_208 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ap_phi_reg_pp0_iter1_out_data_7_reg_300 <= ap_phi_reg_pp0_iter1_out_data_1_reg_239;
            elsif (((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (hit_last_1_reg_733 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_out_data_7_reg_300 <= out_data_5_fu_573_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_out_data_7_reg_300 <= ap_phi_reg_pp0_iter0_out_data_7_reg_300;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_out_keep_1_reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_1) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (tmp_i_reg_672 = ap_const_lv1_0) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (done_short_reg_196 = ap_const_lv1_1)))) then 
                ap_phi_reg_pp0_iter1_out_keep_1_reg_253 <= ap_sig_allocacmp_out_keep_2;
            elsif (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_0) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_out_keep_1_reg_253 <= out_keep_3_fu_506_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_out_keep_1_reg_253 <= ap_phi_reg_pp0_iter0_out_keep_1_reg_253;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_out_keep_7_reg_318_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (hit_last_1_reg_733 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((tmp_4_i_reg_685 = ap_const_lv1_0) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((done_long_reg_208 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
                ap_phi_reg_pp0_iter1_out_keep_7_reg_318 <= ap_phi_reg_pp0_iter1_out_keep_1_reg_253;
            elsif (((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (hit_last_1_reg_733 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_out_keep_7_reg_318 <= out_keep_5_fu_609_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_out_keep_7_reg_318 <= ap_phi_reg_pp0_iter0_out_keep_7_reg_318;
            end if; 
        end if;
    end process;

    done_long_reg_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                done_long_reg_208 <= ap_phi_mux_done_long_1_phi_fu_285_p8;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                done_long_reg_208 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    done_short_1_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_1) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (done_short_reg_196 = ap_const_lv1_1)))) then 
                done_short_1_reg_220 <= ap_const_lv1_1;
            elsif ((((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (tmp_i_reg_672 = ap_const_lv1_0) and (done_short_reg_196 = ap_const_lv1_0)) or ((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (hit_last_reg_681 = ap_const_lv1_0) and (tmp_i_reg_672 = ap_const_lv1_1) and (done_short_reg_196 = ap_const_lv1_0)))) then 
                done_short_1_reg_220 <= ap_const_lv1_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                done_short_1_reg_220 <= ap_phi_reg_pp0_iter0_done_short_1_reg_220;
            end if; 
        end if;
    end process;

    done_short_reg_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                done_short_reg_196 <= done_short_1_reg_220;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                done_short_reg_196 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    out_count_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_count_fu_100 <= ap_const_lv32_0;
            elsif (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                out_count_fu_100 <= ap_phi_mux_out_count_5_phi_fu_377_p4;
            end if; 
        end if;
    end process;

    out_data_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_data_fu_108 <= ap_const_lv512_lc_1;
            elsif (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                out_data_fu_108 <= ap_phi_mux_out_data_4_phi_fu_355_p4;
            end if; 
        end if;
    end process;

    out_keep_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_keep_fu_104 <= ap_const_lv64_0;
            elsif (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                out_keep_fu_104 <= ap_phi_mux_out_keep_4_phi_fu_366_p4;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln146_reg_668 <= and_ln146_fu_400_p2;
                and_ln146_reg_668_pp0_iter1_reg <= and_ln146_reg_668;
                hit_id_reg_676 <= hit_id_fu_406_p1;
                hit_last_reg_681 <= short_matches_dout(32 downto 32);
                tmp_4_i_reg_685 <= tmp_4_i_nbreadreq_fu_132_p3;
                tmp_i_reg_672 <= tmp_i_nbreadreq_fu_118_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                hit_id_1_reg_728 <= hit_id_1_fu_518_p1;
                hit_last_1_reg_733 <= long_matches_dout(32 downto 32);
                icmp_ln172_reg_752 <= icmp_ln172_fu_621_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                out_count_6_reg_689 <= ap_sig_allocacmp_out_count_6;
                out_data_2_reg_705 <= ap_sig_allocacmp_out_data_2;
                out_keep_2_reg_697 <= ap_sig_allocacmp_out_keep_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                out_data_7_reg_300 <= ap_phi_reg_pp0_iter1_out_data_7_reg_300;
                out_keep_7_reg_318 <= ap_phi_reg_pp0_iter1_out_keep_7_reg_318;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, and_ln146_reg_668, ap_enable_reg_pp0_iter2, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_const_lv1_1 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_lv1_1 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    and_ln146_fu_400_p2 <= (ap_phi_mux_done_short_phi_fu_200_p4 and ap_phi_mux_done_long_phi_fu_212_p4);
    and_ln154_fu_455_p2 <= (xor_ln154_fu_449_p2 and ap_sig_allocacmp_out_data_2);
    and_ln155_fu_500_p2 <= (xor_ln155_fu_494_p2 and ap_sig_allocacmp_out_keep_2);
    and_ln166_fu_558_p2 <= (xor_ln166_fu_552_p2 and ap_phi_reg_pp0_iter1_out_data_1_reg_239);
    and_ln167_fu_603_p2 <= (xor_ln167_fu_597_p2 and ap_phi_reg_pp0_iter1_out_keep_1_reg_253);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(6);
    ap_CS_fsm_state7 <= ap_CS_fsm(3);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)) or ((ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter2, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter2))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter0, ap_block_state6_pp0_stage0_iter2, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state6_io) or (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter2))));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state3_pp0_stage1_iter0)
    begin
                ap_block_pp0_stage1_11001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage1_iter0));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_block_state3_pp0_stage1_iter0)
    begin
                ap_block_pp0_stage1_subdone <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage1_iter0));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(short_matches_empty_n, ap_predicate_op28_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter0 <= ((short_matches_empty_n = ap_const_logic_0) and (ap_predicate_op28_read_state2 = ap_const_boolean_1));
    end process;


    ap_block_state3_pp0_stage1_iter0_assign_proc : process(long_matches_empty_n, ap_predicate_op58_read_state3)
    begin
                ap_block_state3_pp0_stage1_iter0 <= ((long_matches_empty_n = ap_const_logic_0) and (ap_predicate_op58_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state6_io_assign_proc : process(output_stream_TREADY, ap_predicate_op98_write_state6)
    begin
                ap_block_state6_io <= ((output_stream_TREADY = ap_const_logic_0) and (ap_predicate_op98_write_state6 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage0_iter2_assign_proc : process(output_stream_TREADY, ap_predicate_op98_write_state6)
    begin
                ap_block_state6_pp0_stage0_iter2 <= ((output_stream_TREADY = ap_const_logic_0) and (ap_predicate_op98_write_state6 = ap_const_boolean_1));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(and_ln146_reg_668)
    begin
        if ((ap_const_lv1_1 = and_ln146_reg_668)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_done_long_1_phi_fu_285_p8_assign_proc : process(and_ln146_reg_668, done_long_reg_208, tmp_4_i_reg_685, hit_last_1_reg_733, ap_phi_reg_pp0_iter1_done_long_1_reg_281)
    begin
        if ((((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (hit_last_1_reg_733 = ap_const_lv1_1)) or ((done_long_reg_208 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln146_reg_668)))) then 
            ap_phi_mux_done_long_1_phi_fu_285_p8 <= ap_const_lv1_1;
        elsif ((((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (hit_last_1_reg_733 = ap_const_lv1_0)) or ((tmp_4_i_reg_685 = ap_const_lv1_0) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668)))) then 
            ap_phi_mux_done_long_1_phi_fu_285_p8 <= ap_const_lv1_0;
        else 
            ap_phi_mux_done_long_1_phi_fu_285_p8 <= ap_phi_reg_pp0_iter1_done_long_1_reg_281;
        end if; 
    end process;


    ap_phi_mux_done_long_phi_fu_212_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, and_ln146_reg_668, done_long_reg_208, ap_enable_reg_pp0_iter1, ap_phi_mux_done_long_1_phi_fu_285_p8)
    begin
        if (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_done_long_phi_fu_212_p4 <= ap_phi_mux_done_long_1_phi_fu_285_p8;
        else 
            ap_phi_mux_done_long_phi_fu_212_p4 <= done_long_reg_208;
        end if; 
    end process;


    ap_phi_mux_done_short_phi_fu_200_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, and_ln146_reg_668, done_short_reg_196, done_short_1_reg_220, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_done_short_phi_fu_200_p4 <= done_short_1_reg_220;
        else 
            ap_phi_mux_done_short_phi_fu_200_p4 <= done_short_reg_196;
        end if; 
    end process;


    ap_phi_mux_out_count_5_phi_fu_377_p4_assign_proc : process(and_ln146_reg_668_pp0_iter1_reg, icmp_ln172_fu_621_p2, ap_phi_reg_pp0_iter1_out_count_4_reg_336, ap_phi_reg_pp0_iter1_out_count_5_reg_374)
    begin
        if ((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg)) then
            if ((icmp_ln172_fu_621_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_out_count_5_phi_fu_377_p4 <= ap_phi_reg_pp0_iter1_out_count_4_reg_336;
            elsif ((icmp_ln172_fu_621_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_out_count_5_phi_fu_377_p4 <= ap_const_lv32_0;
            else 
                ap_phi_mux_out_count_5_phi_fu_377_p4 <= ap_phi_reg_pp0_iter1_out_count_5_reg_374;
            end if;
        else 
            ap_phi_mux_out_count_5_phi_fu_377_p4 <= ap_phi_reg_pp0_iter1_out_count_5_reg_374;
        end if; 
    end process;


    ap_phi_mux_out_data_4_phi_fu_355_p4_assign_proc : process(and_ln146_reg_668_pp0_iter1_reg, icmp_ln172_fu_621_p2, ap_phi_reg_pp0_iter1_out_data_7_reg_300, ap_phi_reg_pp0_iter1_out_data_4_reg_352)
    begin
        if ((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg)) then
            if ((icmp_ln172_fu_621_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_out_data_4_phi_fu_355_p4 <= ap_phi_reg_pp0_iter1_out_data_7_reg_300;
            elsif ((icmp_ln172_fu_621_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_out_data_4_phi_fu_355_p4 <= ap_const_lv512_lc_1;
            else 
                ap_phi_mux_out_data_4_phi_fu_355_p4 <= ap_phi_reg_pp0_iter1_out_data_4_reg_352;
            end if;
        else 
            ap_phi_mux_out_data_4_phi_fu_355_p4 <= ap_phi_reg_pp0_iter1_out_data_4_reg_352;
        end if; 
    end process;


    ap_phi_mux_out_keep_4_phi_fu_366_p4_assign_proc : process(and_ln146_reg_668_pp0_iter1_reg, icmp_ln172_fu_621_p2, ap_phi_reg_pp0_iter1_out_keep_7_reg_318, ap_phi_reg_pp0_iter1_out_keep_4_reg_363)
    begin
        if ((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg)) then
            if ((icmp_ln172_fu_621_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_out_keep_4_phi_fu_366_p4 <= ap_phi_reg_pp0_iter1_out_keep_7_reg_318;
            elsif ((icmp_ln172_fu_621_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_out_keep_4_phi_fu_366_p4 <= ap_const_lv64_0;
            else 
                ap_phi_mux_out_keep_4_phi_fu_366_p4 <= ap_phi_reg_pp0_iter1_out_keep_4_reg_363;
            end if;
        else 
            ap_phi_mux_out_keep_4_phi_fu_366_p4 <= ap_phi_reg_pp0_iter1_out_keep_4_reg_363;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_done_short_1_reg_220 <= "X";
    ap_phi_reg_pp0_iter0_out_count_2_reg_267 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_out_count_4_reg_336 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_out_data_1_reg_239 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_out_data_7_reg_300 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_out_keep_1_reg_253 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_out_keep_7_reg_318 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_done_long_1_reg_281 <= "X";
    ap_phi_reg_pp0_iter1_out_count_5_reg_374 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_out_data_4_reg_352 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_out_keep_4_reg_363 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op28_read_state2_assign_proc : process(and_ln146_fu_400_p2, ap_phi_mux_done_short_phi_fu_200_p4, tmp_i_nbreadreq_fu_118_p3)
    begin
                ap_predicate_op28_read_state2 <= ((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_phi_mux_done_short_phi_fu_200_p4 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_fu_400_p2));
    end process;


    ap_predicate_op58_read_state3_assign_proc : process(and_ln146_reg_668, done_long_reg_208, tmp_4_i_reg_685)
    begin
                ap_predicate_op58_read_state3 <= ((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668));
    end process;


    ap_predicate_op98_write_state6_assign_proc : process(and_ln146_reg_668_pp0_iter1_reg, icmp_ln172_reg_752)
    begin
                ap_predicate_op98_write_state6 <= ((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (icmp_ln172_reg_752 = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_out_count_6_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, and_ln146_reg_668_pp0_iter1_reg, ap_enable_reg_pp0_iter1, ap_phi_mux_out_count_5_phi_fu_377_p4, out_count_fu_100)
    begin
        if (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_out_count_6 <= ap_phi_mux_out_count_5_phi_fu_377_p4;
        else 
            ap_sig_allocacmp_out_count_6 <= out_count_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_out_data_2_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, and_ln146_reg_668_pp0_iter1_reg, ap_enable_reg_pp0_iter1, ap_phi_mux_out_data_4_phi_fu_355_p4, out_data_fu_108)
    begin
        if (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_out_data_2 <= ap_phi_mux_out_data_4_phi_fu_355_p4;
        else 
            ap_sig_allocacmp_out_data_2 <= out_data_fu_108;
        end if; 
    end process;


    ap_sig_allocacmp_out_keep_2_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, and_ln146_reg_668_pp0_iter1_reg, ap_enable_reg_pp0_iter1, ap_phi_mux_out_keep_4_phi_fu_366_p4, out_keep_fu_104)
    begin
        if (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_sig_allocacmp_out_keep_2 <= ap_phi_mux_out_keep_4_phi_fu_366_p4;
        else 
            ap_sig_allocacmp_out_keep_2 <= out_keep_fu_104;
        end if; 
    end process;

    hit_id_1_fu_518_p1 <= long_matches_dout(32 - 1 downto 0);
    hit_id_fu_406_p1 <= short_matches_dout(32 - 1 downto 0);
    icmp_ln172_fu_621_p2 <= "1" when (ap_phi_reg_pp0_iter1_out_count_4_reg_336 = ap_const_lv32_10) else "0";

    long_matches_blk_n_assign_proc : process(long_matches_empty_n, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, and_ln146_reg_668, done_long_reg_208, tmp_4_i_reg_685)
    begin
        if (((tmp_4_i_reg_685 = ap_const_lv1_1) and (done_long_reg_208 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_reg_668) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            long_matches_blk_n <= long_matches_empty_n;
        else 
            long_matches_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    long_matches_read_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_predicate_op58_read_state3, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_predicate_op58_read_state3 = ap_const_boolean_1))) then 
            long_matches_read <= ap_const_logic_1;
        else 
            long_matches_read <= ap_const_logic_0;
        end if; 
    end process;

    out_count_7_fu_512_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_out_count_6) + unsigned(ap_const_lv32_1));
    out_count_8_fu_615_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter1_out_count_2_reg_267) + unsigned(ap_const_lv32_1));
    out_count_out <= out_count_6_reg_689;

    out_count_out_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_count_out_ap_vld <= ap_const_logic_1;
        else 
            out_count_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_data_3_fu_470_p2 <= (shl_ln154_1_fu_464_p2 or and_ln154_fu_455_p2);
    out_data_5_fu_573_p2 <= (shl_ln166_1_fu_567_p2 or and_ln166_fu_558_p2);
    out_data_6_out <= out_data_2_reg_705;

    out_data_6_out_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_data_6_out_ap_vld <= ap_const_logic_1;
        else 
            out_data_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    out_keep_3_fu_506_p2 <= (shl_ln155_fu_488_p2 or and_ln155_fu_500_p2);
    out_keep_5_fu_609_p2 <= (shl_ln167_fu_591_p2 or and_ln167_fu_603_p2);
    out_keep_6_out <= out_keep_2_reg_697;

    out_keep_6_out_ap_vld_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_keep_6_out_ap_vld <= ap_const_logic_1;
        else 
            out_keep_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    output_stream_TDATA <= out_data_7_reg_300;

    output_stream_TDATA_blk_n_assign_proc : process(output_stream_TREADY, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, and_ln146_reg_668_pp0_iter1_reg, icmp_ln172_reg_752)
    begin
        if (((ap_const_lv1_0 = and_ln146_reg_668_pp0_iter1_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln172_reg_752 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_stream_TDATA_blk_n <= output_stream_TREADY;
        else 
            output_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_stream_TDEST <= p_read;
    output_stream_TID <= "X";
    output_stream_TKEEP <= out_keep_7_reg_318;
    output_stream_TLAST <= ap_const_lv1_0;
    output_stream_TSTRB <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    output_stream_TUSER <= "X";

    output_stream_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_predicate_op98_write_state6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op98_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            output_stream_TVALID <= ap_const_logic_1;
        else 
            output_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln154_1_fu_464_p2 <= std_logic_vector(shift_left(unsigned(zext_ln154_1_fu_461_p1),to_integer(unsigned('0' & zext_ln154_fu_439_p1(31-1 downto 0)))));
    shl_ln154_fu_443_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv512_lc_3),to_integer(unsigned('0' & zext_ln154_fu_439_p1(31-1 downto 0)))));
    shl_ln155_fu_488_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_F),to_integer(unsigned('0' & zext_ln155_fu_484_p1(31-1 downto 0)))));
    shl_ln166_1_fu_567_p2 <= std_logic_vector(shift_left(unsigned(zext_ln166_1_fu_564_p1),to_integer(unsigned('0' & zext_ln166_fu_542_p1(31-1 downto 0)))));
    shl_ln166_fu_546_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv512_lc_3),to_integer(unsigned('0' & zext_ln166_fu_542_p1(31-1 downto 0)))));
    shl_ln167_fu_591_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv64_F),to_integer(unsigned('0' & zext_ln167_fu_587_p1(31-1 downto 0)))));

    short_matches_blk_n_assign_proc : process(short_matches_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, and_ln146_fu_400_p2, ap_phi_mux_done_short_phi_fu_200_p4, tmp_i_nbreadreq_fu_118_p3)
    begin
        if (((tmp_i_nbreadreq_fu_118_p3 = ap_const_lv1_1) and (ap_phi_mux_done_short_phi_fu_200_p4 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln146_fu_400_p2) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            short_matches_blk_n <= short_matches_empty_n;
        else 
            short_matches_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    short_matches_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op28_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op28_read_state2 = ap_const_boolean_1))) then 
            short_matches_read <= ap_const_logic_1;
        else 
            short_matches_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_476_p3 <= (trunc_ln154_fu_427_p1 & ap_const_lv2_0);
    tmp_3_fu_534_p3 <= (trunc_ln166_fu_530_p1 & ap_const_lv5_0);
    tmp_4_fu_579_p3 <= (trunc_ln166_fu_530_p1 & ap_const_lv2_0);
    tmp_4_i_nbreadreq_fu_132_p3 <= (0=>(long_matches_empty_n), others=>'-');
    tmp_fu_431_p3 <= (trunc_ln154_fu_427_p1 & ap_const_lv5_0);
    tmp_i_nbreadreq_fu_118_p3 <= (0=>(short_matches_empty_n), others=>'-');
    trunc_ln154_fu_427_p1 <= ap_sig_allocacmp_out_count_6(4 - 1 downto 0);
    trunc_ln166_fu_530_p1 <= ap_phi_reg_pp0_iter1_out_count_2_reg_267(4 - 1 downto 0);
    xor_ln154_fu_449_p2 <= (shl_ln154_fu_443_p2 xor ap_const_lv512_lc_4);
    xor_ln155_fu_494_p2 <= (shl_ln155_fu_488_p2 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    xor_ln166_fu_552_p2 <= (shl_ln166_fu_546_p2 xor ap_const_lv512_lc_4);
    xor_ln167_fu_597_p2 <= (shl_ln167_fu_591_p2 xor ap_const_lv64_FFFFFFFFFFFFFFFF);
    zext_ln154_1_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hit_id_reg_676),512));
    zext_ln154_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_431_p3),512));
    zext_ln155_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_476_p3),64));
    zext_ln166_1_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hit_id_1_reg_728),512));
    zext_ln166_fu_542_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_534_p3),512));
    zext_ln167_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_579_p3),64));
end behav;
