// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2023.2 (lin64) Build 4029153 Fri Oct 13 20:13:54 MDT 2023
// Date        : Sat Jan 17 14:52:28 2026
// Host        : cse-es62-02.cse.chalmers.se running 64-bit Rocky Linux release 9.6 (Blue Onyx)
// Command     : write_verilog -force -mode synth_stub
//               /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.v
// Design      : ulp
// Purpose     : Stub declaration of top-level module interface
// Device      : xcu55c-fsvh2892-2L-e
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
module ulp(BLP_M_AXI_DATA_C2H_00_araddr, 
  BLP_M_AXI_DATA_C2H_00_arburst, BLP_M_AXI_DATA_C2H_00_arid, 
  BLP_M_AXI_DATA_C2H_00_arlen, BLP_M_AXI_DATA_C2H_00_arready, 
  BLP_M_AXI_DATA_C2H_00_arvalid, BLP_M_AXI_DATA_C2H_00_awaddr, 
  BLP_M_AXI_DATA_C2H_00_awburst, BLP_M_AXI_DATA_C2H_00_awid, 
  BLP_M_AXI_DATA_C2H_00_awlen, BLP_M_AXI_DATA_C2H_00_awready, 
  BLP_M_AXI_DATA_C2H_00_awvalid, BLP_M_AXI_DATA_C2H_00_bid, 
  BLP_M_AXI_DATA_C2H_00_bready, BLP_M_AXI_DATA_C2H_00_bresp, 
  BLP_M_AXI_DATA_C2H_00_bvalid, BLP_M_AXI_DATA_C2H_00_rdata, BLP_M_AXI_DATA_C2H_00_rid, 
  BLP_M_AXI_DATA_C2H_00_rlast, BLP_M_AXI_DATA_C2H_00_rready, 
  BLP_M_AXI_DATA_C2H_00_rresp, BLP_M_AXI_DATA_C2H_00_rvalid, 
  BLP_M_AXI_DATA_C2H_00_wdata, BLP_M_AXI_DATA_C2H_00_wlast, 
  BLP_M_AXI_DATA_C2H_00_wready, BLP_M_AXI_DATA_C2H_00_wstrb, 
  BLP_M_AXI_DATA_C2H_00_wvalid, BLP_S_AXI_CTRL_MGMT_00_araddr, 
  BLP_S_AXI_CTRL_MGMT_00_arprot, BLP_S_AXI_CTRL_MGMT_00_arready, 
  BLP_S_AXI_CTRL_MGMT_00_arvalid, BLP_S_AXI_CTRL_MGMT_00_awaddr, 
  BLP_S_AXI_CTRL_MGMT_00_awprot, BLP_S_AXI_CTRL_MGMT_00_awready, 
  BLP_S_AXI_CTRL_MGMT_00_awvalid, BLP_S_AXI_CTRL_MGMT_00_bready, 
  BLP_S_AXI_CTRL_MGMT_00_bresp, BLP_S_AXI_CTRL_MGMT_00_bvalid, 
  BLP_S_AXI_CTRL_MGMT_00_rdata, BLP_S_AXI_CTRL_MGMT_00_rready, 
  BLP_S_AXI_CTRL_MGMT_00_rresp, BLP_S_AXI_CTRL_MGMT_00_rvalid, 
  BLP_S_AXI_CTRL_MGMT_00_wdata, BLP_S_AXI_CTRL_MGMT_00_wready, 
  BLP_S_AXI_CTRL_MGMT_00_wstrb, BLP_S_AXI_CTRL_MGMT_00_wvalid, 
  BLP_S_AXI_CTRL_MGMT_01_araddr, BLP_S_AXI_CTRL_MGMT_01_arprot, 
  BLP_S_AXI_CTRL_MGMT_01_arready, BLP_S_AXI_CTRL_MGMT_01_arvalid, 
  BLP_S_AXI_CTRL_MGMT_01_awaddr, BLP_S_AXI_CTRL_MGMT_01_awprot, 
  BLP_S_AXI_CTRL_MGMT_01_awready, BLP_S_AXI_CTRL_MGMT_01_awvalid, 
  BLP_S_AXI_CTRL_MGMT_01_bready, BLP_S_AXI_CTRL_MGMT_01_bresp, 
  BLP_S_AXI_CTRL_MGMT_01_bvalid, BLP_S_AXI_CTRL_MGMT_01_rdata, 
  BLP_S_AXI_CTRL_MGMT_01_rready, BLP_S_AXI_CTRL_MGMT_01_rresp, 
  BLP_S_AXI_CTRL_MGMT_01_rvalid, BLP_S_AXI_CTRL_MGMT_01_wdata, 
  BLP_S_AXI_CTRL_MGMT_01_wready, BLP_S_AXI_CTRL_MGMT_01_wstrb, 
  BLP_S_AXI_CTRL_MGMT_01_wvalid, BLP_S_AXI_CTRL_USER_00_araddr, 
  BLP_S_AXI_CTRL_USER_00_arprot, BLP_S_AXI_CTRL_USER_00_arready, 
  BLP_S_AXI_CTRL_USER_00_arvalid, BLP_S_AXI_CTRL_USER_00_awaddr, 
  BLP_S_AXI_CTRL_USER_00_awprot, BLP_S_AXI_CTRL_USER_00_awready, 
  BLP_S_AXI_CTRL_USER_00_awvalid, BLP_S_AXI_CTRL_USER_00_bready, 
  BLP_S_AXI_CTRL_USER_00_bresp, BLP_S_AXI_CTRL_USER_00_bvalid, 
  BLP_S_AXI_CTRL_USER_00_rdata, BLP_S_AXI_CTRL_USER_00_rready, 
  BLP_S_AXI_CTRL_USER_00_rresp, BLP_S_AXI_CTRL_USER_00_rvalid, 
  BLP_S_AXI_CTRL_USER_00_wdata, BLP_S_AXI_CTRL_USER_00_wready, 
  BLP_S_AXI_CTRL_USER_00_wstrb, BLP_S_AXI_CTRL_USER_00_wvalid, 
  BLP_S_AXI_CTRL_USER_01_araddr, BLP_S_AXI_CTRL_USER_01_arprot, 
  BLP_S_AXI_CTRL_USER_01_arready, BLP_S_AXI_CTRL_USER_01_arvalid, 
  BLP_S_AXI_CTRL_USER_01_awaddr, BLP_S_AXI_CTRL_USER_01_awprot, 
  BLP_S_AXI_CTRL_USER_01_awready, BLP_S_AXI_CTRL_USER_01_awvalid, 
  BLP_S_AXI_CTRL_USER_01_bready, BLP_S_AXI_CTRL_USER_01_bresp, 
  BLP_S_AXI_CTRL_USER_01_bvalid, BLP_S_AXI_CTRL_USER_01_rdata, 
  BLP_S_AXI_CTRL_USER_01_rready, BLP_S_AXI_CTRL_USER_01_rresp, 
  BLP_S_AXI_CTRL_USER_01_rvalid, BLP_S_AXI_CTRL_USER_01_wdata, 
  BLP_S_AXI_CTRL_USER_01_wready, BLP_S_AXI_CTRL_USER_01_wstrb, 
  BLP_S_AXI_CTRL_USER_01_wvalid, BLP_S_AXI_CTRL_USER_02_araddr, 
  BLP_S_AXI_CTRL_USER_02_arprot, BLP_S_AXI_CTRL_USER_02_arready, 
  BLP_S_AXI_CTRL_USER_02_arvalid, BLP_S_AXI_CTRL_USER_02_awaddr, 
  BLP_S_AXI_CTRL_USER_02_awprot, BLP_S_AXI_CTRL_USER_02_awready, 
  BLP_S_AXI_CTRL_USER_02_awvalid, BLP_S_AXI_CTRL_USER_02_bready, 
  BLP_S_AXI_CTRL_USER_02_bresp, BLP_S_AXI_CTRL_USER_02_bvalid, 
  BLP_S_AXI_CTRL_USER_02_rdata, BLP_S_AXI_CTRL_USER_02_rready, 
  BLP_S_AXI_CTRL_USER_02_rresp, BLP_S_AXI_CTRL_USER_02_rvalid, 
  BLP_S_AXI_CTRL_USER_02_wdata, BLP_S_AXI_CTRL_USER_02_wready, 
  BLP_S_AXI_CTRL_USER_02_wstrb, BLP_S_AXI_CTRL_USER_02_wvalid, 
  BLP_S_AXI_CTRL_USER_03_araddr, BLP_S_AXI_CTRL_USER_03_arprot, 
  BLP_S_AXI_CTRL_USER_03_arready, BLP_S_AXI_CTRL_USER_03_arvalid, 
  BLP_S_AXI_CTRL_USER_03_awaddr, BLP_S_AXI_CTRL_USER_03_awprot, 
  BLP_S_AXI_CTRL_USER_03_awready, BLP_S_AXI_CTRL_USER_03_awvalid, 
  BLP_S_AXI_CTRL_USER_03_bready, BLP_S_AXI_CTRL_USER_03_bresp, 
  BLP_S_AXI_CTRL_USER_03_bvalid, BLP_S_AXI_CTRL_USER_03_rdata, 
  BLP_S_AXI_CTRL_USER_03_rready, BLP_S_AXI_CTRL_USER_03_rresp, 
  BLP_S_AXI_CTRL_USER_03_rvalid, BLP_S_AXI_CTRL_USER_03_wdata, 
  BLP_S_AXI_CTRL_USER_03_wready, BLP_S_AXI_CTRL_USER_03_wstrb, 
  BLP_S_AXI_CTRL_USER_03_wvalid, BLP_S_AXI_DATA_H2C_00_araddr, 
  BLP_S_AXI_DATA_H2C_00_arid, BLP_S_AXI_DATA_H2C_00_arlen, 
  BLP_S_AXI_DATA_H2C_00_arready, BLP_S_AXI_DATA_H2C_00_arvalid, 
  BLP_S_AXI_DATA_H2C_00_awaddr, BLP_S_AXI_DATA_H2C_00_awid, 
  BLP_S_AXI_DATA_H2C_00_awlen, BLP_S_AXI_DATA_H2C_00_awready, 
  BLP_S_AXI_DATA_H2C_00_awvalid, BLP_S_AXI_DATA_H2C_00_bid, 
  BLP_S_AXI_DATA_H2C_00_bready, BLP_S_AXI_DATA_H2C_00_bresp, 
  BLP_S_AXI_DATA_H2C_00_bvalid, BLP_S_AXI_DATA_H2C_00_rdata, BLP_S_AXI_DATA_H2C_00_rid, 
  BLP_S_AXI_DATA_H2C_00_rlast, BLP_S_AXI_DATA_H2C_00_rready, 
  BLP_S_AXI_DATA_H2C_00_rresp, BLP_S_AXI_DATA_H2C_00_rvalid, 
  BLP_S_AXI_DATA_H2C_00_wdata, BLP_S_AXI_DATA_H2C_00_wlast, 
  BLP_S_AXI_DATA_H2C_00_wready, BLP_S_AXI_DATA_H2C_00_wstrb, 
  BLP_S_AXI_DATA_H2C_00_wvalid, blp_m_data_hbm_temp_00, blp_m_data_hbm_temp_01, 
  blp_m_data_memory_calib_complete_00, blp_m_irq_cu_00, blp_m_irq_hbm_cattrip_00, 
  blp_s_aclk_ctrl_00, blp_s_aclk_freerun_ref_00, blp_s_aclk_pcie_00, 
  blp_s_aresetn_ctrl_00, blp_s_aresetn_pcie_00, blp_s_data_satellite_ctrl_data_00, 
  io_clk_qsfp0_refclka_00_clk_n, io_clk_qsfp0_refclka_00_clk_p, 
  io_clk_qsfp1_refclka_00_clk_n, io_clk_qsfp1_refclka_00_clk_p, io_gt_qsfp0_00_grx_n, 
  io_gt_qsfp0_00_grx_p, io_gt_qsfp0_00_gtx_n, io_gt_qsfp0_00_gtx_p, io_gt_qsfp1_00_grx_n, 
  io_gt_qsfp1_00_grx_p, io_gt_qsfp1_00_gtx_n, io_gt_qsfp1_00_gtx_p)
/* synthesis syn_black_box black_box_pad_pin="BLP_M_AXI_DATA_C2H_00_araddr[38:0],BLP_M_AXI_DATA_C2H_00_arburst[1:0],BLP_M_AXI_DATA_C2H_00_arid[1:0],BLP_M_AXI_DATA_C2H_00_arlen[7:0],BLP_M_AXI_DATA_C2H_00_arready,BLP_M_AXI_DATA_C2H_00_arvalid,BLP_M_AXI_DATA_C2H_00_awaddr[38:0],BLP_M_AXI_DATA_C2H_00_awburst[1:0],BLP_M_AXI_DATA_C2H_00_awid[1:0],BLP_M_AXI_DATA_C2H_00_awlen[7:0],BLP_M_AXI_DATA_C2H_00_awready,BLP_M_AXI_DATA_C2H_00_awvalid,BLP_M_AXI_DATA_C2H_00_bid[1:0],BLP_M_AXI_DATA_C2H_00_bready,BLP_M_AXI_DATA_C2H_00_bresp[1:0],BLP_M_AXI_DATA_C2H_00_bvalid,BLP_M_AXI_DATA_C2H_00_rdata[511:0],BLP_M_AXI_DATA_C2H_00_rid[1:0],BLP_M_AXI_DATA_C2H_00_rlast,BLP_M_AXI_DATA_C2H_00_rready,BLP_M_AXI_DATA_C2H_00_rresp[1:0],BLP_M_AXI_DATA_C2H_00_rvalid,BLP_M_AXI_DATA_C2H_00_wdata[511:0],BLP_M_AXI_DATA_C2H_00_wlast,BLP_M_AXI_DATA_C2H_00_wready,BLP_M_AXI_DATA_C2H_00_wstrb[63:0],BLP_M_AXI_DATA_C2H_00_wvalid,BLP_S_AXI_CTRL_MGMT_00_araddr[24:0],BLP_S_AXI_CTRL_MGMT_00_arprot[2:0],BLP_S_AXI_CTRL_MGMT_00_arready,BLP_S_AXI_CTRL_MGMT_00_arvalid,BLP_S_AXI_CTRL_MGMT_00_awaddr[24:0],BLP_S_AXI_CTRL_MGMT_00_awprot[2:0],BLP_S_AXI_CTRL_MGMT_00_awready,BLP_S_AXI_CTRL_MGMT_00_awvalid,BLP_S_AXI_CTRL_MGMT_00_bready,BLP_S_AXI_CTRL_MGMT_00_bresp[1:0],BLP_S_AXI_CTRL_MGMT_00_bvalid,BLP_S_AXI_CTRL_MGMT_00_rdata[31:0],BLP_S_AXI_CTRL_MGMT_00_rready,BLP_S_AXI_CTRL_MGMT_00_rresp[1:0],BLP_S_AXI_CTRL_MGMT_00_rvalid,BLP_S_AXI_CTRL_MGMT_00_wdata[31:0],BLP_S_AXI_CTRL_MGMT_00_wready,BLP_S_AXI_CTRL_MGMT_00_wstrb[3:0],BLP_S_AXI_CTRL_MGMT_00_wvalid,BLP_S_AXI_CTRL_MGMT_01_araddr[24:0],BLP_S_AXI_CTRL_MGMT_01_arprot[2:0],BLP_S_AXI_CTRL_MGMT_01_arready,BLP_S_AXI_CTRL_MGMT_01_arvalid,BLP_S_AXI_CTRL_MGMT_01_awaddr[24:0],BLP_S_AXI_CTRL_MGMT_01_awprot[2:0],BLP_S_AXI_CTRL_MGMT_01_awready,BLP_S_AXI_CTRL_MGMT_01_awvalid,BLP_S_AXI_CTRL_MGMT_01_bready,BLP_S_AXI_CTRL_MGMT_01_bresp[1:0],BLP_S_AXI_CTRL_MGMT_01_bvalid,BLP_S_AXI_CTRL_MGMT_01_rdata[31:0],BLP_S_AXI_CTRL_MGMT_01_rready,BLP_S_AXI_CTRL_MGMT_01_rresp[1:0],BLP_S_AXI_CTRL_MGMT_01_rvalid,BLP_S_AXI_CTRL_MGMT_01_wdata[31:0],BLP_S_AXI_CTRL_MGMT_01_wready,BLP_S_AXI_CTRL_MGMT_01_wstrb[3:0],BLP_S_AXI_CTRL_MGMT_01_wvalid,BLP_S_AXI_CTRL_USER_00_araddr[24:0],BLP_S_AXI_CTRL_USER_00_arprot[2:0],BLP_S_AXI_CTRL_USER_00_arready,BLP_S_AXI_CTRL_USER_00_arvalid,BLP_S_AXI_CTRL_USER_00_awaddr[24:0],BLP_S_AXI_CTRL_USER_00_awprot[2:0],BLP_S_AXI_CTRL_USER_00_awready,BLP_S_AXI_CTRL_USER_00_awvalid,BLP_S_AXI_CTRL_USER_00_bready,BLP_S_AXI_CTRL_USER_00_bresp[1:0],BLP_S_AXI_CTRL_USER_00_bvalid,BLP_S_AXI_CTRL_USER_00_rdata[31:0],BLP_S_AXI_CTRL_USER_00_rready,BLP_S_AXI_CTRL_USER_00_rresp[1:0],BLP_S_AXI_CTRL_USER_00_rvalid,BLP_S_AXI_CTRL_USER_00_wdata[31:0],BLP_S_AXI_CTRL_USER_00_wready,BLP_S_AXI_CTRL_USER_00_wstrb[3:0],BLP_S_AXI_CTRL_USER_00_wvalid,BLP_S_AXI_CTRL_USER_01_araddr[24:0],BLP_S_AXI_CTRL_USER_01_arprot[2:0],BLP_S_AXI_CTRL_USER_01_arready,BLP_S_AXI_CTRL_USER_01_arvalid,BLP_S_AXI_CTRL_USER_01_awaddr[24:0],BLP_S_AXI_CTRL_USER_01_awprot[2:0],BLP_S_AXI_CTRL_USER_01_awready,BLP_S_AXI_CTRL_USER_01_awvalid,BLP_S_AXI_CTRL_USER_01_bready,BLP_S_AXI_CTRL_USER_01_bresp[1:0],BLP_S_AXI_CTRL_USER_01_bvalid,BLP_S_AXI_CTRL_USER_01_rdata[31:0],BLP_S_AXI_CTRL_USER_01_rready,BLP_S_AXI_CTRL_USER_01_rresp[1:0],BLP_S_AXI_CTRL_USER_01_rvalid,BLP_S_AXI_CTRL_USER_01_wdata[31:0],BLP_S_AXI_CTRL_USER_01_wready,BLP_S_AXI_CTRL_USER_01_wstrb[3:0],BLP_S_AXI_CTRL_USER_01_wvalid,BLP_S_AXI_CTRL_USER_02_araddr[24:0],BLP_S_AXI_CTRL_USER_02_arprot[2:0],BLP_S_AXI_CTRL_USER_02_arready,BLP_S_AXI_CTRL_USER_02_arvalid,BLP_S_AXI_CTRL_USER_02_awaddr[24:0],BLP_S_AXI_CTRL_USER_02_awprot[2:0],BLP_S_AXI_CTRL_USER_02_awready,BLP_S_AXI_CTRL_USER_02_awvalid,BLP_S_AXI_CTRL_USER_02_bready,BLP_S_AXI_CTRL_USER_02_bresp[1:0],BLP_S_AXI_CTRL_USER_02_bvalid,BLP_S_AXI_CTRL_USER_02_rdata[31:0],BLP_S_AXI_CTRL_USER_02_rready,BLP_S_AXI_CTRL_USER_02_rresp[1:0],BLP_S_AXI_CTRL_USER_02_rvalid,BLP_S_AXI_CTRL_USER_02_wdata[31:0],BLP_S_AXI_CTRL_USER_02_wready,BLP_S_AXI_CTRL_USER_02_wstrb[3:0],BLP_S_AXI_CTRL_USER_02_wvalid,BLP_S_AXI_CTRL_USER_03_araddr[24:0],BLP_S_AXI_CTRL_USER_03_arprot[2:0],BLP_S_AXI_CTRL_USER_03_arready,BLP_S_AXI_CTRL_USER_03_arvalid,BLP_S_AXI_CTRL_USER_03_awaddr[24:0],BLP_S_AXI_CTRL_USER_03_awprot[2:0],BLP_S_AXI_CTRL_USER_03_awready,BLP_S_AXI_CTRL_USER_03_awvalid,BLP_S_AXI_CTRL_USER_03_bready,BLP_S_AXI_CTRL_USER_03_bresp[1:0],BLP_S_AXI_CTRL_USER_03_bvalid,BLP_S_AXI_CTRL_USER_03_rdata[31:0],BLP_S_AXI_CTRL_USER_03_rready,BLP_S_AXI_CTRL_USER_03_rresp[1:0],BLP_S_AXI_CTRL_USER_03_rvalid,BLP_S_AXI_CTRL_USER_03_wdata[31:0],BLP_S_AXI_CTRL_USER_03_wready,BLP_S_AXI_CTRL_USER_03_wstrb[3:0],BLP_S_AXI_CTRL_USER_03_wvalid,BLP_S_AXI_DATA_H2C_00_araddr[38:0],BLP_S_AXI_DATA_H2C_00_arid[3:0],BLP_S_AXI_DATA_H2C_00_arlen[7:0],BLP_S_AXI_DATA_H2C_00_arready,BLP_S_AXI_DATA_H2C_00_arvalid,BLP_S_AXI_DATA_H2C_00_awaddr[38:0],BLP_S_AXI_DATA_H2C_00_awid[3:0],BLP_S_AXI_DATA_H2C_00_awlen[7:0],BLP_S_AXI_DATA_H2C_00_awready,BLP_S_AXI_DATA_H2C_00_awvalid,BLP_S_AXI_DATA_H2C_00_bid[3:0],BLP_S_AXI_DATA_H2C_00_bready,BLP_S_AXI_DATA_H2C_00_bresp[1:0],BLP_S_AXI_DATA_H2C_00_bvalid,BLP_S_AXI_DATA_H2C_00_rdata[511:0],BLP_S_AXI_DATA_H2C_00_rid[3:0],BLP_S_AXI_DATA_H2C_00_rlast,BLP_S_AXI_DATA_H2C_00_rready,BLP_S_AXI_DATA_H2C_00_rresp[1:0],BLP_S_AXI_DATA_H2C_00_rvalid,BLP_S_AXI_DATA_H2C_00_wdata[511:0],BLP_S_AXI_DATA_H2C_00_wlast,BLP_S_AXI_DATA_H2C_00_wready,BLP_S_AXI_DATA_H2C_00_wstrb[63:0],BLP_S_AXI_DATA_H2C_00_wvalid,blp_m_data_hbm_temp_00[6:0],blp_m_data_hbm_temp_01[6:0],blp_m_data_memory_calib_complete_00[0:0],blp_m_irq_cu_00[127:0],blp_m_irq_hbm_cattrip_00[0:0],blp_s_aclk_ctrl_00,blp_s_aclk_freerun_ref_00,blp_s_aclk_pcie_00,blp_s_aresetn_ctrl_00[0:0],blp_s_aresetn_pcie_00[0:0],blp_s_data_satellite_ctrl_data_00[3:0],io_clk_qsfp0_refclka_00_clk_n,io_clk_qsfp0_refclka_00_clk_p,io_clk_qsfp1_refclka_00_clk_n,io_clk_qsfp1_refclka_00_clk_p,io_gt_qsfp0_00_grx_n[3:0],io_gt_qsfp0_00_grx_p[3:0],io_gt_qsfp0_00_gtx_n[3:0],io_gt_qsfp0_00_gtx_p[3:0],io_gt_qsfp1_00_grx_n[3:0],io_gt_qsfp1_00_grx_p[3:0],io_gt_qsfp1_00_gtx_n[3:0],io_gt_qsfp1_00_gtx_p[3:0]" */;
  output [38:0]BLP_M_AXI_DATA_C2H_00_araddr;
  output [1:0]BLP_M_AXI_DATA_C2H_00_arburst;
  output [1:0]BLP_M_AXI_DATA_C2H_00_arid;
  output [7:0]BLP_M_AXI_DATA_C2H_00_arlen;
  input BLP_M_AXI_DATA_C2H_00_arready;
  output BLP_M_AXI_DATA_C2H_00_arvalid;
  output [38:0]BLP_M_AXI_DATA_C2H_00_awaddr;
  output [1:0]BLP_M_AXI_DATA_C2H_00_awburst;
  output [1:0]BLP_M_AXI_DATA_C2H_00_awid;
  output [7:0]BLP_M_AXI_DATA_C2H_00_awlen;
  input BLP_M_AXI_DATA_C2H_00_awready;
  output BLP_M_AXI_DATA_C2H_00_awvalid;
  input [1:0]BLP_M_AXI_DATA_C2H_00_bid;
  output BLP_M_AXI_DATA_C2H_00_bready;
  input [1:0]BLP_M_AXI_DATA_C2H_00_bresp;
  input BLP_M_AXI_DATA_C2H_00_bvalid;
  input [511:0]BLP_M_AXI_DATA_C2H_00_rdata;
  input [1:0]BLP_M_AXI_DATA_C2H_00_rid;
  input BLP_M_AXI_DATA_C2H_00_rlast;
  output BLP_M_AXI_DATA_C2H_00_rready;
  input [1:0]BLP_M_AXI_DATA_C2H_00_rresp;
  input BLP_M_AXI_DATA_C2H_00_rvalid;
  output [511:0]BLP_M_AXI_DATA_C2H_00_wdata;
  output BLP_M_AXI_DATA_C2H_00_wlast;
  input BLP_M_AXI_DATA_C2H_00_wready;
  output [63:0]BLP_M_AXI_DATA_C2H_00_wstrb;
  output BLP_M_AXI_DATA_C2H_00_wvalid;
  input [24:0]BLP_S_AXI_CTRL_MGMT_00_araddr;
  input [2:0]BLP_S_AXI_CTRL_MGMT_00_arprot;
  output BLP_S_AXI_CTRL_MGMT_00_arready;
  input BLP_S_AXI_CTRL_MGMT_00_arvalid;
  input [24:0]BLP_S_AXI_CTRL_MGMT_00_awaddr;
  input [2:0]BLP_S_AXI_CTRL_MGMT_00_awprot;
  output BLP_S_AXI_CTRL_MGMT_00_awready;
  input BLP_S_AXI_CTRL_MGMT_00_awvalid;
  input BLP_S_AXI_CTRL_MGMT_00_bready;
  output [1:0]BLP_S_AXI_CTRL_MGMT_00_bresp;
  output BLP_S_AXI_CTRL_MGMT_00_bvalid;
  output [31:0]BLP_S_AXI_CTRL_MGMT_00_rdata;
  input BLP_S_AXI_CTRL_MGMT_00_rready;
  output [1:0]BLP_S_AXI_CTRL_MGMT_00_rresp;
  output BLP_S_AXI_CTRL_MGMT_00_rvalid;
  input [31:0]BLP_S_AXI_CTRL_MGMT_00_wdata;
  output BLP_S_AXI_CTRL_MGMT_00_wready;
  input [3:0]BLP_S_AXI_CTRL_MGMT_00_wstrb;
  input BLP_S_AXI_CTRL_MGMT_00_wvalid;
  input [24:0]BLP_S_AXI_CTRL_MGMT_01_araddr;
  input [2:0]BLP_S_AXI_CTRL_MGMT_01_arprot;
  output BLP_S_AXI_CTRL_MGMT_01_arready;
  input BLP_S_AXI_CTRL_MGMT_01_arvalid;
  input [24:0]BLP_S_AXI_CTRL_MGMT_01_awaddr;
  input [2:0]BLP_S_AXI_CTRL_MGMT_01_awprot;
  output BLP_S_AXI_CTRL_MGMT_01_awready;
  input BLP_S_AXI_CTRL_MGMT_01_awvalid;
  input BLP_S_AXI_CTRL_MGMT_01_bready;
  output [1:0]BLP_S_AXI_CTRL_MGMT_01_bresp;
  output BLP_S_AXI_CTRL_MGMT_01_bvalid;
  output [31:0]BLP_S_AXI_CTRL_MGMT_01_rdata;
  input BLP_S_AXI_CTRL_MGMT_01_rready;
  output [1:0]BLP_S_AXI_CTRL_MGMT_01_rresp;
  output BLP_S_AXI_CTRL_MGMT_01_rvalid;
  input [31:0]BLP_S_AXI_CTRL_MGMT_01_wdata;
  output BLP_S_AXI_CTRL_MGMT_01_wready;
  input [3:0]BLP_S_AXI_CTRL_MGMT_01_wstrb;
  input BLP_S_AXI_CTRL_MGMT_01_wvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_00_araddr;
  input [2:0]BLP_S_AXI_CTRL_USER_00_arprot;
  output BLP_S_AXI_CTRL_USER_00_arready;
  input BLP_S_AXI_CTRL_USER_00_arvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_00_awaddr;
  input [2:0]BLP_S_AXI_CTRL_USER_00_awprot;
  output BLP_S_AXI_CTRL_USER_00_awready;
  input BLP_S_AXI_CTRL_USER_00_awvalid;
  input BLP_S_AXI_CTRL_USER_00_bready;
  output [1:0]BLP_S_AXI_CTRL_USER_00_bresp;
  output BLP_S_AXI_CTRL_USER_00_bvalid;
  output [31:0]BLP_S_AXI_CTRL_USER_00_rdata;
  input BLP_S_AXI_CTRL_USER_00_rready;
  output [1:0]BLP_S_AXI_CTRL_USER_00_rresp;
  output BLP_S_AXI_CTRL_USER_00_rvalid;
  input [31:0]BLP_S_AXI_CTRL_USER_00_wdata;
  output BLP_S_AXI_CTRL_USER_00_wready;
  input [3:0]BLP_S_AXI_CTRL_USER_00_wstrb;
  input BLP_S_AXI_CTRL_USER_00_wvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_01_araddr;
  input [2:0]BLP_S_AXI_CTRL_USER_01_arprot;
  output BLP_S_AXI_CTRL_USER_01_arready;
  input BLP_S_AXI_CTRL_USER_01_arvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_01_awaddr;
  input [2:0]BLP_S_AXI_CTRL_USER_01_awprot;
  output BLP_S_AXI_CTRL_USER_01_awready;
  input BLP_S_AXI_CTRL_USER_01_awvalid;
  input BLP_S_AXI_CTRL_USER_01_bready;
  output [1:0]BLP_S_AXI_CTRL_USER_01_bresp;
  output BLP_S_AXI_CTRL_USER_01_bvalid;
  output [31:0]BLP_S_AXI_CTRL_USER_01_rdata;
  input BLP_S_AXI_CTRL_USER_01_rready;
  output [1:0]BLP_S_AXI_CTRL_USER_01_rresp;
  output BLP_S_AXI_CTRL_USER_01_rvalid;
  input [31:0]BLP_S_AXI_CTRL_USER_01_wdata;
  output BLP_S_AXI_CTRL_USER_01_wready;
  input [3:0]BLP_S_AXI_CTRL_USER_01_wstrb;
  input BLP_S_AXI_CTRL_USER_01_wvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_02_araddr;
  input [2:0]BLP_S_AXI_CTRL_USER_02_arprot;
  output BLP_S_AXI_CTRL_USER_02_arready;
  input BLP_S_AXI_CTRL_USER_02_arvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_02_awaddr;
  input [2:0]BLP_S_AXI_CTRL_USER_02_awprot;
  output BLP_S_AXI_CTRL_USER_02_awready;
  input BLP_S_AXI_CTRL_USER_02_awvalid;
  input BLP_S_AXI_CTRL_USER_02_bready;
  output [1:0]BLP_S_AXI_CTRL_USER_02_bresp;
  output BLP_S_AXI_CTRL_USER_02_bvalid;
  output [31:0]BLP_S_AXI_CTRL_USER_02_rdata;
  input BLP_S_AXI_CTRL_USER_02_rready;
  output [1:0]BLP_S_AXI_CTRL_USER_02_rresp;
  output BLP_S_AXI_CTRL_USER_02_rvalid;
  input [31:0]BLP_S_AXI_CTRL_USER_02_wdata;
  output BLP_S_AXI_CTRL_USER_02_wready;
  input [3:0]BLP_S_AXI_CTRL_USER_02_wstrb;
  input BLP_S_AXI_CTRL_USER_02_wvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_03_araddr;
  input [2:0]BLP_S_AXI_CTRL_USER_03_arprot;
  output BLP_S_AXI_CTRL_USER_03_arready;
  input BLP_S_AXI_CTRL_USER_03_arvalid;
  input [24:0]BLP_S_AXI_CTRL_USER_03_awaddr;
  input [2:0]BLP_S_AXI_CTRL_USER_03_awprot;
  output BLP_S_AXI_CTRL_USER_03_awready;
  input BLP_S_AXI_CTRL_USER_03_awvalid;
  input BLP_S_AXI_CTRL_USER_03_bready;
  output [1:0]BLP_S_AXI_CTRL_USER_03_bresp;
  output BLP_S_AXI_CTRL_USER_03_bvalid;
  output [31:0]BLP_S_AXI_CTRL_USER_03_rdata;
  input BLP_S_AXI_CTRL_USER_03_rready;
  output [1:0]BLP_S_AXI_CTRL_USER_03_rresp;
  output BLP_S_AXI_CTRL_USER_03_rvalid;
  input [31:0]BLP_S_AXI_CTRL_USER_03_wdata;
  output BLP_S_AXI_CTRL_USER_03_wready;
  input [3:0]BLP_S_AXI_CTRL_USER_03_wstrb;
  input BLP_S_AXI_CTRL_USER_03_wvalid;
  input [38:0]BLP_S_AXI_DATA_H2C_00_araddr;
  input [3:0]BLP_S_AXI_DATA_H2C_00_arid;
  input [7:0]BLP_S_AXI_DATA_H2C_00_arlen;
  output BLP_S_AXI_DATA_H2C_00_arready;
  input BLP_S_AXI_DATA_H2C_00_arvalid;
  input [38:0]BLP_S_AXI_DATA_H2C_00_awaddr;
  input [3:0]BLP_S_AXI_DATA_H2C_00_awid;
  input [7:0]BLP_S_AXI_DATA_H2C_00_awlen;
  output BLP_S_AXI_DATA_H2C_00_awready;
  input BLP_S_AXI_DATA_H2C_00_awvalid;
  output [3:0]BLP_S_AXI_DATA_H2C_00_bid;
  input BLP_S_AXI_DATA_H2C_00_bready;
  output [1:0]BLP_S_AXI_DATA_H2C_00_bresp;
  output BLP_S_AXI_DATA_H2C_00_bvalid;
  output [511:0]BLP_S_AXI_DATA_H2C_00_rdata;
  output [3:0]BLP_S_AXI_DATA_H2C_00_rid;
  output BLP_S_AXI_DATA_H2C_00_rlast;
  input BLP_S_AXI_DATA_H2C_00_rready;
  output [1:0]BLP_S_AXI_DATA_H2C_00_rresp;
  output BLP_S_AXI_DATA_H2C_00_rvalid;
  input [511:0]BLP_S_AXI_DATA_H2C_00_wdata;
  input BLP_S_AXI_DATA_H2C_00_wlast;
  output BLP_S_AXI_DATA_H2C_00_wready;
  input [63:0]BLP_S_AXI_DATA_H2C_00_wstrb;
  input BLP_S_AXI_DATA_H2C_00_wvalid;
  output [6:0]blp_m_data_hbm_temp_00;
  output [6:0]blp_m_data_hbm_temp_01;
  output [0:0]blp_m_data_memory_calib_complete_00;
  output [127:0]blp_m_irq_cu_00;
  output [0:0]blp_m_irq_hbm_cattrip_00;
  input blp_s_aclk_ctrl_00;
  input blp_s_aclk_freerun_ref_00;
  input blp_s_aclk_pcie_00;
  input [0:0]blp_s_aresetn_ctrl_00;
  input [0:0]blp_s_aresetn_pcie_00;
  input [3:0]blp_s_data_satellite_ctrl_data_00;
  input io_clk_qsfp0_refclka_00_clk_n;
  input io_clk_qsfp0_refclka_00_clk_p;
  input io_clk_qsfp1_refclka_00_clk_n;
  input io_clk_qsfp1_refclka_00_clk_p;
  input [3:0]io_gt_qsfp0_00_grx_n;
  input [3:0]io_gt_qsfp0_00_grx_p;
  output [3:0]io_gt_qsfp0_00_gtx_n;
  output [3:0]io_gt_qsfp0_00_gtx_p;
  input [3:0]io_gt_qsfp1_00_grx_n;
  input [3:0]io_gt_qsfp1_00_grx_p;
  output [3:0]io_gt_qsfp1_00_gtx_n;
  output [3:0]io_gt_qsfp1_00_gtx_p;
endmodule
