-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2023.2 (lin64) Build 4029153 Fri Oct 13 20:13:54 MDT 2023
-- Date        : Sat Jan 17 14:52:28 2026
-- Host        : cse-es62-02.cse.chalmers.se running 64-bit Rocky Linux release 9.6 (Blue Onyx)
-- Command     : write_vhdl -force -mode synth_stub
--               /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.vhdl
-- Design      : ulp
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xcu55c-fsvh2892-2L-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity ulp is
  Port ( 
    BLP_M_AXI_DATA_C2H_00_araddr : out STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_M_AXI_DATA_C2H_00_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_arid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_M_AXI_DATA_C2H_00_arready : in STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_arvalid : out STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_awaddr : out STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_M_AXI_DATA_C2H_00_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_awid : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_M_AXI_DATA_C2H_00_awready : in STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_awvalid : out STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_bid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_bready : out STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_bvalid : in STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_rdata : in STD_LOGIC_VECTOR ( 511 downto 0 );
    BLP_M_AXI_DATA_C2H_00_rid : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_rlast : in STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_rready : out STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_M_AXI_DATA_C2H_00_rvalid : in STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_wdata : out STD_LOGIC_VECTOR ( 511 downto 0 );
    BLP_M_AXI_DATA_C2H_00_wlast : out STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_wready : in STD_LOGIC;
    BLP_M_AXI_DATA_C2H_00_wstrb : out STD_LOGIC_VECTOR ( 63 downto 0 );
    BLP_M_AXI_DATA_C2H_00_wvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_00_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_MGMT_00_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_MGMT_01_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_MGMT_01_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_00_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_00_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_00_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_00_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_00_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_00_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_00_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_00_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_00_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_00_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_01_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_01_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_01_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_01_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_01_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_01_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_01_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_01_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_01_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_01_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_02_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_02_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_02_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_02_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_02_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_02_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_02_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_02_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_02_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_02_wvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_araddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_03_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_03_arready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_arvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_awaddr : in STD_LOGIC_VECTOR ( 24 downto 0 );
    BLP_S_AXI_CTRL_USER_03_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    BLP_S_AXI_CTRL_USER_03_awready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_awvalid : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_bready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_03_bvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_03_rready : in STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_CTRL_USER_03_rvalid : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    BLP_S_AXI_CTRL_USER_03_wready : out STD_LOGIC;
    BLP_S_AXI_CTRL_USER_03_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_CTRL_USER_03_wvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_araddr : in STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_00_arready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_arvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_awaddr : in STD_LOGIC_VECTOR ( 38 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awid : in STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awlen : in STD_LOGIC_VECTOR ( 7 downto 0 );
    BLP_S_AXI_DATA_H2C_00_awready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_awvalid : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_bid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_bready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_00_bvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_rdata : out STD_LOGIC_VECTOR ( 511 downto 0 );
    BLP_S_AXI_DATA_H2C_00_rid : out STD_LOGIC_VECTOR ( 3 downto 0 );
    BLP_S_AXI_DATA_H2C_00_rlast : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_rready : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    BLP_S_AXI_DATA_H2C_00_rvalid : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_wdata : in STD_LOGIC_VECTOR ( 511 downto 0 );
    BLP_S_AXI_DATA_H2C_00_wlast : in STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_wready : out STD_LOGIC;
    BLP_S_AXI_DATA_H2C_00_wstrb : in STD_LOGIC_VECTOR ( 63 downto 0 );
    BLP_S_AXI_DATA_H2C_00_wvalid : in STD_LOGIC;
    blp_m_data_hbm_temp_00 : out STD_LOGIC_VECTOR ( 6 downto 0 );
    blp_m_data_hbm_temp_01 : out STD_LOGIC_VECTOR ( 6 downto 0 );
    blp_m_data_memory_calib_complete_00 : out STD_LOGIC_VECTOR ( 0 to 0 );
    blp_m_irq_cu_00 : out STD_LOGIC_VECTOR ( 127 downto 0 );
    blp_m_irq_hbm_cattrip_00 : out STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_aclk_ctrl_00 : in STD_LOGIC;
    blp_s_aclk_freerun_ref_00 : in STD_LOGIC;
    blp_s_aclk_pcie_00 : in STD_LOGIC;
    blp_s_aresetn_ctrl_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_aresetn_pcie_00 : in STD_LOGIC_VECTOR ( 0 to 0 );
    blp_s_data_satellite_ctrl_data_00 : in STD_LOGIC_VECTOR ( 3 downto 0 );
    io_clk_qsfp0_refclka_00_clk_n : in STD_LOGIC;
    io_clk_qsfp0_refclka_00_clk_p : in STD_LOGIC;
    io_clk_qsfp1_refclka_00_clk_n : in STD_LOGIC;
    io_clk_qsfp1_refclka_00_clk_p : in STD_LOGIC;
    io_gt_qsfp0_00_grx_n : in STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp0_00_grx_p : in STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp0_00_gtx_n : out STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp0_00_gtx_p : out STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp1_00_grx_n : in STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp1_00_grx_p : in STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp1_00_gtx_n : out STD_LOGIC_VECTOR ( 3 downto 0 );
    io_gt_qsfp1_00_gtx_p : out STD_LOGIC_VECTOR ( 3 downto 0 )
  );

end ulp;

architecture stub of ulp is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "BLP_M_AXI_DATA_C2H_00_araddr[38:0],BLP_M_AXI_DATA_C2H_00_arburst[1:0],BLP_M_AXI_DATA_C2H_00_arid[1:0],BLP_M_AXI_DATA_C2H_00_arlen[7:0],BLP_M_AXI_DATA_C2H_00_arready,BLP_M_AXI_DATA_C2H_00_arvalid,BLP_M_AXI_DATA_C2H_00_awaddr[38:0],BLP_M_AXI_DATA_C2H_00_awburst[1:0],BLP_M_AXI_DATA_C2H_00_awid[1:0],BLP_M_AXI_DATA_C2H_00_awlen[7:0],BLP_M_AXI_DATA_C2H_00_awready,BLP_M_AXI_DATA_C2H_00_awvalid,BLP_M_AXI_DATA_C2H_00_bid[1:0],BLP_M_AXI_DATA_C2H_00_bready,BLP_M_AXI_DATA_C2H_00_bresp[1:0],BLP_M_AXI_DATA_C2H_00_bvalid,BLP_M_AXI_DATA_C2H_00_rdata[511:0],BLP_M_AXI_DATA_C2H_00_rid[1:0],BLP_M_AXI_DATA_C2H_00_rlast,BLP_M_AXI_DATA_C2H_00_rready,BLP_M_AXI_DATA_C2H_00_rresp[1:0],BLP_M_AXI_DATA_C2H_00_rvalid,BLP_M_AXI_DATA_C2H_00_wdata[511:0],BLP_M_AXI_DATA_C2H_00_wlast,BLP_M_AXI_DATA_C2H_00_wready,BLP_M_AXI_DATA_C2H_00_wstrb[63:0],BLP_M_AXI_DATA_C2H_00_wvalid,BLP_S_AXI_CTRL_MGMT_00_araddr[24:0],BLP_S_AXI_CTRL_MGMT_00_arprot[2:0],BLP_S_AXI_CTRL_MGMT_00_arready,BLP_S_AXI_CTRL_MGMT_00_arvalid,BLP_S_AXI_CTRL_MGMT_00_awaddr[24:0],BLP_S_AXI_CTRL_MGMT_00_awprot[2:0],BLP_S_AXI_CTRL_MGMT_00_awready,BLP_S_AXI_CTRL_MGMT_00_awvalid,BLP_S_AXI_CTRL_MGMT_00_bready,BLP_S_AXI_CTRL_MGMT_00_bresp[1:0],BLP_S_AXI_CTRL_MGMT_00_bvalid,BLP_S_AXI_CTRL_MGMT_00_rdata[31:0],BLP_S_AXI_CTRL_MGMT_00_rready,BLP_S_AXI_CTRL_MGMT_00_rresp[1:0],BLP_S_AXI_CTRL_MGMT_00_rvalid,BLP_S_AXI_CTRL_MGMT_00_wdata[31:0],BLP_S_AXI_CTRL_MGMT_00_wready,BLP_S_AXI_CTRL_MGMT_00_wstrb[3:0],BLP_S_AXI_CTRL_MGMT_00_wvalid,BLP_S_AXI_CTRL_MGMT_01_araddr[24:0],BLP_S_AXI_CTRL_MGMT_01_arprot[2:0],BLP_S_AXI_CTRL_MGMT_01_arready,BLP_S_AXI_CTRL_MGMT_01_arvalid,BLP_S_AXI_CTRL_MGMT_01_awaddr[24:0],BLP_S_AXI_CTRL_MGMT_01_awprot[2:0],BLP_S_AXI_CTRL_MGMT_01_awready,BLP_S_AXI_CTRL_MGMT_01_awvalid,BLP_S_AXI_CTRL_MGMT_01_bready,BLP_S_AXI_CTRL_MGMT_01_bresp[1:0],BLP_S_AXI_CTRL_MGMT_01_bvalid,BLP_S_AXI_CTRL_MGMT_01_rdata[31:0],BLP_S_AXI_CTRL_MGMT_01_rready,BLP_S_AXI_CTRL_MGMT_01_rresp[1:0],BLP_S_AXI_CTRL_MGMT_01_rvalid,BLP_S_AXI_CTRL_MGMT_01_wdata[31:0],BLP_S_AXI_CTRL_MGMT_01_wready,BLP_S_AXI_CTRL_MGMT_01_wstrb[3:0],BLP_S_AXI_CTRL_MGMT_01_wvalid,BLP_S_AXI_CTRL_USER_00_araddr[24:0],BLP_S_AXI_CTRL_USER_00_arprot[2:0],BLP_S_AXI_CTRL_USER_00_arready,BLP_S_AXI_CTRL_USER_00_arvalid,BLP_S_AXI_CTRL_USER_00_awaddr[24:0],BLP_S_AXI_CTRL_USER_00_awprot[2:0],BLP_S_AXI_CTRL_USER_00_awready,BLP_S_AXI_CTRL_USER_00_awvalid,BLP_S_AXI_CTRL_USER_00_bready,BLP_S_AXI_CTRL_USER_00_bresp[1:0],BLP_S_AXI_CTRL_USER_00_bvalid,BLP_S_AXI_CTRL_USER_00_rdata[31:0],BLP_S_AXI_CTRL_USER_00_rready,BLP_S_AXI_CTRL_USER_00_rresp[1:0],BLP_S_AXI_CTRL_USER_00_rvalid,BLP_S_AXI_CTRL_USER_00_wdata[31:0],BLP_S_AXI_CTRL_USER_00_wready,BLP_S_AXI_CTRL_USER_00_wstrb[3:0],BLP_S_AXI_CTRL_USER_00_wvalid,BLP_S_AXI_CTRL_USER_01_araddr[24:0],BLP_S_AXI_CTRL_USER_01_arprot[2:0],BLP_S_AXI_CTRL_USER_01_arready,BLP_S_AXI_CTRL_USER_01_arvalid,BLP_S_AXI_CTRL_USER_01_awaddr[24:0],BLP_S_AXI_CTRL_USER_01_awprot[2:0],BLP_S_AXI_CTRL_USER_01_awready,BLP_S_AXI_CTRL_USER_01_awvalid,BLP_S_AXI_CTRL_USER_01_bready,BLP_S_AXI_CTRL_USER_01_bresp[1:0],BLP_S_AXI_CTRL_USER_01_bvalid,BLP_S_AXI_CTRL_USER_01_rdata[31:0],BLP_S_AXI_CTRL_USER_01_rready,BLP_S_AXI_CTRL_USER_01_rresp[1:0],BLP_S_AXI_CTRL_USER_01_rvalid,BLP_S_AXI_CTRL_USER_01_wdata[31:0],BLP_S_AXI_CTRL_USER_01_wready,BLP_S_AXI_CTRL_USER_01_wstrb[3:0],BLP_S_AXI_CTRL_USER_01_wvalid,BLP_S_AXI_CTRL_USER_02_araddr[24:0],BLP_S_AXI_CTRL_USER_02_arprot[2:0],BLP_S_AXI_CTRL_USER_02_arready,BLP_S_AXI_CTRL_USER_02_arvalid,BLP_S_AXI_CTRL_USER_02_awaddr[24:0],BLP_S_AXI_CTRL_USER_02_awprot[2:0],BLP_S_AXI_CTRL_USER_02_awready,BLP_S_AXI_CTRL_USER_02_awvalid,BLP_S_AXI_CTRL_USER_02_bready,BLP_S_AXI_CTRL_USER_02_bresp[1:0],BLP_S_AXI_CTRL_USER_02_bvalid,BLP_S_AXI_CTRL_USER_02_rdata[31:0],BLP_S_AXI_CTRL_USER_02_rready,BLP_S_AXI_CTRL_USER_02_rresp[1:0],BLP_S_AXI_CTRL_USER_02_rvalid,BLP_S_AXI_CTRL_USER_02_wdata[31:0],BLP_S_AXI_CTRL_USER_02_wready,BLP_S_AXI_CTRL_USER_02_wstrb[3:0],BLP_S_AXI_CTRL_USER_02_wvalid,BLP_S_AXI_CTRL_USER_03_araddr[24:0],BLP_S_AXI_CTRL_USER_03_arprot[2:0],BLP_S_AXI_CTRL_USER_03_arready,BLP_S_AXI_CTRL_USER_03_arvalid,BLP_S_AXI_CTRL_USER_03_awaddr[24:0],BLP_S_AXI_CTRL_USER_03_awprot[2:0],BLP_S_AXI_CTRL_USER_03_awready,BLP_S_AXI_CTRL_USER_03_awvalid,BLP_S_AXI_CTRL_USER_03_bready,BLP_S_AXI_CTRL_USER_03_bresp[1:0],BLP_S_AXI_CTRL_USER_03_bvalid,BLP_S_AXI_CTRL_USER_03_rdata[31:0],BLP_S_AXI_CTRL_USER_03_rready,BLP_S_AXI_CTRL_USER_03_rresp[1:0],BLP_S_AXI_CTRL_USER_03_rvalid,BLP_S_AXI_CTRL_USER_03_wdata[31:0],BLP_S_AXI_CTRL_USER_03_wready,BLP_S_AXI_CTRL_USER_03_wstrb[3:0],BLP_S_AXI_CTRL_USER_03_wvalid,BLP_S_AXI_DATA_H2C_00_araddr[38:0],BLP_S_AXI_DATA_H2C_00_arid[3:0],BLP_S_AXI_DATA_H2C_00_arlen[7:0],BLP_S_AXI_DATA_H2C_00_arready,BLP_S_AXI_DATA_H2C_00_arvalid,BLP_S_AXI_DATA_H2C_00_awaddr[38:0],BLP_S_AXI_DATA_H2C_00_awid[3:0],BLP_S_AXI_DATA_H2C_00_awlen[7:0],BLP_S_AXI_DATA_H2C_00_awready,BLP_S_AXI_DATA_H2C_00_awvalid,BLP_S_AXI_DATA_H2C_00_bid[3:0],BLP_S_AXI_DATA_H2C_00_bready,BLP_S_AXI_DATA_H2C_00_bresp[1:0],BLP_S_AXI_DATA_H2C_00_bvalid,BLP_S_AXI_DATA_H2C_00_rdata[511:0],BLP_S_AXI_DATA_H2C_00_rid[3:0],BLP_S_AXI_DATA_H2C_00_rlast,BLP_S_AXI_DATA_H2C_00_rready,BLP_S_AXI_DATA_H2C_00_rresp[1:0],BLP_S_AXI_DATA_H2C_00_rvalid,BLP_S_AXI_DATA_H2C_00_wdata[511:0],BLP_S_AXI_DATA_H2C_00_wlast,BLP_S_AXI_DATA_H2C_00_wready,BLP_S_AXI_DATA_H2C_00_wstrb[63:0],BLP_S_AXI_DATA_H2C_00_wvalid,blp_m_data_hbm_temp_00[6:0],blp_m_data_hbm_temp_01[6:0],blp_m_data_memory_calib_complete_00[0:0],blp_m_irq_cu_00[127:0],blp_m_irq_hbm_cattrip_00[0:0],blp_s_aclk_ctrl_00,blp_s_aclk_freerun_ref_00,blp_s_aclk_pcie_00,blp_s_aresetn_ctrl_00[0:0],blp_s_aresetn_pcie_00[0:0],blp_s_data_satellite_ctrl_data_00[3:0],io_clk_qsfp0_refclka_00_clk_n,io_clk_qsfp0_refclka_00_clk_p,io_clk_qsfp1_refclka_00_clk_n,io_clk_qsfp1_refclka_00_clk_p,io_gt_qsfp0_00_grx_n[3:0],io_gt_qsfp0_00_grx_p[3:0],io_gt_qsfp0_00_gtx_n[3:0],io_gt_qsfp0_00_gtx_p[3:0],io_gt_qsfp1_00_grx_n[3:0],io_gt_qsfp1_00_grx_p[3:0],io_gt_qsfp1_00_gtx_n[3:0],io_gt_qsfp1_00_gtx_p[3:0]";
begin
end;
