# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2.xci
# IP: The module: 'ulp_axi_gpio_null_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_axi_gpio_null_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_axi_gpio_null_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_axi_gpio_null_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2.xci
# IP: The module: 'ulp_axi_gpio_null_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_axi_gpio_null_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_axi_gpio_null_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/m2_2/shared/dat480-final/project_split.intf0.xilinx_u55c_gen3x16_xdma_3_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_axi_gpio_null_2/ulp_axi_gpio_null_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_axi_gpio_null_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
