// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ethernet_header_inserter_handle_output (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        no_ip_header_out_dout,
        no_ip_header_out_num_data_valid,
        no_ip_header_out_fifo_cap,
        no_ip_header_out_empty_n,
        no_ip_header_out_read,
        ip_header_checksum_dout,
        ip_header_checksum_num_data_valid,
        ip_header_checksum_fifo_cap,
        ip_header_checksum_empty_n,
        ip_header_checksum_read,
        arpTableReplay_TVALID,
        myMacAddress_dout,
        myMacAddress_num_data_valid,
        myMacAddress_fifo_cap,
        myMacAddress_empty_n,
        myMacAddress_read,
        dataOut_TREADY,
        arpTableReplay_TDATA,
        arpTableReplay_TREADY,
        dataOut_TDATA,
        dataOut_TVALID,
        dataOut_TKEEP,
        dataOut_TSTRB,
        dataOut_TLAST
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [1023:0] no_ip_header_out_dout;
input  [4:0] no_ip_header_out_num_data_valid;
input  [4:0] no_ip_header_out_fifo_cap;
input   no_ip_header_out_empty_n;
output   no_ip_header_out_read;
input  [1023:0] ip_header_checksum_dout;
input  [4:0] ip_header_checksum_num_data_valid;
input  [4:0] ip_header_checksum_fifo_cap;
input   ip_header_checksum_empty_n;
output   ip_header_checksum_read;
input   arpTableReplay_TVALID;
input  [47:0] myMacAddress_dout;
input  [2:0] myMacAddress_num_data_valid;
input  [2:0] myMacAddress_fifo_cap;
input   myMacAddress_empty_n;
output   myMacAddress_read;
input   dataOut_TREADY;
input  [127:0] arpTableReplay_TDATA;
output   arpTableReplay_TREADY;
output  [511:0] dataOut_TDATA;
output   dataOut_TVALID;
output  [63:0] dataOut_TKEEP;
output  [63:0] dataOut_TSTRB;
output  [0:0] dataOut_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg no_ip_header_out_read;
reg ip_header_checksum_read;
reg myMacAddress_read;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] grp_nbreadreq_fu_132_p3;
reg    ap_predicate_op8_read_state1;
wire   [0:0] grp_nbreadreq_fu_146_p3;
reg    ap_predicate_op24_read_state1;
reg    ap_predicate_op42_read_state1;
reg    ap_predicate_op51_read_state1;
wire   [0:0] tmp_i_nbreadreq_fu_160_p3;
reg    ap_predicate_op60_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [2:0] mw_state_load_reg_540;
wire   [2:0] mw_state_load_reg_540_pp0_iter0_reg;
reg   [0:0] tmp_4_i_reg_544;
reg    ap_predicate_op91_write_state2;
reg   [0:0] tmp_3_i_reg_574;
reg    ap_predicate_op97_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [2:0] mw_state_load_reg_540_pp0_iter1_reg;
reg   [0:0] tmp_4_i_reg_544_pp0_iter1_reg;
reg    ap_predicate_op107_write_state3;
reg   [0:0] tmp_3_i_reg_574_pp0_iter1_reg;
reg    ap_predicate_op109_write_state3;
wire    regslice_both_dataOut_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [2:0] mw_state;
reg   [111:0] previous_word_data;
reg   [13:0] previous_word_keep;
reg    arpTableReplay_TDATA_blk_n;
reg    myMacAddress_blk_n;
reg    dataOut_TDATA_blk_n;
reg    ip_header_checksum_blk_n;
reg    no_ip_header_out_blk_n;
wire   [399:0] trunc_ln186_fu_267_p1;
reg   [399:0] trunc_ln186_reg_551;
reg   [49:0] tmp_9_i7_reg_556;
reg   [111:0] tmp_10_i_reg_561;
reg   [13:0] tmp_11_i8_reg_566;
wire   [399:0] trunc_ln154_fu_321_p1;
reg   [399:0] trunc_ln154_reg_581;
reg   [49:0] tmp_5_i3_reg_586;
reg   [111:0] tmp_6_i_reg_591;
reg   [13:0] tmp_7_i4_reg_596;
reg   [0:0] tmp_i_reg_613;
wire   [0:0] tmp_i_reg_613_pp0_iter0_reg;
wire   [47:0] reply_macAddress_fu_407_p1;
reg   [47:0] reply_macAddress_reg_617;
wire   [0:0] reply_hit_fu_411_p3;
reg   [0:0] reply_hit_reg_622;
wire   [0:0] reply_hit_reg_622_pp0_iter0_reg;
wire   [511:0] sendWord_data_2_fu_437_p3;
wire   [63:0] sendWord_keep_2_fu_445_p3;
wire   [511:0] sendWord_data_1_fu_463_p3;
wire   [63:0] sendWord_keep_1_fu_471_p3;
wire   [511:0] zext_ln104_fu_497_p1;
wire   [63:0] zext_ln104_1_fu_510_p1;
reg   [1:0] ap_phi_mux_storemerge1_i_phi_fu_201_p4;
wire   [1:0] ap_phi_reg_pp0_iter0_storemerge1_i_reg_198;
wire   [0:0] ap_phi_reg_pp0_iter0_sendWord_last_1_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter1_sendWord_last_1_reg_209;
wire   [0:0] grp_fu_247_p3;
wire   [0:0] tmp_1_fu_301_p3;
wire   [0:0] ap_phi_reg_pp0_iter0_sendWord_last_reg_228;
reg   [0:0] ap_phi_reg_pp0_iter1_sendWord_last_reg_228;
wire   [0:0] grp_fu_255_p3;
wire   [0:0] tmp_fu_361_p3;
wire   [2:0] select_ln132_fu_387_p3;
wire   [2:0] zext_ln121_fu_419_p1;
wire   [111:0] zext_ln117_fu_524_p1;
wire   [112:0] sendWord_data_fu_489_p3;
wire   [14:0] sendWord_keep_fu_502_p3;
wire   [99:0] zext_ln117_cast_fu_515_p4;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_arpTableReplay_U_apdone_blk;
wire   [127:0] arpTableReplay_TDATA_int_regslice;
wire    arpTableReplay_TVALID_int_regslice;
reg    arpTableReplay_TREADY_int_regslice;
wire    regslice_both_arpTableReplay_U_ack_in;
reg   [511:0] dataOut_TDATA_int_regslice;
reg    dataOut_TVALID_int_regslice;
wire    dataOut_TREADY_int_regslice;
wire    regslice_both_dataOut_V_data_V_U_vld_out;
wire    regslice_both_dataOut_V_keep_V_U_apdone_blk;
reg   [63:0] dataOut_TKEEP_int_regslice;
wire    regslice_both_dataOut_V_keep_V_U_ack_in_dummy;
wire    regslice_both_dataOut_V_keep_V_U_vld_out;
wire    regslice_both_dataOut_V_strb_V_U_apdone_blk;
wire   [63:0] dataOut_TSTRB_int_regslice;
wire    regslice_both_dataOut_V_strb_V_U_ack_in_dummy;
wire    regslice_both_dataOut_V_strb_V_U_vld_out;
wire    regslice_both_dataOut_V_last_V_U_apdone_blk;
reg   [0:0] dataOut_TLAST_int_regslice;
wire    regslice_both_dataOut_V_last_V_U_ack_in_dummy;
wire    regslice_both_dataOut_V_last_V_U_vld_out;
reg    ap_condition_102;
reg    ap_condition_422;
reg    ap_condition_343;
reg    ap_condition_340;
reg    ap_condition_354;
reg    ap_condition_364;
reg    ap_condition_360;
reg    ap_condition_373;
reg    ap_condition_194;
reg    ap_condition_397;
reg    ap_condition_251;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 mw_state = 3'd0;
#0 previous_word_data = 112'd0;
#0 previous_word_keep = 14'd0;
end

ethernet_header_inserter_regslice_both #(
    .DataWidth( 128 ))
regslice_both_arpTableReplay_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpTableReplay_TDATA),
    .vld_in(arpTableReplay_TVALID),
    .ack_in(regslice_both_arpTableReplay_U_ack_in),
    .data_out(arpTableReplay_TDATA_int_regslice),
    .vld_out(arpTableReplay_TVALID_int_regslice),
    .ack_out(arpTableReplay_TREADY_int_regslice),
    .apdone_blk(regslice_both_arpTableReplay_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 512 ))
regslice_both_dataOut_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataOut_TDATA_int_regslice),
    .vld_in(dataOut_TVALID_int_regslice),
    .ack_in(dataOut_TREADY_int_regslice),
    .data_out(dataOut_TDATA),
    .vld_out(regslice_both_dataOut_V_data_V_U_vld_out),
    .ack_out(dataOut_TREADY),
    .apdone_blk(regslice_both_dataOut_V_data_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_dataOut_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataOut_TKEEP_int_regslice),
    .vld_in(dataOut_TVALID_int_regslice),
    .ack_in(regslice_both_dataOut_V_keep_V_U_ack_in_dummy),
    .data_out(dataOut_TKEEP),
    .vld_out(regslice_both_dataOut_V_keep_V_U_vld_out),
    .ack_out(dataOut_TREADY),
    .apdone_blk(regslice_both_dataOut_V_keep_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_dataOut_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataOut_TSTRB_int_regslice),
    .vld_in(dataOut_TVALID_int_regslice),
    .ack_in(regslice_both_dataOut_V_strb_V_U_ack_in_dummy),
    .data_out(dataOut_TSTRB),
    .vld_out(regslice_both_dataOut_V_strb_V_U_vld_out),
    .ack_out(dataOut_TREADY),
    .apdone_blk(regslice_both_dataOut_V_strb_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dataOut_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataOut_TLAST_int_regslice),
    .vld_in(dataOut_TVALID_int_regslice),
    .ack_in(regslice_both_dataOut_V_last_V_U_ack_in_dummy),
    .data_out(dataOut_TLAST),
    .vld_out(regslice_both_dataOut_V_last_V_U_vld_out),
    .ack_out(dataOut_TREADY),
    .apdone_blk(regslice_both_dataOut_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_1_fu_301_p3 == 1'd0) & (grp_fu_247_p3 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_1_reg_209 <= 1'd1;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_247_p3 == 1'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_1_fu_301_p3 == 1'd1) & (grp_fu_247_p3 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_1_reg_209 <= 1'd0;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_1_reg_209 <= ap_phi_reg_pp0_iter0_sendWord_last_1_reg_209;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_fu_361_p3 == 1'd0) & (grp_fu_255_p3 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_reg_228 <= 1'd1;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1) & (tmp_fu_361_p3 == 1'd1) & (grp_fu_255_p3 == 1'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state1) & (grp_fu_255_p3 == 1'd0)))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_reg_228 <= 1'd0;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_sendWord_last_reg_228 <= ap_phi_reg_pp0_iter0_sendWord_last_reg_228;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_194)) begin
        if ((1'b1 == ap_condition_102)) begin
            mw_state <= zext_ln121_fu_419_p1;
        end else if ((mw_state == 3'd5)) begin
            mw_state <= 3'd0;
        end else if (((grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd1))) begin
            mw_state <= select_ln132_fu_387_p3;
        end else if ((1'b1 == ap_condition_373)) begin
            mw_state <= 3'd0;
        end else if ((1'b1 == ap_condition_360)) begin
            mw_state <= 3'd5;
        end else if ((1'b1 == ap_condition_364)) begin
            mw_state <= 3'd0;
        end else if ((1'b1 == ap_condition_354)) begin
            mw_state <= 3'd4;
        end else if ((1'b1 == ap_condition_340)) begin
            mw_state <= 3'd5;
        end else if ((1'b1 == ap_condition_343)) begin
            mw_state <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_251)) begin
        if ((1'b1 == ap_condition_397)) begin
            previous_word_data <= zext_ln117_fu_524_p1;
        end else if (((tmp_3_i_reg_574 == 1'd1) & (mw_state_load_reg_540 == 3'd3))) begin
            previous_word_data <= tmp_6_i_reg_591;
        end else if (((tmp_4_i_reg_544 == 1'd1) & (mw_state_load_reg_540 == 3'd4))) begin
            previous_word_data <= tmp_10_i_reg_561;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_251)) begin
        if ((1'b1 == ap_condition_397)) begin
            previous_word_keep <= 14'd16383;
        end else if (((tmp_3_i_reg_574 == 1'd1) & (mw_state_load_reg_540 == 3'd3))) begin
            previous_word_keep <= tmp_7_i4_reg_596;
        end else if (((tmp_4_i_reg_544 == 1'd1) & (mw_state_load_reg_540 == 3'd4))) begin
            previous_word_keep <= tmp_11_i8_reg_566;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        mw_state_load_reg_540 <= mw_state;
        reply_hit_reg_622 <= arpTableReplay_TDATA_int_regslice[128'd64];
        reply_macAddress_reg_617 <= reply_macAddress_fu_407_p1;
        tmp_10_i_reg_561 <= {{no_ip_header_out_dout[511:400]}};
        tmp_11_i8_reg_566 <= {{no_ip_header_out_dout[575:562]}};
        tmp_3_i_reg_574 <= grp_nbreadreq_fu_146_p3;
        tmp_4_i_reg_544 <= grp_nbreadreq_fu_132_p3;
        tmp_5_i3_reg_586 <= {{ip_header_checksum_dout[561:512]}};
        tmp_6_i_reg_591 <= {{ip_header_checksum_dout[511:400]}};
        tmp_7_i4_reg_596 <= {{ip_header_checksum_dout[575:562]}};
        tmp_9_i7_reg_556 <= {{no_ip_header_out_dout[561:512]}};
        tmp_i_reg_613 <= tmp_i_nbreadreq_fu_160_p3;
        trunc_ln154_reg_581 <= trunc_ln154_fu_321_p1;
        trunc_ln186_reg_551 <= trunc_ln186_fu_267_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        mw_state_load_reg_540_pp0_iter1_reg <= mw_state_load_reg_540;
        tmp_3_i_reg_574_pp0_iter1_reg <= tmp_3_i_reg_574;
        tmp_4_i_reg_544_pp0_iter1_reg <= tmp_4_i_reg_544;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_102)) begin
        if ((reply_hit_fu_411_p3 == 1'd0)) begin
            ap_phi_mux_storemerge1_i_phi_fu_201_p4 = 2'd1;
        end else if ((reply_hit_fu_411_p3 == 1'd1)) begin
            ap_phi_mux_storemerge1_i_phi_fu_201_p4 = 2'd3;
        end else begin
            ap_phi_mux_storemerge1_i_phi_fu_201_p4 = ap_phi_reg_pp0_iter0_storemerge1_i_reg_198;
        end
    end else begin
        ap_phi_mux_storemerge1_i_phi_fu_201_p4 = ap_phi_reg_pp0_iter0_storemerge1_i_reg_198;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1) & (ap_predicate_op60_read_state1 == 1'b1))) begin
        arpTableReplay_TDATA_blk_n = arpTableReplay_TVALID_int_regslice;
    end else begin
        arpTableReplay_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op60_read_state1 == 1'b1))) begin
        arpTableReplay_TREADY_int_regslice = 1'b1;
    end else begin
        arpTableReplay_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter2_fsm_state3) & (mw_state_load_reg_540_pp0_iter1_reg == 3'd5)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op109_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op107_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (mw_state_load_reg_540 == 3'd5)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op97_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op91_write_state2 == 1'b1)))) begin
        dataOut_TDATA_blk_n = dataOut_TREADY_int_regslice;
    end else begin
        dataOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((mw_state_load_reg_540 == 3'd5)) begin
            dataOut_TDATA_int_regslice = zext_ln104_fu_497_p1;
        end else if ((ap_predicate_op97_write_state2 == 1'b1)) begin
            dataOut_TDATA_int_regslice = sendWord_data_1_fu_463_p3;
        end else if ((ap_predicate_op91_write_state2 == 1'b1)) begin
            dataOut_TDATA_int_regslice = sendWord_data_2_fu_437_p3;
        end else begin
            dataOut_TDATA_int_regslice = 'bx;
        end
    end else begin
        dataOut_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((mw_state_load_reg_540 == 3'd5)) begin
            dataOut_TKEEP_int_regslice = zext_ln104_1_fu_510_p1;
        end else if ((ap_predicate_op97_write_state2 == 1'b1)) begin
            dataOut_TKEEP_int_regslice = sendWord_keep_1_fu_471_p3;
        end else if ((ap_predicate_op91_write_state2 == 1'b1)) begin
            dataOut_TKEEP_int_regslice = sendWord_keep_2_fu_445_p3;
        end else begin
            dataOut_TKEEP_int_regslice = 'bx;
        end
    end else begin
        dataOut_TKEEP_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_422)) begin
        if ((mw_state_load_reg_540 == 3'd5)) begin
            dataOut_TLAST_int_regslice = 1'd1;
        end else if ((ap_predicate_op97_write_state2 == 1'b1)) begin
            dataOut_TLAST_int_regslice = ap_phi_reg_pp0_iter1_sendWord_last_reg_228;
        end else if ((ap_predicate_op91_write_state2 == 1'b1)) begin
            dataOut_TLAST_int_regslice = ap_phi_reg_pp0_iter1_sendWord_last_1_reg_209;
        end else begin
            dataOut_TLAST_int_regslice = 'bx;
        end
    end else begin
        dataOut_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (mw_state_load_reg_540 == 3'd5)) | (~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op97_write_state2 == 1'b1)) | (~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op91_write_state2 == 1'b1)))) begin
        dataOut_TVALID_int_regslice = 1'b1;
    end else begin
        dataOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_predicate_op51_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_predicate_op24_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)))) begin
        ip_header_checksum_blk_n = ip_header_checksum_empty_n;
    end else begin
        ip_header_checksum_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op51_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op24_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ip_header_checksum_read = 1'b1;
    end else begin
        ip_header_checksum_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter1_fsm_state2)) begin
        myMacAddress_blk_n = myMacAddress_empty_n;
    end else begin
        myMacAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        myMacAddress_read = 1'b1;
    end else begin
        myMacAddress_read = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_predicate_op8_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1)))) begin
        no_ip_header_out_blk_n = no_ip_header_out_empty_n;
    end else begin
        no_ip_header_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op42_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (ap_predicate_op8_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        no_ip_header_out_read = 1'b1;
    end else begin
        no_ip_header_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | (ap_done_reg == 1'b1)) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | (ap_done_reg == 1'b1)) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | ((ap_predicate_op51_read_state1 == 1'b1) & (ip_header_checksum_empty_n == 1'b0)) | ((ap_predicate_op42_read_state1 == 1'b1) & (no_ip_header_out_empty_n == 1'b0)) | ((ap_predicate_op24_read_state1 == 1'b1) & (ip_header_checksum_empty_n == 1'b0)) | ((arpTableReplay_TVALID_int_regslice == 1'b0) & (ap_predicate_op60_read_state1 == 1'b1)) | ((ap_predicate_op8_read_state1 == 1'b1) & (no_ip_header_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_io = (((dataOut_TREADY_int_regslice == 1'b0) & (mw_state_load_reg_540 == 3'd5)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op97_write_state2 == 1'b1)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op91_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((myMacAddress_empty_n == 1'b0) | ((dataOut_TREADY_int_regslice == 1'b0) & (mw_state_load_reg_540 == 3'd5)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op97_write_state2 == 1'b1)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op91_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = (((dataOut_TREADY_int_regslice == 1'b0) & (mw_state_load_reg_540_pp0_iter1_reg == 3'd5)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op109_write_state3 == 1'b1)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_dataOut_V_data_V_U_apdone_blk == 1'b1) | ((dataOut_TREADY_int_regslice == 1'b0) & (mw_state_load_reg_540_pp0_iter1_reg == 3'd5)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op109_write_state3 == 1'b1)) | ((dataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op107_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_102 = (~(mw_state == 3'd5) & ~(mw_state == 3'd1) & ~(mw_state == 3'd2) & ~(mw_state == 3'd3) & ~(mw_state == 3'd4) & (tmp_i_nbreadreq_fu_160_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_194 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_251 = (~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

always @ (*) begin
    ap_condition_340 = ((grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd4) & (tmp_1_fu_301_p3 == 1'd1) & (grp_fu_247_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_343 = ((grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd4) & (tmp_1_fu_301_p3 == 1'd0) & (grp_fu_247_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_354 = ((grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3) & (grp_fu_255_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_360 = ((grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3) & (tmp_fu_361_p3 == 1'd1) & (grp_fu_255_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_364 = ((grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3) & (tmp_fu_361_p3 == 1'd0) & (grp_fu_255_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_373 = ((grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd2) & (grp_fu_247_p3 == 1'd1));
end

always @ (*) begin
    ap_condition_397 = (~(mw_state_load_reg_540_pp0_iter0_reg == 3'd2) & ~(mw_state_load_reg_540_pp0_iter0_reg == 3'd1) & ~(mw_state_load_reg_540 == 3'd5) & ~(mw_state_load_reg_540 == 3'd3) & ~(mw_state_load_reg_540 == 3'd4) & (reply_hit_reg_622_pp0_iter0_reg == 1'd1) & (tmp_i_reg_613_pp0_iter0_reg == 1'd1));
end

always @ (*) begin
    ap_condition_422 = (~((1'b1 == ap_block_state2_pp0_stage0_iter1) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2));
end

assign ap_phi_reg_pp0_iter0_sendWord_last_1_reg_209 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_last_reg_228 = 'bx;

assign ap_phi_reg_pp0_iter0_storemerge1_i_reg_198 = 'bx;

always @ (*) begin
    ap_predicate_op107_write_state3 = ((tmp_4_i_reg_544_pp0_iter1_reg == 1'd1) & (mw_state_load_reg_540_pp0_iter1_reg == 3'd4));
end

always @ (*) begin
    ap_predicate_op109_write_state3 = ((tmp_3_i_reg_574_pp0_iter1_reg == 1'd1) & (mw_state_load_reg_540_pp0_iter1_reg == 3'd3));
end

always @ (*) begin
    ap_predicate_op24_read_state1 = ((grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd3));
end

always @ (*) begin
    ap_predicate_op42_read_state1 = ((grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd2));
end

always @ (*) begin
    ap_predicate_op51_read_state1 = ((grp_nbreadreq_fu_146_p3 == 1'd1) & (mw_state == 3'd1));
end

always @ (*) begin
    ap_predicate_op60_read_state1 = (~(mw_state == 3'd5) & ~(mw_state == 3'd1) & ~(mw_state == 3'd2) & ~(mw_state == 3'd3) & ~(mw_state == 3'd4) & (tmp_i_nbreadreq_fu_160_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op8_read_state1 = ((grp_nbreadreq_fu_132_p3 == 1'd1) & (mw_state == 3'd4));
end

always @ (*) begin
    ap_predicate_op91_write_state2 = ((tmp_4_i_reg_544 == 1'd1) & (mw_state_load_reg_540 == 3'd4));
end

always @ (*) begin
    ap_predicate_op97_write_state2 = ((tmp_3_i_reg_574 == 1'd1) & (mw_state_load_reg_540 == 3'd3));
end

assign arpTableReplay_TREADY = regslice_both_arpTableReplay_U_ack_in;

assign dataOut_TSTRB_int_regslice = 'bx;

assign dataOut_TVALID = regslice_both_dataOut_V_data_V_U_vld_out;

assign grp_fu_247_p3 = no_ip_header_out_dout[1024'd576];

assign grp_fu_255_p3 = ip_header_checksum_dout[1024'd576];

assign grp_nbreadreq_fu_132_p3 = no_ip_header_out_empty_n;

assign grp_nbreadreq_fu_146_p3 = ip_header_checksum_empty_n;

assign mw_state_load_reg_540_pp0_iter0_reg = mw_state_load_reg_540;

assign reply_hit_fu_411_p3 = arpTableReplay_TDATA_int_regslice[128'd64];

assign reply_hit_reg_622_pp0_iter0_reg = reply_hit_reg_622;

assign reply_macAddress_fu_407_p1 = arpTableReplay_TDATA_int_regslice[47:0];

assign select_ln132_fu_387_p3 = ((grp_fu_255_p3[0:0] == 1'b1) ? 3'd0 : 3'd2);

assign sendWord_data_1_fu_463_p3 = {{trunc_ln154_reg_581}, {previous_word_data}};

assign sendWord_data_2_fu_437_p3 = {{trunc_ln186_reg_551}, {previous_word_data}};

assign sendWord_data_fu_489_p3 = {{1'd0}, {previous_word_data}};

assign sendWord_keep_1_fu_471_p3 = {{tmp_5_i3_reg_586}, {previous_word_keep}};

assign sendWord_keep_2_fu_445_p3 = {{tmp_9_i7_reg_556}, {previous_word_keep}};

assign sendWord_keep_fu_502_p3 = {{1'd0}, {previous_word_keep}};

assign tmp_1_fu_301_p3 = no_ip_header_out_dout[32'd562];

assign tmp_fu_361_p3 = ip_header_checksum_dout[32'd562];

assign tmp_i_nbreadreq_fu_160_p3 = arpTableReplay_TVALID_int_regslice;

assign tmp_i_reg_613_pp0_iter0_reg = tmp_i_reg_613;

assign trunc_ln154_fu_321_p1 = ip_header_checksum_dout[399:0];

assign trunc_ln186_fu_267_p1 = no_ip_header_out_dout[399:0];

assign zext_ln104_1_fu_510_p1 = sendWord_keep_fu_502_p3;

assign zext_ln104_fu_497_p1 = sendWord_data_fu_489_p3;

assign zext_ln117_cast_fu_515_p4 = {{{{4'd8}, {myMacAddress_dout}}}, {reply_macAddress_reg_617}};

assign zext_ln117_fu_524_p1 = zext_ln117_cast_fu_515_p4;

assign zext_ln121_fu_419_p1 = ap_phi_mux_storemerge1_i_phi_fu_201_p4;

endmodule //ethernet_header_inserter_handle_output
