// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ethernet_header_inserter_broadcaster_and_mac_request (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        dataIn_TVALID,
        ip_header_out_din,
        ip_header_out_num_data_valid,
        ip_header_out_fifo_cap,
        ip_header_out_full_n,
        ip_header_out_write,
        no_ip_header_out_din,
        no_ip_header_out_num_data_valid,
        no_ip_header_out_fifo_cap,
        no_ip_header_out_full_n,
        no_ip_header_out_write,
        arpTableRequest_TREADY,
        start_out,
        start_write,
        dataIn_TDATA,
        dataIn_TREADY,
        dataIn_TKEEP,
        dataIn_TSTRB,
        dataIn_TLAST,
        arpTableRequest_TDATA,
        arpTableRequest_TVALID,
        regSubNetMask,
        regDefaultGateway
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   dataIn_TVALID;
output  [1023:0] ip_header_out_din;
input  [4:0] ip_header_out_num_data_valid;
input  [4:0] ip_header_out_fifo_cap;
input   ip_header_out_full_n;
output   ip_header_out_write;
output  [1023:0] no_ip_header_out_din;
input  [4:0] no_ip_header_out_num_data_valid;
input  [4:0] no_ip_header_out_fifo_cap;
input   no_ip_header_out_full_n;
output   no_ip_header_out_write;
input   arpTableRequest_TREADY;
output   start_out;
output   start_write;
input  [511:0] dataIn_TDATA;
output   dataIn_TREADY;
input  [63:0] dataIn_TKEEP;
input  [63:0] dataIn_TSTRB;
input  [0:0] dataIn_TLAST;
output  [31:0] arpTableRequest_TDATA;
output   arpTableRequest_TVALID;
input  [31:0] regSubNetMask;
input  [31:0] regDefaultGateway;

reg ap_done;
reg ap_idle;
reg ip_header_out_write;
reg no_ip_header_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg    internal_ap_ready;
wire   [0:0] tmp_i_nbreadreq_fu_66_p6;
reg    ap_predicate_op21_read_state1;
reg    ap_predicate_op34_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] bmr_fsm_state_load_reg_214;
reg   [0:0] tmp_i_reg_218;
reg    ap_predicate_op49_write_state2;
reg    ap_predicate_op52_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] bmr_fsm_state_load_reg_214_pp0_iter1_reg;
reg   [0:0] tmp_i_reg_218_pp0_iter1_reg;
reg   [0:0] icmp_ln58_reg_249;
reg    ap_predicate_op53_write_state3;
reg    ap_predicate_op54_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] bmr_fsm_state_load_reg_214_pp0_iter2_reg;
reg   [0:0] tmp_i_reg_218_pp0_iter2_reg;
reg   [0:0] icmp_ln58_reg_249_pp0_iter2_reg;
reg    ap_predicate_op55_write_state4;
reg    ap_predicate_op57_write_state4;
wire    regslice_both_arpTableRequest_U_apdone_blk;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state4_io;
wire    ap_CS_iter3_fsm_state4;
reg   [0:0] bmr_fsm_state;
reg    dataIn_TDATA_blk_n;
reg    arpTableRequest_TDATA_blk_n;
reg    ip_header_out_blk_n;
reg    no_ip_header_out_blk_n;
reg   [511:0] reg_137;
reg   [63:0] reg_141;
wire   [0:0] grp_fu_133_p1;
reg   [0:0] currWord_last_reg_222;
reg   [31:0] dst_ip_addr_reg_227;
reg   [31:0] dst_ip_addr_reg_227_pp0_iter1_reg;
reg   [31:0] regSubNetMask_read_reg_233;
reg   [31:0] regDefaultGateway_read_reg_238;
reg   [31:0] regDefaultGateway_read_reg_238_pp0_iter1_reg;
reg   [0:0] currWord_last_1_reg_244;
wire   [0:0] icmp_ln58_fu_180_p2;
wire   [31:0] xor_ln58_fu_171_p2;
wire   [31:0] and_ln58_fu_175_p2;
wire   [576:0] tmp_4_i_fu_186_p4;
wire   [576:0] tmp_3_i_fu_200_p4;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
wire    regslice_both_dataIn_V_data_V_U_apdone_blk;
wire   [511:0] dataIn_TDATA_int_regslice;
wire    dataIn_TVALID_int_regslice;
reg    dataIn_TREADY_int_regslice;
wire    regslice_both_dataIn_V_data_V_U_ack_in;
wire    regslice_both_dataIn_V_keep_V_U_apdone_blk;
wire   [63:0] dataIn_TKEEP_int_regslice;
wire    regslice_both_dataIn_V_keep_V_U_vld_out;
wire    regslice_both_dataIn_V_keep_V_U_ack_in;
wire    regslice_both_dataIn_V_strb_V_U_apdone_blk;
wire   [63:0] dataIn_TSTRB_int_regslice;
wire    regslice_both_dataIn_V_strb_V_U_vld_out;
wire    regslice_both_dataIn_V_strb_V_U_ack_in;
wire    regslice_both_dataIn_V_last_V_U_apdone_blk;
wire   [0:0] dataIn_TLAST_int_regslice;
wire    regslice_both_dataIn_V_last_V_U_vld_out;
wire    regslice_both_dataIn_V_last_V_U_ack_in;
reg   [31:0] arpTableRequest_TDATA_int_regslice;
reg    arpTableRequest_TVALID_int_regslice;
wire    arpTableRequest_TREADY_int_regslice;
wire    regslice_both_arpTableRequest_U_vld_out;
reg    ap_condition_300;
reg    ap_condition_450;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 bmr_fsm_state = 1'd0;
end

ethernet_header_inserter_regslice_both #(
    .DataWidth( 512 ))
regslice_both_dataIn_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataIn_TDATA),
    .vld_in(dataIn_TVALID),
    .ack_in(regslice_both_dataIn_V_data_V_U_ack_in),
    .data_out(dataIn_TDATA_int_regslice),
    .vld_out(dataIn_TVALID_int_regslice),
    .ack_out(dataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_dataIn_V_data_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_dataIn_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataIn_TKEEP),
    .vld_in(dataIn_TVALID),
    .ack_in(regslice_both_dataIn_V_keep_V_U_ack_in),
    .data_out(dataIn_TKEEP_int_regslice),
    .vld_out(regslice_both_dataIn_V_keep_V_U_vld_out),
    .ack_out(dataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_dataIn_V_keep_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 64 ))
regslice_both_dataIn_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataIn_TSTRB),
    .vld_in(dataIn_TVALID),
    .ack_in(regslice_both_dataIn_V_strb_V_U_ack_in),
    .data_out(dataIn_TSTRB_int_regslice),
    .vld_out(regslice_both_dataIn_V_strb_V_U_vld_out),
    .ack_out(dataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_dataIn_V_strb_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dataIn_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dataIn_TLAST),
    .vld_in(dataIn_TVALID),
    .ack_in(regslice_both_dataIn_V_last_V_U_ack_in),
    .data_out(dataIn_TLAST_int_regslice),
    .vld_out(regslice_both_dataIn_V_last_V_U_vld_out),
    .ack_out(dataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_dataIn_V_last_V_U_apdone_blk)
);

ethernet_header_inserter_regslice_both #(
    .DataWidth( 32 ))
regslice_both_arpTableRequest_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(arpTableRequest_TDATA_int_regslice),
    .vld_in(arpTableRequest_TVALID_int_regslice),
    .ack_in(arpTableRequest_TREADY_int_regslice),
    .data_out(arpTableRequest_TDATA),
    .vld_out(regslice_both_arpTableRequest_U_vld_out),
    .ack_out(arpTableRequest_TREADY),
    .apdone_blk(regslice_both_arpTableRequest_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_450)) begin
        if (((bmr_fsm_state == 1'd1) & (grp_fu_133_p1 == 1'd1))) begin
            bmr_fsm_state <= 1'd0;
        end else if (((bmr_fsm_state == 1'd0) & (grp_fu_133_p1 == 1'd0))) begin
            bmr_fsm_state <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        bmr_fsm_state_load_reg_214 <= bmr_fsm_state;
        currWord_last_1_reg_244 <= dataIn_TLAST_int_regslice;
        currWord_last_reg_222 <= dataIn_TLAST_int_regslice;
        dst_ip_addr_reg_227 <= {{dataIn_TDATA_int_regslice[159:128]}};
        regDefaultGateway_read_reg_238 <= regDefaultGateway;
        regSubNetMask_read_reg_233 <= regSubNetMask;
        tmp_i_reg_218 <= tmp_i_nbreadreq_fu_66_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        bmr_fsm_state_load_reg_214_pp0_iter1_reg <= bmr_fsm_state_load_reg_214;
        dst_ip_addr_reg_227_pp0_iter1_reg <= dst_ip_addr_reg_227;
        icmp_ln58_reg_249 <= icmp_ln58_fu_180_p2;
        regDefaultGateway_read_reg_238_pp0_iter1_reg <= regDefaultGateway_read_reg_238;
        tmp_i_reg_218_pp0_iter1_reg <= tmp_i_reg_218;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        bmr_fsm_state_load_reg_214_pp0_iter2_reg <= bmr_fsm_state_load_reg_214_pp0_iter1_reg;
        icmp_ln58_reg_249_pp0_iter2_reg <= icmp_ln58_reg_249;
        tmp_i_reg_218_pp0_iter2_reg <= tmp_i_reg_218_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_i_nbreadreq_fu_66_p6 == 1'd1) & (bmr_fsm_state == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_i_nbreadreq_fu_66_p6 == 1'd1) & (bmr_fsm_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        reg_137 <= dataIn_TDATA_int_regslice;
        reg_141 <= dataIn_TKEEP_int_regslice;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage0_iter1)) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter3_fsm_state4) & (ap_predicate_op57_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (ap_predicate_op55_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op54_write_state3 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op53_write_state3 == 1'b1)))) begin
        arpTableRequest_TDATA_blk_n = arpTableRequest_TREADY_int_regslice;
    end else begin
        arpTableRequest_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_300)) begin
        if ((ap_predicate_op54_write_state3 == 1'b1)) begin
            arpTableRequest_TDATA_int_regslice = dst_ip_addr_reg_227_pp0_iter1_reg;
        end else if ((ap_predicate_op53_write_state3 == 1'b1)) begin
            arpTableRequest_TDATA_int_regslice = regDefaultGateway_read_reg_238_pp0_iter1_reg;
        end else begin
            arpTableRequest_TDATA_int_regslice = 'bx;
        end
    end else begin
        arpTableRequest_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op54_write_state3 == 1'b1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op53_write_state3 == 1'b1)))) begin
        arpTableRequest_TVALID_int_regslice = 1'b1;
    end else begin
        arpTableRequest_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (ap_predicate_op34_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1)) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (ap_predicate_op21_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (real_start == 1'b1)))) begin
        dataIn_TDATA_blk_n = dataIn_TVALID_int_regslice;
    end else begin
        dataIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (ap_predicate_op34_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (ap_predicate_op21_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        dataIn_TREADY_int_regslice = 1'b1;
    end else begin
        dataIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op49_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ip_header_out_blk_n = ip_header_out_full_n;
    end else begin
        ip_header_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (ap_predicate_op49_write_state2 == 1'b1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ip_header_out_write = 1'b1;
    end else begin
        ip_header_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op52_write_state2 == 1'b1))) begin
        no_ip_header_out_blk_n = no_ip_header_out_full_n;
    end else begin
        no_ip_header_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op52_write_state2 == 1'b1))) begin
        no_ip_header_out_write = 1'b1;
    end else begin
        no_ip_header_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter1_fsm_state2) & (1'b0 == ap_block_state2_pp0_stage0_iter1))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & ~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2)))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

assign and_ln58_fu_175_p2 = (xor_ln58_fu_171_p2 & regSubNetMask_read_reg_233);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | ((ap_predicate_op34_read_state1 == 1'b1) & (dataIn_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op21_read_state1 == 1'b1) & (dataIn_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((ap_predicate_op49_write_state2 == 1'b1) & (ip_header_out_full_n == 1'b0)) | ((ap_predicate_op52_write_state2 == 1'b1) & (no_ip_header_out_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = (((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op54_write_state3 == 1'b1)) | ((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op53_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op54_write_state3 == 1'b1)) | ((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op53_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_io = (((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) | ((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((regslice_both_arpTableRequest_U_apdone_blk == 1'b1) | ((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op57_write_state4 == 1'b1)) | ((arpTableRequest_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_condition_300 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3))) & (1'b1 == ap_CS_iter2_fsm_state3));
end

always @ (*) begin
    ap_condition_450 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter3_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter3))) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter2))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_i_nbreadreq_fu_66_p6 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_predicate_op21_read_state1 = ((tmp_i_nbreadreq_fu_66_p6 == 1'd1) & (bmr_fsm_state == 1'd0));
end

always @ (*) begin
    ap_predicate_op34_read_state1 = ((tmp_i_nbreadreq_fu_66_p6 == 1'd1) & (bmr_fsm_state == 1'd1));
end

always @ (*) begin
    ap_predicate_op49_write_state2 = ((tmp_i_reg_218 == 1'd1) & (bmr_fsm_state_load_reg_214 == 1'd0));
end

always @ (*) begin
    ap_predicate_op52_write_state2 = ((tmp_i_reg_218 == 1'd1) & (bmr_fsm_state_load_reg_214 == 1'd1));
end

always @ (*) begin
    ap_predicate_op53_write_state3 = ((icmp_ln58_reg_249 == 1'd0) & (tmp_i_reg_218_pp0_iter1_reg == 1'd1) & (bmr_fsm_state_load_reg_214_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op54_write_state3 = ((icmp_ln58_reg_249 == 1'd1) & (tmp_i_reg_218_pp0_iter1_reg == 1'd1) & (bmr_fsm_state_load_reg_214_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op55_write_state4 = ((icmp_ln58_reg_249_pp0_iter2_reg == 1'd0) & (tmp_i_reg_218_pp0_iter2_reg == 1'd1) & (bmr_fsm_state_load_reg_214_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op57_write_state4 = ((icmp_ln58_reg_249_pp0_iter2_reg == 1'd1) & (tmp_i_reg_218_pp0_iter2_reg == 1'd1) & (bmr_fsm_state_load_reg_214_pp0_iter2_reg == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign arpTableRequest_TVALID = regslice_both_arpTableRequest_U_vld_out;

assign dataIn_TREADY = regslice_both_dataIn_V_data_V_U_ack_in;

assign grp_fu_133_p1 = dataIn_TLAST_int_regslice;

assign icmp_ln58_fu_180_p2 = ((and_ln58_fu_175_p2 == 32'd0) ? 1'b1 : 1'b0);

assign ip_header_out_din = tmp_4_i_fu_186_p4;

assign no_ip_header_out_din = tmp_3_i_fu_200_p4;

assign start_out = real_start;

assign tmp_3_i_fu_200_p4 = {{{currWord_last_1_reg_244}, {reg_141}}, {reg_137}};

assign tmp_4_i_fu_186_p4 = {{{currWord_last_reg_222}, {reg_141}}, {reg_137}};

assign tmp_i_nbreadreq_fu_66_p6 = dataIn_TVALID_int_regslice;

assign xor_ln58_fu_171_p2 = (regDefaultGateway_read_reg_238 ^ dst_ip_addr_reg_227);

endmodule //ethernet_header_inserter_broadcaster_and_mac_request
