// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="krnl_proj_split_krnl_proj_split,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu55c-fsvh2892-2L-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.100000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=138,HLS_SYN_DSP=0,HLS_SYN_FF=6951,HLS_SYN_LUT=43478,HLS_VERSION=2023_2}" *)

module krnl_proj_split (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        input_stream_TDATA,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        output_stream_TDATA,
        output_stream_TKEEP,
        output_stream_TSTRB,
        output_stream_TUSER,
        output_stream_TLAST,
        output_stream_TID,
        output_stream_TDEST,
        input_stream_TVALID,
        input_stream_TREADY,
        output_stream_TVALID,
        output_stream_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [511:0] input_stream_TDATA;
input  [63:0] input_stream_TKEEP;
input  [63:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [15:0] input_stream_TDEST;
output  [511:0] output_stream_TDATA;
output  [63:0] output_stream_TKEEP;
output  [63:0] output_stream_TSTRB;
output  [0:0] output_stream_TUSER;
output  [0:0] output_stream_TLAST;
output  [0:0] output_stream_TID;
output  [15:0] output_stream_TDEST;
input   input_stream_TVALID;
output   input_stream_TREADY;
output   output_stream_TVALID;
input   output_stream_TREADY;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    input_split_U0_ap_start;
wire    input_split_U0_start_full_n;
wire    input_split_U0_ap_done;
wire    input_split_U0_ap_continue;
wire    input_split_U0_ap_idle;
wire    input_split_U0_ap_ready;
wire    input_split_U0_start_out;
wire    input_split_U0_start_write;
wire    input_split_U0_input_stream_TREADY;
wire   [8:0] input_split_U0_short_bytes_din;
wire    input_split_U0_short_bytes_write;
wire   [8:0] input_split_U0_long_bytes_din;
wire    input_split_U0_long_bytes_write;
wire   [15:0] input_split_U0_ap_return_0;
wire   [63:0] input_split_U0_ap_return_1;
wire    ap_channel_done_bytes_channel;
wire    bytes_channel_full_n;
reg    ap_sync_reg_channel_write_bytes_channel;
wire    ap_sync_channel_write_bytes_channel;
wire    ap_channel_done_dest_channel;
wire    dest_channel_full_n;
reg    ap_sync_reg_channel_write_dest_channel;
wire    ap_sync_channel_write_dest_channel;
wire    matcher_engine_1720_16_U0_ap_start;
wire    matcher_engine_1720_16_U0_ap_done;
wire    matcher_engine_1720_16_U0_ap_continue;
wire    matcher_engine_1720_16_U0_ap_idle;
wire    matcher_engine_1720_16_U0_ap_ready;
wire    matcher_engine_1720_16_U0_short_bytes_read;
wire   [32:0] matcher_engine_1720_16_U0_short_matches_din;
wire    matcher_engine_1720_16_U0_short_matches_write;
wire    matcher_engine_957_214_U0_ap_start;
wire    matcher_engine_957_214_U0_ap_done;
wire    matcher_engine_957_214_U0_ap_continue;
wire    matcher_engine_957_214_U0_ap_idle;
wire    matcher_engine_957_214_U0_ap_ready;
wire    matcher_engine_957_214_U0_long_bytes_read;
wire   [32:0] matcher_engine_957_214_U0_long_matches_din;
wire    matcher_engine_957_214_U0_long_matches_write;
wire    merge_matches_U0_ap_start;
wire    merge_matches_U0_ap_done;
wire    merge_matches_U0_ap_continue;
wire    merge_matches_U0_ap_idle;
wire    merge_matches_U0_ap_ready;
wire    merge_matches_U0_short_matches_read;
wire    merge_matches_U0_long_matches_read;
wire   [511:0] merge_matches_U0_output_stream_TDATA;
wire    merge_matches_U0_output_stream_TVALID;
wire   [63:0] merge_matches_U0_output_stream_TKEEP;
wire   [63:0] merge_matches_U0_output_stream_TSTRB;
wire   [0:0] merge_matches_U0_output_stream_TUSER;
wire   [0:0] merge_matches_U0_output_stream_TLAST;
wire   [0:0] merge_matches_U0_output_stream_TID;
wire   [15:0] merge_matches_U0_output_stream_TDEST;
wire    ap_sync_continue;
wire    Block_entry211_proc_U0_ap_start;
wire    Block_entry211_proc_U0_ap_done;
wire    Block_entry211_proc_U0_ap_continue;
wire    Block_entry211_proc_U0_ap_idle;
wire    Block_entry211_proc_U0_ap_ready;
wire   [63:0] Block_entry211_proc_U0_processed_bytes;
wire    Block_entry211_proc_U0_processed_bytes_ap_vld;
wire   [63:0] Block_entry211_proc_U0_processed_cycles;
wire    Block_entry211_proc_U0_processed_cycles_ap_vld;
wire    short_bytes_full_n;
wire   [8:0] short_bytes_dout;
wire   [6:0] short_bytes_num_data_valid;
wire   [6:0] short_bytes_fifo_cap;
wire    short_bytes_empty_n;
wire    long_bytes_full_n;
wire   [8:0] long_bytes_dout;
wire   [6:0] long_bytes_num_data_valid;
wire   [6:0] long_bytes_fifo_cap;
wire    long_bytes_empty_n;
wire   [15:0] dest_channel_dout;
wire   [2:0] dest_channel_num_data_valid;
wire   [2:0] dest_channel_fifo_cap;
wire    dest_channel_empty_n;
wire   [63:0] bytes_channel_dout;
wire   [2:0] bytes_channel_num_data_valid;
wire   [2:0] bytes_channel_fifo_cap;
wire    bytes_channel_empty_n;
wire    short_matches_full_n;
wire   [32:0] short_matches_dout;
wire   [6:0] short_matches_num_data_valid;
wire   [6:0] short_matches_fifo_cap;
wire    short_matches_empty_n;
wire    long_matches_full_n;
wire   [32:0] long_matches_dout;
wire   [6:0] long_matches_num_data_valid;
wire   [6:0] long_matches_fifo_cap;
wire    long_matches_empty_n;
wire    ap_sync_done;
wire   [0:0] start_for_matcher_engine_1720_16_U0_din;
wire    start_for_matcher_engine_1720_16_U0_full_n;
wire   [0:0] start_for_matcher_engine_1720_16_U0_dout;
wire    start_for_matcher_engine_1720_16_U0_empty_n;
wire   [0:0] start_for_matcher_engine_957_214_U0_din;
wire    start_for_matcher_engine_957_214_U0_full_n;
wire   [0:0] start_for_matcher_engine_957_214_U0_dout;
wire    start_for_matcher_engine_957_214_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_channel_write_bytes_channel = 1'b0;
#0 ap_sync_reg_channel_write_dest_channel = 1'b0;
end

krnl_proj_split_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .processed_bytes(Block_entry211_proc_U0_processed_bytes),
    .processed_cycles(Block_entry211_proc_U0_processed_cycles),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

krnl_proj_split_input_split input_split_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(input_split_U0_ap_start),
    .start_full_n(input_split_U0_start_full_n),
    .ap_done(input_split_U0_ap_done),
    .ap_continue(input_split_U0_ap_continue),
    .ap_idle(input_split_U0_ap_idle),
    .ap_ready(input_split_U0_ap_ready),
    .start_out(input_split_U0_start_out),
    .start_write(input_split_U0_start_write),
    .input_stream_TDATA(input_stream_TDATA),
    .input_stream_TVALID(input_stream_TVALID),
    .input_stream_TREADY(input_split_U0_input_stream_TREADY),
    .input_stream_TKEEP(input_stream_TKEEP),
    .input_stream_TSTRB(input_stream_TSTRB),
    .input_stream_TUSER(input_stream_TUSER),
    .input_stream_TLAST(input_stream_TLAST),
    .input_stream_TID(input_stream_TID),
    .input_stream_TDEST(input_stream_TDEST),
    .short_bytes_din(input_split_U0_short_bytes_din),
    .short_bytes_num_data_valid(short_bytes_num_data_valid),
    .short_bytes_fifo_cap(short_bytes_fifo_cap),
    .short_bytes_full_n(short_bytes_full_n),
    .short_bytes_write(input_split_U0_short_bytes_write),
    .long_bytes_din(input_split_U0_long_bytes_din),
    .long_bytes_num_data_valid(long_bytes_num_data_valid),
    .long_bytes_fifo_cap(long_bytes_fifo_cap),
    .long_bytes_full_n(long_bytes_full_n),
    .long_bytes_write(input_split_U0_long_bytes_write),
    .ap_return_0(input_split_U0_ap_return_0),
    .ap_return_1(input_split_U0_ap_return_1)
);

krnl_proj_split_matcher_engine_1720_16_s matcher_engine_1720_16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(matcher_engine_1720_16_U0_ap_start),
    .ap_done(matcher_engine_1720_16_U0_ap_done),
    .ap_continue(matcher_engine_1720_16_U0_ap_continue),
    .ap_idle(matcher_engine_1720_16_U0_ap_idle),
    .ap_ready(matcher_engine_1720_16_U0_ap_ready),
    .short_bytes_dout(short_bytes_dout),
    .short_bytes_num_data_valid(short_bytes_num_data_valid),
    .short_bytes_fifo_cap(short_bytes_fifo_cap),
    .short_bytes_empty_n(short_bytes_empty_n),
    .short_bytes_read(matcher_engine_1720_16_U0_short_bytes_read),
    .short_matches_din(matcher_engine_1720_16_U0_short_matches_din),
    .short_matches_num_data_valid(short_matches_num_data_valid),
    .short_matches_fifo_cap(short_matches_fifo_cap),
    .short_matches_full_n(short_matches_full_n),
    .short_matches_write(matcher_engine_1720_16_U0_short_matches_write)
);

krnl_proj_split_matcher_engine_957_214_s matcher_engine_957_214_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(matcher_engine_957_214_U0_ap_start),
    .ap_done(matcher_engine_957_214_U0_ap_done),
    .ap_continue(matcher_engine_957_214_U0_ap_continue),
    .ap_idle(matcher_engine_957_214_U0_ap_idle),
    .ap_ready(matcher_engine_957_214_U0_ap_ready),
    .long_bytes_dout(long_bytes_dout),
    .long_bytes_num_data_valid(long_bytes_num_data_valid),
    .long_bytes_fifo_cap(long_bytes_fifo_cap),
    .long_bytes_empty_n(long_bytes_empty_n),
    .long_bytes_read(matcher_engine_957_214_U0_long_bytes_read),
    .long_matches_din(matcher_engine_957_214_U0_long_matches_din),
    .long_matches_num_data_valid(long_matches_num_data_valid),
    .long_matches_fifo_cap(long_matches_fifo_cap),
    .long_matches_full_n(long_matches_full_n),
    .long_matches_write(matcher_engine_957_214_U0_long_matches_write)
);

krnl_proj_split_merge_matches merge_matches_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(merge_matches_U0_ap_start),
    .ap_done(merge_matches_U0_ap_done),
    .ap_continue(merge_matches_U0_ap_continue),
    .ap_idle(merge_matches_U0_ap_idle),
    .ap_ready(merge_matches_U0_ap_ready),
    .short_matches_dout(short_matches_dout),
    .short_matches_num_data_valid(short_matches_num_data_valid),
    .short_matches_fifo_cap(short_matches_fifo_cap),
    .short_matches_empty_n(short_matches_empty_n),
    .short_matches_read(merge_matches_U0_short_matches_read),
    .long_matches_dout(long_matches_dout),
    .long_matches_num_data_valid(long_matches_num_data_valid),
    .long_matches_fifo_cap(long_matches_fifo_cap),
    .long_matches_empty_n(long_matches_empty_n),
    .long_matches_read(merge_matches_U0_long_matches_read),
    .output_stream_TDATA(merge_matches_U0_output_stream_TDATA),
    .output_stream_TVALID(merge_matches_U0_output_stream_TVALID),
    .output_stream_TREADY(output_stream_TREADY),
    .output_stream_TKEEP(merge_matches_U0_output_stream_TKEEP),
    .output_stream_TSTRB(merge_matches_U0_output_stream_TSTRB),
    .output_stream_TUSER(merge_matches_U0_output_stream_TUSER),
    .output_stream_TLAST(merge_matches_U0_output_stream_TLAST),
    .output_stream_TID(merge_matches_U0_output_stream_TID),
    .output_stream_TDEST(merge_matches_U0_output_stream_TDEST),
    .p_read(dest_channel_dout)
);

krnl_proj_split_Block_entry211_proc Block_entry211_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry211_proc_U0_ap_start),
    .ap_done(Block_entry211_proc_U0_ap_done),
    .ap_continue(Block_entry211_proc_U0_ap_continue),
    .ap_idle(Block_entry211_proc_U0_ap_idle),
    .ap_ready(Block_entry211_proc_U0_ap_ready),
    .p_read(bytes_channel_dout),
    .processed_bytes(Block_entry211_proc_U0_processed_bytes),
    .processed_bytes_ap_vld(Block_entry211_proc_U0_processed_bytes_ap_vld),
    .processed_cycles(Block_entry211_proc_U0_processed_cycles),
    .processed_cycles_ap_vld(Block_entry211_proc_U0_processed_cycles_ap_vld)
);

krnl_proj_split_fifo_w9_d64_S short_bytes_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(input_split_U0_short_bytes_din),
    .if_full_n(short_bytes_full_n),
    .if_write(input_split_U0_short_bytes_write),
    .if_dout(short_bytes_dout),
    .if_num_data_valid(short_bytes_num_data_valid),
    .if_fifo_cap(short_bytes_fifo_cap),
    .if_empty_n(short_bytes_empty_n),
    .if_read(matcher_engine_1720_16_U0_short_bytes_read)
);

krnl_proj_split_fifo_w9_d64_S long_bytes_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(input_split_U0_long_bytes_din),
    .if_full_n(long_bytes_full_n),
    .if_write(input_split_U0_long_bytes_write),
    .if_dout(long_bytes_dout),
    .if_num_data_valid(long_bytes_num_data_valid),
    .if_fifo_cap(long_bytes_fifo_cap),
    .if_empty_n(long_bytes_empty_n),
    .if_read(matcher_engine_957_214_U0_long_bytes_read)
);

krnl_proj_split_fifo_w16_d3_S dest_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(input_split_U0_ap_return_0),
    .if_full_n(dest_channel_full_n),
    .if_write(ap_channel_done_dest_channel),
    .if_dout(dest_channel_dout),
    .if_num_data_valid(dest_channel_num_data_valid),
    .if_fifo_cap(dest_channel_fifo_cap),
    .if_empty_n(dest_channel_empty_n),
    .if_read(merge_matches_U0_ap_ready)
);

krnl_proj_split_fifo_w64_d2_S bytes_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(input_split_U0_ap_return_1),
    .if_full_n(bytes_channel_full_n),
    .if_write(ap_channel_done_bytes_channel),
    .if_dout(bytes_channel_dout),
    .if_num_data_valid(bytes_channel_num_data_valid),
    .if_fifo_cap(bytes_channel_fifo_cap),
    .if_empty_n(bytes_channel_empty_n),
    .if_read(Block_entry211_proc_U0_ap_ready)
);

krnl_proj_split_fifo_w33_d64_A short_matches_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(matcher_engine_1720_16_U0_short_matches_din),
    .if_full_n(short_matches_full_n),
    .if_write(matcher_engine_1720_16_U0_short_matches_write),
    .if_dout(short_matches_dout),
    .if_num_data_valid(short_matches_num_data_valid),
    .if_fifo_cap(short_matches_fifo_cap),
    .if_empty_n(short_matches_empty_n),
    .if_read(merge_matches_U0_short_matches_read)
);

krnl_proj_split_fifo_w33_d64_A long_matches_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(matcher_engine_957_214_U0_long_matches_din),
    .if_full_n(long_matches_full_n),
    .if_write(matcher_engine_957_214_U0_long_matches_write),
    .if_dout(long_matches_dout),
    .if_num_data_valid(long_matches_num_data_valid),
    .if_fifo_cap(long_matches_fifo_cap),
    .if_empty_n(long_matches_empty_n),
    .if_read(merge_matches_U0_long_matches_read)
);

krnl_proj_split_start_for_matcher_engine_1720_16_U0 start_for_matcher_engine_1720_16_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_matcher_engine_1720_16_U0_din),
    .if_full_n(start_for_matcher_engine_1720_16_U0_full_n),
    .if_write(input_split_U0_start_write),
    .if_dout(start_for_matcher_engine_1720_16_U0_dout),
    .if_empty_n(start_for_matcher_engine_1720_16_U0_empty_n),
    .if_read(matcher_engine_1720_16_U0_ap_ready)
);

krnl_proj_split_start_for_matcher_engine_957_214_U0 start_for_matcher_engine_957_214_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_matcher_engine_957_214_U0_din),
    .if_full_n(start_for_matcher_engine_957_214_U0_full_n),
    .if_write(input_split_U0_start_write),
    .if_dout(start_for_matcher_engine_957_214_U0_dout),
    .if_empty_n(start_for_matcher_engine_957_214_U0_empty_n),
    .if_read(matcher_engine_957_214_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_bytes_channel <= 1'b0;
    end else begin
        if (((input_split_U0_ap_done & input_split_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bytes_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bytes_channel <= ap_sync_channel_write_bytes_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_dest_channel <= 1'b0;
    end else begin
        if (((input_split_U0_ap_done & input_split_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_dest_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_dest_channel <= ap_sync_channel_write_dest_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign Block_entry211_proc_U0_ap_continue = ap_sync_continue;

assign Block_entry211_proc_U0_ap_start = bytes_channel_empty_n;

assign ap_channel_done_bytes_channel = (input_split_U0_ap_done & (ap_sync_reg_channel_write_bytes_channel ^ 1'b1));

assign ap_channel_done_dest_channel = (input_split_U0_ap_done & (ap_sync_reg_channel_write_dest_channel ^ 1'b1));

assign ap_done = ap_sync_done;

assign ap_idle = (merge_matches_U0_ap_idle & matcher_engine_957_214_U0_ap_idle & matcher_engine_1720_16_U0_ap_idle & input_split_U0_ap_idle & (bytes_channel_empty_n ^ 1'b1) & (dest_channel_empty_n ^ 1'b1) & Block_entry211_proc_U0_ap_idle);

assign ap_ready = input_split_U0_ap_ready;

assign ap_sync_channel_write_bytes_channel = ((bytes_channel_full_n & ap_channel_done_bytes_channel) | ap_sync_reg_channel_write_bytes_channel);

assign ap_sync_channel_write_dest_channel = ((dest_channel_full_n & ap_channel_done_dest_channel) | ap_sync_reg_channel_write_dest_channel);

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (merge_matches_U0_ap_done & Block_entry211_proc_U0_ap_done);

assign input_split_U0_ap_continue = (ap_sync_channel_write_dest_channel & ap_sync_channel_write_bytes_channel);

assign input_split_U0_ap_start = ap_start;

assign input_split_U0_start_full_n = (start_for_matcher_engine_957_214_U0_full_n & start_for_matcher_engine_1720_16_U0_full_n);

assign input_stream_TREADY = input_split_U0_input_stream_TREADY;

assign matcher_engine_1720_16_U0_ap_continue = 1'b1;

assign matcher_engine_1720_16_U0_ap_start = start_for_matcher_engine_1720_16_U0_empty_n;

assign matcher_engine_957_214_U0_ap_continue = 1'b1;

assign matcher_engine_957_214_U0_ap_start = start_for_matcher_engine_957_214_U0_empty_n;

assign merge_matches_U0_ap_continue = ap_sync_continue;

assign merge_matches_U0_ap_start = dest_channel_empty_n;

assign output_stream_TDATA = merge_matches_U0_output_stream_TDATA;

assign output_stream_TDEST = merge_matches_U0_output_stream_TDEST;

assign output_stream_TID = merge_matches_U0_output_stream_TID;

assign output_stream_TKEEP = merge_matches_U0_output_stream_TKEEP;

assign output_stream_TLAST = merge_matches_U0_output_stream_TLAST;

assign output_stream_TSTRB = merge_matches_U0_output_stream_TSTRB;

assign output_stream_TUSER = merge_matches_U0_output_stream_TUSER;

assign output_stream_TVALID = merge_matches_U0_output_stream_TVALID;

assign start_for_matcher_engine_1720_16_U0_din = 1'b1;

assign start_for_matcher_engine_957_214_U0_din = 1'b1;

endmodule //krnl_proj_split
