// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module krnl_proj_split_input_split (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_stream_TDATA,
        input_stream_TVALID,
        input_stream_TREADY,
        input_stream_TKEEP,
        input_stream_TSTRB,
        input_stream_TUSER,
        input_stream_TLAST,
        input_stream_TID,
        input_stream_TDEST,
        short_bytes_din,
        short_bytes_num_data_valid,
        short_bytes_fifo_cap,
        short_bytes_full_n,
        short_bytes_write,
        long_bytes_din,
        long_bytes_num_data_valid,
        long_bytes_fifo_cap,
        long_bytes_full_n,
        long_bytes_write,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] input_stream_TDATA;
input   input_stream_TVALID;
output   input_stream_TREADY;
input  [63:0] input_stream_TKEEP;
input  [63:0] input_stream_TSTRB;
input  [0:0] input_stream_TUSER;
input  [0:0] input_stream_TLAST;
input  [0:0] input_stream_TID;
input  [15:0] input_stream_TDEST;
output  [8:0] short_bytes_din;
input  [6:0] short_bytes_num_data_valid;
input  [6:0] short_bytes_fifo_cap;
input   short_bytes_full_n;
output   short_bytes_write;
output  [8:0] long_bytes_din;
input  [6:0] long_bytes_num_data_valid;
input  [6:0] long_bytes_fifo_cap;
input   long_bytes_full_n;
output   long_bytes_write;
output  [15:0] ap_return_0;
output  [63:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg start_write;
reg[8:0] short_bytes_din;
reg short_bytes_write;
reg[8:0] long_bytes_din;
reg long_bytes_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_stream_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg    short_bytes_blk_n;
wire    ap_CS_fsm_state5;
reg   [0:0] in_word_last_reg_219;
reg    long_bytes_blk_n;
reg   [511:0] in_word_data_reg_209;
reg   [63:0] in_word_keep_reg_214;
reg   [15:0] in_word_dest_reg_223;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_idle;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_ready;
wire   [8:0] grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write;
wire   [8:0] grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write;
wire   [63:0] grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out_ap_vld;
wire   [63:0] grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out;
wire    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out_ap_vld;
reg    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [63:0] empty_fu_58;
reg    ap_block_state5;
reg    ap_block_state1;
reg   [63:0] add_i_i5_fu_62;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_input_stream_V_data_V_U_apdone_blk;
wire   [511:0] input_stream_TDATA_int_regslice;
wire    input_stream_TVALID_int_regslice;
reg    input_stream_TREADY_int_regslice;
wire    regslice_both_input_stream_V_data_V_U_ack_in;
wire    regslice_both_input_stream_V_keep_V_U_apdone_blk;
wire   [63:0] input_stream_TKEEP_int_regslice;
wire    regslice_both_input_stream_V_keep_V_U_vld_out;
wire    regslice_both_input_stream_V_keep_V_U_ack_in;
wire    regslice_both_input_stream_V_strb_V_U_apdone_blk;
wire   [63:0] input_stream_TSTRB_int_regslice;
wire    regslice_both_input_stream_V_strb_V_U_vld_out;
wire    regslice_both_input_stream_V_strb_V_U_ack_in;
wire    regslice_both_input_stream_V_user_V_U_apdone_blk;
wire   [0:0] input_stream_TUSER_int_regslice;
wire    regslice_both_input_stream_V_user_V_U_vld_out;
wire    regslice_both_input_stream_V_user_V_U_ack_in;
wire    regslice_both_input_stream_V_last_V_U_apdone_blk;
wire   [0:0] input_stream_TLAST_int_regslice;
wire    regslice_both_input_stream_V_last_V_U_vld_out;
wire    regslice_both_input_stream_V_last_V_U_ack_in;
wire    regslice_both_input_stream_V_id_V_U_apdone_blk;
wire   [0:0] input_stream_TID_int_regslice;
wire    regslice_both_input_stream_V_id_V_U_vld_out;
wire    regslice_both_input_stream_V_id_V_U_ack_in;
wire    regslice_both_input_stream_V_dest_V_U_apdone_blk;
wire   [15:0] input_stream_TDEST_int_regslice;
wire    regslice_both_input_stream_V_dest_V_U_vld_out;
wire    regslice_both_input_stream_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg = 1'b0;
#0 empty_fu_58 = 64'd0;
#0 add_i_i5_fu_62 = 64'd0;
end

krnl_proj_split_input_split_Pipeline_VITIS_LOOP_39_2 grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start),
    .ap_done(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done),
    .ap_idle(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_idle),
    .ap_ready(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_ready),
    .short_bytes_din(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din),
    .short_bytes_num_data_valid(7'd0),
    .short_bytes_fifo_cap(7'd0),
    .short_bytes_full_n(short_bytes_full_n),
    .short_bytes_write(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write),
    .long_bytes_din(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din),
    .long_bytes_num_data_valid(7'd0),
    .long_bytes_fifo_cap(7'd0),
    .long_bytes_full_n(long_bytes_full_n),
    .long_bytes_write(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write),
    .add_i_i5(add_i_i5_fu_62),
    .empty(empty_fu_58),
    .in_word_keep(in_word_keep_reg_214),
    .in_word_data(in_word_data_reg_209),
    .byte_count_write_assign_out(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out),
    .byte_count_write_assign_out_ap_vld(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out_ap_vld),
    .p_out(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out),
    .p_out_ap_vld(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out_ap_vld)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 512 ))
regslice_both_input_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TDATA),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_data_V_U_ack_in),
    .data_out(input_stream_TDATA_int_regslice),
    .vld_out(input_stream_TVALID_int_regslice),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_data_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TKEEP),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_keep_V_U_ack_in),
    .data_out(input_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_input_stream_V_keep_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_keep_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 64 ))
regslice_both_input_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TSTRB),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_strb_V_U_ack_in),
    .data_out(input_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_input_stream_V_strb_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_strb_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TUSER),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_user_V_U_ack_in),
    .data_out(input_stream_TUSER_int_regslice),
    .vld_out(regslice_both_input_stream_V_user_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_user_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TLAST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_last_V_U_ack_in),
    .data_out(input_stream_TLAST_int_regslice),
    .vld_out(regslice_both_input_stream_V_last_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_last_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 1 ))
regslice_both_input_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TID),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_id_V_U_ack_in),
    .data_out(input_stream_TID_int_regslice),
    .vld_out(regslice_both_input_stream_V_id_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_id_V_U_apdone_blk)
);

krnl_proj_split_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(input_stream_TDEST),
    .vld_in(input_stream_TVALID),
    .ack_in(regslice_both_input_stream_V_dest_V_U_ack_in),
    .data_out(input_stream_TDEST_int_regslice),
    .vld_out(regslice_both_input_stream_V_dest_V_U_vld_out),
    .ack_out(input_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_ready == 1'b1)) begin
            grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        add_i_i5_fu_62 <= 64'd0;
    end else if (((in_word_last_reg_219 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        add_i_i5_fu_62 <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_fu_58 <= 64'd0;
    end else if (((in_word_last_reg_219 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        empty_fu_58 <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((input_stream_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_word_data_reg_209 <= input_stream_TDATA_int_regslice;
        in_word_dest_reg_223 <= input_stream_TDEST_int_regslice;
        in_word_keep_reg_214 <= input_stream_TKEEP_int_regslice;
        in_word_last_reg_219 <= input_stream_TLAST_int_regslice;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input_stream_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_stream_TDATA_blk_n = input_stream_TVALID_int_regslice;
    end else begin
        input_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input_stream_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        input_stream_TREADY_int_regslice = 1'b1;
    end else begin
        input_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        long_bytes_blk_n = long_bytes_full_n;
    end else begin
        long_bytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        long_bytes_din = 9'd256;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        long_bytes_din = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din;
    end else begin
        long_bytes_din = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        long_bytes_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        long_bytes_write = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write;
    end else begin
        long_bytes_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        short_bytes_blk_n = short_bytes_full_n;
    end else begin
        short_bytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        short_bytes_din = 9'd256;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        short_bytes_din = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din;
    end else begin
        short_bytes_din = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din;
    end
end

always @ (*) begin
    if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
        short_bytes_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        short_bytes_write = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write;
    end else begin
        short_bytes_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((input_stream_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((in_word_last_reg_219 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((in_word_last_reg_219 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (1'b0 == ap_block_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state5 = (((in_word_last_reg_219 == 1'd1) & (long_bytes_full_n == 1'b0)) | ((in_word_last_reg_219 == 1'd1) & (short_bytes_full_n == 1'b0)));
end

assign ap_ready = internal_ap_ready;

assign ap_return_0 = in_word_dest_reg_223;

assign ap_return_1 = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out;

assign grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start = grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg;

assign input_stream_TREADY = regslice_both_input_stream_V_data_V_U_ack_in;

assign start_out = real_start;

endmodule //krnl_proj_split_input_split
