-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity krnl_proj_split_input_split is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    input_stream_TDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    input_stream_TVALID : IN STD_LOGIC;
    input_stream_TREADY : OUT STD_LOGIC;
    input_stream_TKEEP : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream_TSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    input_stream_TDEST : IN STD_LOGIC_VECTOR (15 downto 0);
    short_bytes_din : OUT STD_LOGIC_VECTOR (8 downto 0);
    short_bytes_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    short_bytes_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    short_bytes_full_n : IN STD_LOGIC;
    short_bytes_write : OUT STD_LOGIC;
    long_bytes_din : OUT STD_LOGIC_VECTOR (8 downto 0);
    long_bytes_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    long_bytes_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    long_bytes_full_n : IN STD_LOGIC;
    long_bytes_write : OUT STD_LOGIC;
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of krnl_proj_split_input_split is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal input_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal short_bytes_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal in_word_last_reg_219 : STD_LOGIC_VECTOR (0 downto 0);
    signal long_bytes_blk_n : STD_LOGIC;
    signal in_word_data_reg_209 : STD_LOGIC_VECTOR (511 downto 0);
    signal in_word_keep_reg_214 : STD_LOGIC_VECTOR (63 downto 0);
    signal in_word_dest_reg_223 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_idle : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_ready : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out_ap_vld : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out_ap_vld : STD_LOGIC;
    signal grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal empty_fu_58 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_block_state5 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal add_i_i5_fu_62 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_input_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (511 downto 0);
    signal input_stream_TVALID_int_regslice : STD_LOGIC;
    signal input_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_input_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal regslice_both_input_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_input_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_input_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal input_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_input_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_input_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component krnl_proj_split_input_split_Pipeline_VITIS_LOOP_39_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        short_bytes_din : OUT STD_LOGIC_VECTOR (8 downto 0);
        short_bytes_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        short_bytes_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        short_bytes_full_n : IN STD_LOGIC;
        short_bytes_write : OUT STD_LOGIC;
        long_bytes_din : OUT STD_LOGIC_VECTOR (8 downto 0);
        long_bytes_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        long_bytes_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        long_bytes_full_n : IN STD_LOGIC;
        long_bytes_write : OUT STD_LOGIC;
        add_i_i5 : IN STD_LOGIC_VECTOR (63 downto 0);
        empty : IN STD_LOGIC_VECTOR (63 downto 0);
        in_word_keep : IN STD_LOGIC_VECTOR (63 downto 0);
        in_word_data : IN STD_LOGIC_VECTOR (511 downto 0);
        byte_count_write_assign_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        byte_count_write_assign_out_ap_vld : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;


    component krnl_proj_split_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108 : component krnl_proj_split_input_split_Pipeline_VITIS_LOOP_39_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start,
        ap_done => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done,
        ap_idle => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_idle,
        ap_ready => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_ready,
        short_bytes_din => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din,
        short_bytes_num_data_valid => ap_const_lv7_0,
        short_bytes_fifo_cap => ap_const_lv7_0,
        short_bytes_full_n => short_bytes_full_n,
        short_bytes_write => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write,
        long_bytes_din => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din,
        long_bytes_num_data_valid => ap_const_lv7_0,
        long_bytes_fifo_cap => ap_const_lv7_0,
        long_bytes_full_n => long_bytes_full_n,
        long_bytes_write => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write,
        add_i_i5 => add_i_i5_fu_62,
        empty => empty_fu_58,
        in_word_keep => in_word_keep_reg_214,
        in_word_data => in_word_data_reg_209,
        byte_count_write_assign_out => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out,
        byte_count_write_assign_out_ap_vld => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out_ap_vld,
        p_out => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out,
        p_out_ap_vld => grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out_ap_vld);

    regslice_both_input_stream_V_data_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 512)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TDATA,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_data_V_U_ack_in,
        data_out => input_stream_TDATA_int_regslice,
        vld_out => input_stream_TVALID_int_regslice,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_data_V_U_apdone_blk);

    regslice_both_input_stream_V_keep_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TKEEP,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_keep_V_U_ack_in,
        data_out => input_stream_TKEEP_int_regslice,
        vld_out => regslice_both_input_stream_V_keep_V_U_vld_out,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_keep_V_U_apdone_blk);

    regslice_both_input_stream_V_strb_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TSTRB,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_strb_V_U_ack_in,
        data_out => input_stream_TSTRB_int_regslice,
        vld_out => regslice_both_input_stream_V_strb_V_U_vld_out,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_strb_V_U_apdone_blk);

    regslice_both_input_stream_V_user_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TUSER,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_user_V_U_ack_in,
        data_out => input_stream_TUSER_int_regslice,
        vld_out => regslice_both_input_stream_V_user_V_U_vld_out,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_user_V_U_apdone_blk);

    regslice_both_input_stream_V_last_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TLAST,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_last_V_U_ack_in,
        data_out => input_stream_TLAST_int_regslice,
        vld_out => regslice_both_input_stream_V_last_V_U_vld_out,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_last_V_U_apdone_blk);

    regslice_both_input_stream_V_id_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TID,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_id_V_U_ack_in,
        data_out => input_stream_TID_int_regslice,
        vld_out => regslice_both_input_stream_V_id_V_U_vld_out,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_id_V_U_apdone_blk);

    regslice_both_input_stream_V_dest_V_U : component krnl_proj_split_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => input_stream_TDEST,
        vld_in => input_stream_TVALID,
        ack_in => regslice_both_input_stream_V_dest_V_U_ack_in,
        data_out => input_stream_TDEST_int_regslice,
        vld_out => regslice_both_input_stream_V_dest_V_U_vld_out,
        ack_out => input_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_input_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_ready = ap_const_logic_1)) then 
                    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    add_i_i5_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                add_i_i5_fu_62 <= ap_const_lv64_0;
            elsif (((in_word_last_reg_219 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                add_i_i5_fu_62 <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out;
            end if; 
        end if;
    end process;

    empty_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                empty_fu_58 <= ap_const_lv64_0;
            elsif (((in_word_last_reg_219 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                empty_fu_58 <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_p_out;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_stream_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                in_word_data_reg_209 <= input_stream_TDATA_int_regslice;
                in_word_dest_reg_223 <= input_stream_TDEST_int_regslice;
                in_word_keep_reg_214 <= input_stream_TKEEP_int_regslice;
                in_word_last_reg_219 <= input_stream_TLAST_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, in_word_last_reg_219, grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done, ap_CS_fsm_state4, ap_block_state5, ap_block_state1, input_stream_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((input_stream_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((in_word_last_reg_219 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(input_stream_TVALID_int_regslice)
    begin
        if ((input_stream_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done)
    begin
        if ((grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state5_assign_proc : process(short_bytes_full_n, long_bytes_full_n, in_word_last_reg_219)
    begin
                ap_block_state5 <= (((in_word_last_reg_219 = ap_const_lv1_1) and (long_bytes_full_n = ap_const_logic_0)) or ((in_word_last_reg_219 = ap_const_lv1_1) and (short_bytes_full_n = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, in_word_last_reg_219, ap_block_state5)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    ap_return_0 <= in_word_dest_reg_223;
    ap_return_1 <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_byte_count_write_assign_out;
    grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_ap_start_reg;

    input_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, input_stream_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            input_stream_TDATA_blk_n <= input_stream_TVALID_int_regslice;
        else 
            input_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_stream_TREADY <= regslice_both_input_stream_V_data_V_U_ack_in;

    input_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state2, input_stream_TVALID_int_regslice)
    begin
        if (((input_stream_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state5, in_word_last_reg_219, ap_block_state5)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    long_bytes_blk_n_assign_proc : process(long_bytes_full_n, ap_CS_fsm_state5, in_word_last_reg_219)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            long_bytes_blk_n <= long_bytes_full_n;
        else 
            long_bytes_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    long_bytes_din_assign_proc : process(ap_CS_fsm_state5, in_word_last_reg_219, grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din, ap_CS_fsm_state4, ap_block_state5)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
            long_bytes_din <= ap_const_lv9_100;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            long_bytes_din <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din;
        else 
            long_bytes_din <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_din;
        end if; 
    end process;


    long_bytes_write_assign_proc : process(ap_CS_fsm_state5, in_word_last_reg_219, grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write, ap_CS_fsm_state4, ap_block_state5)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
            long_bytes_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            long_bytes_write <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_long_bytes_write;
        else 
            long_bytes_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    short_bytes_blk_n_assign_proc : process(short_bytes_full_n, ap_CS_fsm_state5, in_word_last_reg_219)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            short_bytes_blk_n <= short_bytes_full_n;
        else 
            short_bytes_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    short_bytes_din_assign_proc : process(ap_CS_fsm_state5, in_word_last_reg_219, grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din, ap_CS_fsm_state4, ap_block_state5)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
            short_bytes_din <= ap_const_lv9_100;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            short_bytes_din <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din;
        else 
            short_bytes_din <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_din;
        end if; 
    end process;


    short_bytes_write_assign_proc : process(ap_CS_fsm_state5, in_word_last_reg_219, grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write, ap_CS_fsm_state4, ap_block_state5)
    begin
        if (((in_word_last_reg_219 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
            short_bytes_write <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            short_bytes_write <= grp_input_split_Pipeline_VITIS_LOOP_39_2_fu_108_short_bytes_write;
        else 
            short_bytes_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
